/**
 * Pedersen homomorphic commitments — the ADDITIVELY-HOMOMORPHIC commitment layer
 * the Merkle layer does not have. R&D, dark, unwired. (Extraction ledger wave 7:
 * the one real, non-stub capability the Grok Pedersen snippets kept gesturing at.)
 *
 * WHAT IT ADDS OVER proof-of-record.ts (Merkle):
 *   Merkle proves "this exact pick was in the committed set, unaltered" — but a
 *   verifier must OPEN the leaf (see the pick) to check it. Pedersen commitments
 *   compose: Commit(v1,r1)·Commit(v2,r2) = Commit(v1+v2, r1+r2). So a party can be
 *   handed the per-pick commitments plus a claimed AGGREGATE (total, count-scaled
 *   sum, exposure) and its aggregate blinding, and verify the aggregate is
 *   consistent with the individual commitments WITHOUT any individual value being
 *   revealed. The concrete GSE use is the pre-reveal sealed slate: prove a numeric
 *   property of tomorrow's committed slate before any game starts, reveal the
 *   picks later — a strictly stronger anti-cherry-pick story than Merkle alone.
 *
 * SECURITY — stated precisely, because crypto claims get the same data-and-method
 * discipline as everything else:
 *   - Commit(v,r) = g^v · h^r mod p in the order-q subgroup of Z_p^*.
 *   - PERFECTLY HIDING: r uniform over [0,q) makes C uniform over the subgroup,
 *     independent of v — the commitment reveals nothing about v, information-
 *     theoretically. (This is Pedersen's known trade-off vs hash commitments,
 *     which are the other way round.)
 *   - COMPUTATIONALLY BINDING under the discrete-log assumption: opening C to a
 *     different (v',r') requires knowing log_g(h), which nobody does (see the
 *     nothing-up-my-sleeve h below). NOT information-theoretically binding.
 *   - NOT POST-QUANTUM. DLOG falls to a quantum adversary. This is why Pedersen is
 *     an ADDITIVE layer here, never the sole integrity mechanism: the SHA-256
 *     Merkle commitment (proof-of-record.ts) remains the primary, hash-based,
 *     post-quantum-flavored tamper-evidence. Pedersen only adds homomorphic
 *     aggregate-verifiability on top.
 *   - This is a PURE-BigInt reference implementation: correct and deterministic,
 *     but NOT hardened (no constant-time modular exponentiation, no side-channel
 *     defenses). The VERIFICATION path (openCommitment / verifyLedgerAggregate)
 *     processes only public, revealed values, so timing leaks nothing there. The
 *     COMMIT path DOES exponentiate the secret blinding with a non-constant-time
 *     modPow — so commitment GENERATION must not run in an adversary-observable
 *     timing context (in practice blindings are minted at a CSPRNG loader
 *     boundary the caller owns). Production of a real public surface should move
 *     to a standardized group + an audited constant-time library.
 *
 * THE GROUP — generated by REPRODUCIBLE EXECUTION, not recited from memory (the
 * confident-constant trap the doctrine forbids): q is the smallest safe-prime q
 * at or above 2^255 (independently confirmed: q - 2^255 = 115095, and p = 2q+1
 * is therefore ~2^256, a 257-bit prime), found by incremental Miller-Rabin
 * search; verifyGroup() re-certifies primality at runtime so the exact value is
 * self-checking rather than trusted from this comment. (An earlier draft of THIS
 * sentence recited the offset as "+951" — the search's STARTING point, not its
 * result — and a hostile-crypto review caught it: precisely the recited-constant
 * error the module is built to avoid, fixed here.) g = 4 (a square, hence order
 * exactly q in a safe-prime group); h derived by
 * hashing the fixed public seed "GSE-pedersen-h-v1", reduced mod p and squared
 * into the subgroup — a nothing-up-my-sleeve element whose log_g(h) nobody knows.
 * verifyGroup() RE-CERTIFIES all of this at runtime (primality of q and 2q+1,
 * subgroup membership of g and h), so the constants are self-checking rather than
 * trusted. For a production surface, swap to a standardized group (e.g. an
 * RFC 3526 MODP prime or a named curve's subgroup) — re-derived, not copied here.
 *
 * Deterministic; blindings are an INPUT (a pure core cannot mint randomness).
 * Returns null on refused input, never throws on data.
 */

/** Order-q subgroup of Z_p^* in a safe-prime group p = 2q+1. Verified by verifyGroup(). */
export const PEDERSEN_P =
  115792089237316195423570985008687907853269984665640564039457584007913129870127n;
export const PEDERSEN_Q =
  57896044618658097711785492504343953926634992332820282019728792003956564935063n;
/** g = 4: a quadratic residue, hence order exactly q (q prime) in the safe-prime group. */
export const PEDERSEN_G = 4n;
/** h = (sha256("GSE-pedersen-h-v1") mod p)^2 mod p — nothing-up-my-sleeve; log_g(h) unknown. */
export const PEDERSEN_H =
  8662593458384245091556566258156614067129379654968565214918795815991630923767n;

export interface PedersenGroup {
  readonly p: bigint;
  readonly q: bigint;
  readonly g: bigint;
  readonly h: bigint;
}

export const DEFAULT_PEDERSEN_GROUP: PedersenGroup = {
  p: PEDERSEN_P,
  q: PEDERSEN_Q,
  g: PEDERSEN_G,
  h: PEDERSEN_H,
};

function modPow(base: bigint, exp: bigint, mod: bigint): bigint {
  let b = ((base % mod) + mod) % mod;
  let e = exp;
  let r = 1n;
  while (e > 0n) {
    if (e & 1n) r = (r * b) % mod;
    b = (b * b) % mod;
    e >>= 1n;
  }
  return r;
}

/** Deterministic Miller-Rabin with a fixed witness set. Probabilistic at 256 bits
 * (composite-pass prob < 4^-|witnesses|); the group is a demonstration group and
 * verifyGroup re-runs this so the check is reproducible, not trusted-from-file. */
function isProbablePrime(n: bigint, witnesses: readonly bigint[]): boolean {
  if (n < 2n) return false;
  for (const p of [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n, 37n]) {
    if (n % p === 0n) return n === p;
  }
  let d = n - 1n;
  let s = 0n;
  while ((d & 1n) === 0n) {
    d >>= 1n;
    s += 1n;
  }
  for (const a of witnesses) {
    if (a % n === 0n) continue;
    let x = modPow(a, d, n);
    if (x === 1n || x === n - 1n) continue;
    let composite = true;
    for (let i = 1n; i < s; i++) {
      x = (x * x) % n;
      if (x === n - 1n) {
        composite = false;
        break;
      }
    }
    if (composite) return false;
  }
  return true;
}

const MR_WITNESSES = [2n, 3n, 5n, 7n, 11n, 13n, 17n, 19n, 23n, 29n, 31n, 37n];

/**
 * Re-certify a group at runtime: q prime, p = 2q+1 prime, g and h are non-identity
 * order-q elements (so the subgroup and the homomorphism are as claimed). Cheap
 * enough to call in tests / at load; makes the module constants self-checking.
 */
export function verifyGroup(group: PedersenGroup = DEFAULT_PEDERSEN_GROUP): boolean {
  const { p, q, g, h } = group;
  if (p !== 2n * q + 1n) return false;
  if (!isProbablePrime(q, MR_WITNESSES)) return false;
  if (!isProbablePrime(p, MR_WITNESSES)) return false;
  // g, h in [2, p-1), order exactly q (non-identity, q-th power is identity).
  for (const x of [g, h]) {
    if (x <= 1n || x >= p) return false;
    if (modPow(x, q, p) !== 1n) return false;
  }
  if (g === h) return false;
  return true;
}

/** A commitment is just the group element C = g^v · h^r mod p. */
export type PedersenCommitment = bigint;

/**
 * Commit to a non-negative integer value with a blinding factor. Exponents are
 * reduced mod q (the subgroup order) — the caller must keep the TRUE (unreduced)
 * value and blinding for opening, and must ensure aggregate sums do not wrap mod q
 * (trivially satisfied for fixed-point-encoded bounded returns at any realistic n;
 * see encodeFixedPoint + the no-wrap note there). Returns null on refused input.
 *
 * ASYMMETRIC RANGE GUARD (intentional): a blinding >= q is REFUSED (blindings
 * must be uniform in [0,q); a value at/above q is always a caller bug), whereas a
 * value >= q is REDUCED mod q — that is correct group behavior (g has order q, so
 * g^(v+q) = g^v), not a binding break, and is the documented homomorphic contract
 * the shipped tests bless. encodeFixedPoint keeps real values ~50 orders of
 * magnitude below q, so the reduction never triggers on genuine input.
 */
export function commit(
  value: bigint,
  blinding: bigint,
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): PedersenCommitment | null {
  if (typeof value !== "bigint" || typeof blinding !== "bigint") return null;
  if (value < 0n || blinding < 0n) return null;
  if (blinding >= group.q) return null; // a blinding >= q is a caller bug (must be uniform in [0,q))
  const { p, q, g, h } = group;
  return (modPow(g, value % q, p) * modPow(h, blinding, p)) % p;
}

/** Homomorphic addition: Commit(v1,r1)·Commit(v2,r2) = Commit(v1+v2, r1+r2). */
export function addCommitments(
  c1: PedersenCommitment,
  c2: PedersenCommitment,
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): PedersenCommitment {
  return (((c1 % group.p) * (c2 % group.p)) % group.p + group.p) % group.p;
}

/** Product of many commitments (the aggregate commitment of a whole ledger). */
export function aggregateCommitments(
  commitments: readonly PedersenCommitment[],
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): PedersenCommitment {
  let acc = 1n;
  for (const c of commitments) acc = (acc * (((c % group.p) + group.p) % group.p)) % group.p;
  return acc;
}

/** Open (verify) a commitment against a claimed (value, blinding). */
export function openCommitment(
  commitment: PedersenCommitment,
  value: bigint,
  blinding: bigint,
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): boolean {
  const recomputed = commit(value, blinding, group);
  if (recomputed === null) return false;
  return recomputed === (((commitment % group.p) + group.p) % group.p);
}

export interface LedgerCommitmentResult {
  /** Per-value commitments (publishable; reveal nothing about the values). */
  readonly commitments: readonly PedersenCommitment[];
  /** Product of the per-value commitments = commitment to (sum values, sum blindings). */
  readonly aggregateCommitment: PedersenCommitment;
  /** Sum of the true values (the aggregate the prover will later claim). */
  readonly aggregateValue: bigint;
  /** Sum of the blindings mod q (the opener for the aggregate). */
  readonly aggregateBlinding: bigint;
}

/**
 * Commit to a whole ledger of non-negative integer values with per-value
 * blindings. Returns the individual commitments plus the aggregate opener. The
 * homomorphism means `aggregateCommitment === commit(aggregateValue % q,
 * aggregateBlinding)` — which verifyLedgerAggregate checks. Returns null if any
 * value/blinding is refused or the arrays disagree in length.
 */
export function commitLedger(
  values: readonly bigint[],
  blindings: readonly bigint[],
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): LedgerCommitmentResult | null {
  if (values.length !== blindings.length || values.length === 0) return null;
  const commitments: PedersenCommitment[] = [];
  let aggregateValue = 0n;
  let aggregateBlinding = 0n;
  for (let i = 0; i < values.length; i++) {
    const c = commit(values[i]!, blindings[i]!, group);
    if (c === null) return null;
    commitments.push(c);
    aggregateValue += values[i]!;
    aggregateBlinding = (aggregateBlinding + blindings[i]!) % group.q;
  }
  return {
    commitments,
    aggregateCommitment: aggregateCommitments(commitments, group),
    aggregateValue,
    aggregateBlinding,
  };
}

/**
 * THE payoff: verify a claimed aggregate against the per-value commitments WITHOUT
 * any individual value. True iff the product of the commitments opens to
 * (claimedAggregateValue, claimedAggregateBlinding). A prover publishes the
 * commitments pre-reveal, then reveals only the aggregate + its blinding; anyone
 * runs this. A doctored aggregate (off by one, wrong blinding) fails.
 */
export function verifyLedgerAggregate(
  commitments: readonly PedersenCommitment[],
  claimedAggregateValue: bigint,
  claimedAggregateBlinding: bigint,
  group: PedersenGroup = DEFAULT_PEDERSEN_GROUP,
): boolean {
  if (commitments.length === 0) return false;
  const product = aggregateCommitments(commitments, group);
  return openCommitment(product, claimedAggregateValue, claimedAggregateBlinding, group);
}

/**
 * Encode a bounded real (e.g. a per-bet return, or an e-process increment) into a
 * non-negative field integer via fixed-point + an offset for the negative floor.
 * value_int = round((x - min) * scale). NO-WRAP REQUIREMENT: n · (max-min) · scale
 * must stay < q for the aggregate to be exact; with q ~ 2^255, scale = 1e6, and
 * returns in [-1, 20], q / (21·1e6) ~ 2.8×10^69, so this holds for ~10^69 picks
 * — never a real constraint (independently recomputed in hostile review).
 * Returns null if x is out of [min,max] or non-finite.
 */
export function encodeFixedPoint(
  x: number,
  min = -1,
  max = 20,
  scale = 1_000_000,
): bigint | null {
  if (!Number.isFinite(x) || x < min || x > max) return null;
  return BigInt(Math.round((x - min) * scale));
}
