/**
 * Calibration Training — weekly insight prompt.
 *
 * One sentence per user per week, identifying their most actionable
 * calibration pattern. Generated by Claude API from structured calibration
 * data; persisted to UserCalibrationSnapshot.insightText.
 *
 * Spec: docs/product/calibration-training-spec.md
 * Voice rules locked.
 */

export const CALIBRATION_INSIGHT_SYSTEM_PROMPT = `You are generating a one-sentence calibration insight for a sports bettor.

Input: structured data about the user's confidence estimates and the actual
outcomes for one week.

Output: one sentence. ≤ 25 words. Identifies the user's most actionable
calibration pattern. Examples:

"You were well-calibrated on NFL spreads this week but 12% overconfident on
MLB totals."

"Your confidence on Pro picks tracked the actual win rate almost exactly.
That's calibration."

"You were under-confident across the board this week; the picks you rated
at 65% hit at 72%."

VOICE RULES
- Direct. No hedging.
- Specific. Name the sport, the pick type, the magnitude.
- No marketing language. No "great job!"
- Past tense.
- One sentence. Hard limit.
- No emoji.
- No CTAs ("keep it up," "try again next week," "upgrade for more insights").

PROHIBITED
- No "you should bet more / less."
- No "this is good for you" framing — the insight is descriptive, not
  prescriptive.
- No comparison to other users.
- No banned vocabulary from docs/positioning.md.

OUTPUT
Plain text, one sentence, no markdown, no quote marks around the output.`;

export interface CalibrationInsightInput {
  userId: string;
  weekOfYear: number;
  yearOf: number;
  totalEstimates: number;
  bandData: Record<
    string,
    { sampleSize: number; actualWinRate: number; userMidpoint: number }
  >;
  perSportData: Record<
    string,
    { sampleSize: number; calibrationDelta: number; direction: "OVER" | "UNDER" | "WELL_CALIBRATED" }
  >;
  perPickKindData: Record<
    string,
    { sampleSize: number; calibrationDelta: number; direction: "OVER" | "UNDER" | "WELL_CALIBRATED" }
  >;
}

export function buildCalibrationInsightUserPrompt(
  input: CalibrationInsightInput,
): string {
  const bandSummary = Object.entries(input.bandData)
    .map(
      ([band, data]) =>
        `  ${band}: estimated ${data.userMidpoint}%, actual ${data.actualWinRate}% (sample ${data.sampleSize})`,
    )
    .join("\n");

  const sportSummary = Object.entries(input.perSportData)
    .filter(([_, data]) => data.sampleSize >= 5)
    .map(
      ([sport, data]) =>
        `  ${sport}: ${data.direction}, delta ${data.calibrationDelta.toFixed(1)}% (sample ${data.sampleSize})`,
    )
    .join("\n");

  const pickKindSummary = Object.entries(input.perPickKindData)
    .filter(([_, data]) => data.sampleSize >= 5)
    .map(
      ([kind, data]) =>
        `  ${kind}: ${data.direction}, delta ${data.calibrationDelta.toFixed(1)}% (sample ${data.sampleSize})`,
    )
    .join("\n");

  return `User calibration data for week ${input.weekOfYear} of ${input.yearOf}:

Total estimates: ${input.totalEstimates}

By confidence band:
${bandSummary || "  (insufficient data)"}

By sport (sample ≥ 5):
${sportSummary || "  (no sport had a meaningful sample this week)"}

By pick kind (sample ≥ 5):
${pickKindSummary || "  (no pick kind had a meaningful sample this week)"}

Produce the one-sentence insight now.`;
}
