import type { FounderWorkItem } from "./founder-command";

/**
 * Executable founder backlog for the current NOVA/GSE phase.
 *
 * Every record states what, why, when, how, proof, agent work, and owner-only
 * action so a coding agent can execute without reconstructing this conversation.
 */
export const FOUNDER_WORK_SEED: readonly FounderWorkItem[] = [
  {
    id: "nova-pr-146-verification",
    title: "Make the NOVA branch honestly reviewable",
    project: "NOVA",
    lane: "LAUNCH_BLOCKER",
    state: "IN_PROGRESS",
    authority: "AGENT_INTERNAL",
    what: "Drive PR #146 through focused tests, full CI, typecheck, lint, Prisma validation, guardrails, and build evidence without merging it.",
    why: "NOVA cannot become a trusted operating layer while its own branch has unresolved verification or stale current-truth statements.",
    when: "Before adding production persistence, scheduling, external connectors, or canonical council registration.",
    how: [
      "Run the focused NOVA suite and retain diagnostic logs.",
      "Run full repository CI and classify every failure as branch-caused, base-caused, environmental, or stale-test debt.",
      "Repair only branch-caused failures in small coherent commits.",
      "Update the PR current-truth section from observed evidence.",
      "Keep the PR draft until every required gate has a reproducible receipt.",
    ],
    acceptanceCriteria: [
      "Focused NOVA tests pass.",
      "Deterministic runtime tests pass.",
      "Trust, draft-only, model-freeze, secret, rights, affiliate, and public-claim guardrails pass.",
      "Typecheck, lint, Prisma validation, workspace tests, and production build have recorded outcomes.",
      "PR description matches the implemented and unwired surfaces.",
    ],
    evidenceRequired: [
      "GitHub Actions run identifiers and conclusions",
      "retained focused-test and guardrail logs",
      "final changed-file review",
      "explicit unresolved-risk list",
    ],
    agentCanDo: [
      "Read branch diffs and CI evidence",
      "repair branch-caused code and test defects",
      "write verification reports",
      "update internal documentation",
    ],
    ownerOnly: [],
    urgency: 5,
    revenueImpact: 3,
    cashAvoidance: 3,
    strategicLeverage: 5,
    founderMinutes: 0,
    estimatedEngineeringHours: 5,
    externalActionsAllowed: false,
  },
  {
    id: "founder-ai-opportunity-audit-offer",
    title: "Package the first sellable NOVA service",
    project: "PERSONAL",
    lane: "FIRST_CASH",
    state: "READY",
    authority: "AGENT_THEN_OWNER",
    what: "Package a fixed-scope AI Opportunity, Cost, and Workflow Audit that turns a buyer's current tools, subscriptions, data, and processes into a verified savings and implementation plan.",
    why: "A service can monetize the working NOVA method before a marketplace app or subscription product has enough demand evidence.",
    when: "Immediately after the branch has a stable demonstrable proof surface; do not wait for production autonomy.",
    how: [
      "Define one buyer profile and one fixed outcome.",
      "Create intake, evidence ledger, opportunity matrix, cost model, and implementation roadmap templates.",
      "Produce an anonymized GSE/NOVA case study that contains no private employment or legal material.",
      "Create a one-page offer, scope boundary, delivery timeline, acceptance criteria, and price experiment.",
      "Prepare a lead list and message drafts without sending them.",
    ],
    acceptanceCriteria: [
      "A buyer can understand the outcome in under two minutes.",
      "Scope can be delivered by one person in a bounded number of hours.",
      "Every savings or revenue estimate is labeled and supported.",
      "Payment, intake, delivery, and revision boundaries are documented.",
      "No customer acquisition action occurs without owner approval.",
    ],
    evidenceRequired: [
      "rendered offer page",
      "sample audit output",
      "delivery checklist",
      "pricing hypothesis and margin calculation",
      "owner-ready outreach drafts",
    ],
    agentCanDo: [
      "draft and test the offer assets",
      "build the internal audit generator",
      "prepare anonymized evidence",
      "rank leads and prepare drafts",
    ],
    ownerOnly: [
      "approve public claims and price",
      "choose payment method",
      "send messages or submit marketplace profiles",
      "accept contracts and deliver client-facing judgment",
    ],
    urgency: 5,
    revenueImpact: 5,
    cashAvoidance: 1,
    strategicLeverage: 4,
    founderMinutes: 35,
    estimatedEngineeringHours: 6,
    externalActionsAllowed: false,
  },
  {
    id: "local-coding-continuity",
    title: "Remove subscription exhaustion as a development stoppage",
    project: "PERSONAL",
    lane: "COST_AVOIDANCE",
    state: "VERIFIED",
    authority: "AGENT_THEN_OWNER",
    what: "Create a local coding-agent lane using an OpenAI-compatible local runtime, bounded worktrees, repository instructions, deterministic tests, and premium-model escalation rules.",
    why: "Claude and Codex usage limits should reduce speed, not stop all mechanical engineering progress or force unplanned API spend.",
    when: "Before the next premium usage reset is consumed by routine testing, refactoring, documentation, or narrow implementation work.",
    how: [
      "Capture hardware truth before choosing a model.",
      "Install one local runtime and one appropriately sized coding model only after owner approval.",
      "Use isolated Git worktrees and deny deployment, secrets, payments, and external communication.",
      "Route mechanical implementation and test loops locally.",
      "Escalate architecture, security, payment, migration, and adversarial review to premium models.",
      "Measure task success, duration, repair count, context size, and premium tokens avoided.",
    ],
    acceptanceCriteria: [
      "One local model completes a bounded repository task through tests.",
      "The task runs in an isolated worktree.",
      "No paid fallback occurs under zero-cash mode.",
      "The result is independently reviewed before merge.",
      "A model-selection record ties task class to measured outcome.",
    ],
    evidenceRequired: [
      "hardware report",
      "model and runtime versions",
      "task transcript summary",
      "test receipt",
      "cost and elapsed-time comparison",
    ],
    agentCanDo: [
      "prepare scripts and instructions",
      "create worktree templates",
      "define evaluation tasks",
      "analyze measured outcomes",
    ],
    ownerOnly: ["approve software installation", "approve disk use", "enter any required credentials"],
    urgency: 5,
    revenueImpact: 3,
    cashAvoidance: 5,
    strategicLeverage: 5,
    founderMinutes: 20,
    estimatedEngineeringHours: 4,
    externalActionsAllowed: false,
  },
  {
    id: "nova-user-source-resolution",
    title: "Resolve the founder's new social and newsletter discoveries",
    project: "NOVA",
    lane: "COMPOUNDING_ASSET",
    state: "READY",
    authority: "AGENT_THEN_OWNER",
    what: "Process the 11 Instagram links and 17 privacy-sensitive newsletter redirects as discovery intake, then replace useful claims with canonical primary sources.",
    why: "The founder's discoveries are valuable signals, but social posts and recipient-specific redirects cannot enter the evidence graph as verified truth.",
    when: "During the next research cycle after the intake ledger and privacy controls are green.",
    how: [
      "Deduplicate by canonical locator and SHA-256.",
      "Resolve redirect destinations privately without credentials and discard tracking tokens.",
      "Identify the topic, named product, release, offer, or workflow behind each item.",
      "Locate current first-party documentation for each material claim.",
      "Create opportunity or risk candidates only from supported evidence.",
    ],
    acceptanceCriteria: [
      "All 28 discoveries have a final disposition.",
      "No raw recipient-specific tracking URL is committed.",
      "Every promoted claim cites a primary source.",
      "Unsupported or inaccessible items remain discovery-only.",
      "No media is copied or used for training without rights clearance.",
    ],
    evidenceRequired: ["source-resolution ledger", "canonical destination map", "primary-source citations", "rights verdicts"],
    agentCanDo: ["deduplicate", "research public primary sources", "draft dispositions", "update internal ledgers"],
    ownerOnly: ["provide access when a source is private", "approve any rights-sensitive reuse"],
    urgency: 3,
    revenueImpact: 2,
    cashAvoidance: 2,
    strategicLeverage: 4,
    founderMinutes: 10,
    estimatedEngineeringHours: 5,
    externalActionsAllowed: false,
  },
  {
    id: "nova-chatgpt-read-app",
    title: "Build the read-only NOVA app for ChatGPT and Codex",
    project: "NOVA",
    lane: "COMPOUNDING_ASSET",
    state: "VERIFIED",
    authority: "AGENT_THEN_OWNER",
    what: "Build an MCP-backed ChatGPT app and plugin package that exposes NOVA briefs, evidence, credits truth, opportunity details, and founder queues through read-only tools and a chat-native interface.",
    why: "ChatGPT and Codex now use a shared plugin discovery surface, giving NOVA a distribution and personal-efficiency channel without duplicating its evidence core.",
    when: "After the internal read models and authentication boundary are stable; before any write-action tool is considered.",
    how: [
      "Create a dedicated MCP server package rather than embedding vendor code in the web app.",
      "Expose narrowly scoped read tools for briefs, opportunities, sources, credits, and founder decisions.",
      "Add explicit read-only annotations and deny write or external-action behavior.",
      "Create one responsive widget for evidence and money-state inspection.",
      "Add positive, negative, permission, privacy, and unsupported-query tests.",
      "Prepare submission metadata only after the real server and widget pass review.",
    ],
    acceptanceCriteria: [
      "Every tool is read-only and returns typed, bounded output.",
      "No secrets or internal-only fields reach the widget.",
      "The app is usable in ChatGPT developer mode.",
      "At least five positive and three negative submission cases pass.",
      "No claim of native digital-app payment is made without a current platform source.",
    ],
    evidenceRequired: ["MCP inspection transcript", "tool contract tests", "widget screenshots", "privacy and CSP review", "submission-readiness report"],
    agentCanDo: ["scaffold and implement the app", "write tests", "prepare submission artifacts", "run local validation"],
    ownerOnly: ["enable developer mode", "approve privacy policy", "submit for directory review", "connect production hosting"],
    urgency: 3,
    revenueImpact: 3,
    cashAvoidance: 1,
    strategicLeverage: 5,
    founderMinutes: 25,
    estimatedEngineeringHours: 14,
    externalActionsAllowed: false,
  },
  {
    id: "nova-portable-agent-skill-pack",
    title: "Package NOVA as portable skills across Claude, Codex, Copilot, and Grok Build",
    project: "NOVA",
    lane: "COMPOUNDING_ASSET",
    state: "DISCOVERED",
    authority: "AGENT_THEN_OWNER",
    what: "Create a vendor-neutral Agent Skills package for source triage, opportunity review, evidence verification, cost routing, experiment design, and nightly autopsy.",
    why: "The same governed workflow can travel across coding environments while the evidence and authority rules remain canonical in GSE.",
    when: "After the workflow contracts are stable and before maintaining separate vendor-specific prompt libraries.",
    how: [
      "Define one canonical skill contract with progressive context loading.",
      "Generate surface-specific wrappers for Claude plugins, ChatGPT/Codex plugins, Copilot skills, and Grok Build plugins.",
      "Keep tool permissions and external actions disabled by default.",
      "Add compatibility fixtures and version the skill contract independently from model prompts.",
      "Publish nowhere until supply-chain and privacy review are complete.",
    ],
    acceptanceCriteria: [
      "The same fixture produces structurally equivalent outputs across supported harnesses.",
      "Each wrapper loads only the context required for its task.",
      "No wrapper can expand its own permissions.",
      "Vendor-specific features are optional adapters, not canonical logic.",
      "A compatibility matrix records current support and drift.",
    ],
    evidenceRequired: ["canonical skill specification", "cross-harness fixtures", "permission matrix", "version and drift report"],
    agentCanDo: ["write skill files", "build wrappers", "run compatibility tests", "document installation"],
    ownerOnly: ["approve marketplace publication", "approve public repository and licensing terms"],
    urgency: 2,
    revenueImpact: 2,
    cashAvoidance: 3,
    strategicLeverage: 5,
    founderMinutes: 15,
    estimatedEngineeringHours: 10,
    externalActionsAllowed: false,
  },
  {
    id: "credit-truth-and-workload-router",
    title: "Convert startup credits into governed workload capacity",
    project: "NOVA",
    lane: "COST_AVOIDANCE",
    state: "VERIFIED",
    authority: "AGENT_THEN_OWNER",
    what: "Track startup programs through discovered, eligibility-unverified, eligible, applied, approved, activated, consumed, and expired states, then map only activated credits to compatible workloads.",
    why: "Program maximums and applications are not operating capital; value appears only when an approved balance displaces a cash expense before expiration.",
    when: "Before routing production inference, storage, compute, observability, or deployment to a credited provider.",
    how: [
      "Maintain one record per program and account.",
      "Capture eligibility, exclusions, service caps, expiration, and evidence.",
      "Prepare applications and architecture attachments without submitting them.",
      "After owner activation, allocate workloads by cash displacement, migration cost, and expiration risk.",
      "Alert before expiration and stop billable fallback when policy is zero-cash or credits-only.",
    ],
    acceptanceCriteria: [
      "Discovered programs never appear as usable balances.",
      "Every activated balance has primary evidence and an expiration date.",
      "Workloads are mapped only to covered services.",
      "Cash displacement and post-credit exit cost are measured.",
      "No application or billing activation occurs autonomously.",
    ],
    evidenceRequired: ["program ledger", "eligibility packet", "activation receipt", "workload mapping", "cash-displacement report"],
    agentCanDo: ["monitor program changes", "prepare applications", "model workload economics", "draft expiration alerts"],
    ownerOnly: ["submit applications", "accept terms", "connect accounts", "activate billing or paid services"],
    urgency: 4,
    revenueImpact: 1,
    cashAvoidance: 5,
    strategicLeverage: 4,
    founderMinutes: 30,
    estimatedEngineeringHours: 8,
    externalActionsAllowed: false,
  },
  {
    id: "nova-observability-and-evaluation",
    title: "Measure NOVA before scaling its autonomy",
    project: "NOVA",
    lane: "SECURITY_CONTINUITY",
    state: "READY",
    authority: "AGENT_INTERNAL",
    what: "Instrument source precision, retrieval failures, model use, tool calls, decision latency, experiment outcomes, and cost without sending sensitive payloads to an unreviewed vendor.",
    why: "An autonomous research system without observability cannot distinguish useful learning from stale retrieval, repeated work, cost drift, or silent permission expansion.",
    when: "Before production scheduling, broad connector activation, or LLM-assisted synthesis.",
    how: [
      "Define local-first structured telemetry and redaction rules.",
      "Measure source success, change-event precision, false alerts, queue age, model calls, spend, and owner attention.",
      "Evaluate Langfuse, ClickHouse, OpenTelemetry, SigNoz, Honeycomb, Grafana, and Datadog against the same requirements.",
      "Adopt no vendor until the smallest reversible trial has evidence.",
      "Expose an internal health and calibration surface in the cockpit.",
    ],
    acceptanceCriteria: [
      "Every NOVA cycle has a receipt and stable run id.",
      "Sensitive fields are redacted before export.",
      "False-positive and source-failure rates are visible.",
      "Model and tool costs are attributable to a task and outcome.",
      "The selected observability path has a documented exit plan.",
    ],
    evidenceRequired: ["telemetry schema", "redaction tests", "vendor comparison", "sample dashboard", "failure-injection results"],
    agentCanDo: ["implement local telemetry", "run trials", "build dashboards", "write comparisons"],
    ownerOnly: [],
    urgency: 4,
    revenueImpact: 2,
    cashAvoidance: 4,
    strategicLeverage: 5,
    founderMinutes: 0,
    estimatedEngineeringHours: 10,
    externalActionsAllowed: false,
  },
];
