import type { OpportunitySource } from "./types";

/**
 * Curated first-party discovery registry.
 *
 * A registry entry authorizes only the listed metadata capture. It does not
 * authorize installation, account creation, application submission, scraping,
 * redistribution, model training, or any commercial use of source content.
 */
export const DEFAULT_OPPORTUNITY_SOURCES: readonly OpportunitySource[] = [
  {
    id: "openai-api-changelog",
    name: "OpenAI API Changelog",
    owner: "OpenAI",
    url: "https://developers.openai.com/api/docs/changelog",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["ai_model_release", "platform_update", "security_or_deprecation"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release date", "title", "short factual change summary", "canonical link", "deprecation deadline"],
    prohibitedCapture: ["full-page archival", "redistribution of documentation", "credentials"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Primary source for API models, endpoints, features, migrations, and retirements.",
  },
  {
    id: "openai-chatgpt-release-notes",
    name: "ChatGPT Release Notes",
    owner: "OpenAI",
    url: "https://help.openai.com/en/articles/6825453-chatgpt-release-notes",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["platform_update", "ai_model_release", "app_product"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release date", "feature title", "availability", "canonical link"],
    prohibitedCapture: ["full article copy", "account data"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Tracks new ChatGPT surfaces, scheduled work, connectors, plan availability, and model changes.",
  },
  {
    id: "openai-codex-releases",
    name: "OpenAI Codex Releases",
    owner: "OpenAI",
    url: "https://api.github.com/repos/openai/codex/releases",
    transport: "github_releases",
    authority: "official_vendor",
    evidenceTier: "official_repository_release",
    classes: ["developer_tool", "platform_update", "security_or_deprecation"],
    cadence: "event",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release tag", "published timestamp", "release title", "release URL", "asset metadata"],
    prohibitedCapture: ["automatic binary installation", "unreviewed release execution"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Release metadata is discovery evidence only; every upgrade remains sandboxed and review-gated.",
  },
  {
    id: "anthropic-platform-release-notes",
    name: "Claude Platform Release Notes",
    owner: "Anthropic",
    url: "https://platform.claude.com/docs/en/release-notes/overview",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["ai_model_release", "platform_update", "security_or_deprecation", "cost_reduction"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release date", "title", "short factual change summary", "pricing fact", "deadline", "canonical link"],
    prohibitedCapture: ["full documentation copy", "credentials", "private console content"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Primary source for Claude API, Managed Agents, SDK, pricing, migration, and deprecation changes.",
  },
  {
    id: "anthropic-claude-code-releases",
    name: "Claude Code Releases",
    owner: "Anthropic",
    url: "https://api.github.com/repos/anthropics/claude-code/releases",
    transport: "github_releases",
    authority: "official_vendor",
    evidenceTier: "official_repository_release",
    classes: ["developer_tool", "platform_update", "security_or_deprecation"],
    cadence: "event",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release tag", "published timestamp", "release title", "release URL", "release metadata"],
    prohibitedCapture: ["automatic upgrade", "automatic plugin installation"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Use release diffs to detect features, breaking changes, and usage-control improvements.",
  },
  {
    id: "google-vertex-ai-release-notes",
    name: "Vertex AI Generative AI Release Notes",
    owner: "Google Cloud",
    url: "https://docs.cloud.google.com/vertex-ai/generative-ai/docs/release-notes",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["ai_model_release", "platform_update", "security_or_deprecation", "api_or_data_feed"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["release date", "feature or model title", "availability", "deprecation deadline", "canonical link"],
    prohibitedCapture: ["full documentation copy", "console data"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Includes model availability, Agent Platform, evaluation, RAG, pricing, and retirement changes.",
  },
  {
    id: "github-changelog",
    name: "GitHub Changelog",
    owner: "GitHub",
    url: "https://github.blog/changelog/feed/",
    transport: "rss",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["developer_tool", "platform_update", "security_or_deprecation"],
    cadence: "event",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["headline", "published timestamp", "category", "canonical link", "short factual summary"],
    prohibitedCapture: ["full article redistribution"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Tracks GitHub, Actions, Copilot, API, marketplace, security, and retirement changes.",
  },
  {
    id: "huggingface-hub-discovery",
    name: "Hugging Face Hub Discovery API",
    owner: "Hugging Face",
    url: "https://huggingface.co/api/models?sort=lastModified&direction=-1&limit=100",
    transport: "json_api",
    authority: "official_registry",
    evidenceTier: "official_primary",
    classes: ["ai_model_release", "api_or_data_feed", "developer_tool", "research_signal"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["repository id", "last modified", "tags", "license metadata", "model card link", "download metadata"],
    prohibitedCapture: ["automatic model download", "training without license review", "gated artifact access"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Discovery is not approval. Every model, dataset, or Space receives license, security, and benchmark review.",
  },
  {
    id: "mcp-official-registry",
    name: "Official MCP Registry",
    owner: "Model Context Protocol project",
    url: "https://registry.modelcontextprotocol.io/",
    transport: "json_api",
    authority: "official_registry",
    evidenceTier: "official_primary",
    classes: ["developer_tool", "api_or_data_feed", "workflow_arbitrage", "app_product"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["server name", "version", "description", "publisher metadata", "repository link", "published timestamp"],
    prohibitedCapture: ["automatic install", "automatic invocation", "credential grant", "trust inference from registry presence"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "The registry proves discoverability and namespace ownership, not runtime safety or commercial fitness.",
  },
  {
    id: "agentic-resource-discovery",
    name: "Agentic Resource Discovery Specification",
    owner: "ARD community",
    url: "https://agenticresourcediscovery.org/",
    transport: "html_changelog",
    authority: "standards_body",
    evidenceTier: "regulator_or_standards_body",
    classes: ["platform_update", "developer_tool", "api_or_data_feed", "workflow_arbitrage"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["spec version", "release date", "resource types", "canonical links", "compatibility changes"],
    prohibitedCapture: ["automatic registry trust", "automatic resource invocation"],
    requiresTermsReview: false,
    enabledByDefault: true,
    notes: "Monitor the emerging discovery layer for agents, tools, skills, APIs, and workflows.",
  },
  {
    id: "arxiv-ai-research",
    name: "arXiv AI and Software Engineering Feed",
    owner: "arXiv / Cornell University",
    url: "https://export.arxiv.org/api/query",
    transport: "atom",
    authority: "research_repository",
    evidenceTier: "official_primary",
    classes: ["research_signal", "ai_model_release", "developer_tool"],
    cadence: "daily",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["paper title", "authors", "abstract metadata", "submission date", "categories", "canonical link"],
    prohibitedCapture: ["claiming replication from publication alone", "training on paper content without rights review"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Research is a hypothesis source. Product adoption requires reproduction or stronger evidence.",
  },
  {
    id: "aws-activate",
    name: "AWS Activate",
    owner: "Amazon Web Services",
    url: "https://aws.amazon.com/startups/credits",
    transport: "manual_snapshot",
    authority: "official_program",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["startup_credit", "partnership", "cost_reduction"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["eligibility", "benefit range", "covered services", "expiration", "application link", "terms link"],
    prohibitedCapture: ["automatic application", "claiming credits before approval", "credential capture"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Track self-funded and provider-sponsored eligibility separately; awarded and activated credits are different states.",
  },
  {
    id: "google-for-startups-cloud",
    name: "Google for Startups Cloud Program",
    owner: "Google Cloud",
    url: "https://cloud.google.com/startup",
    transport: "manual_snapshot",
    authority: "official_program",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["startup_credit", "partnership", "cost_reduction"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["eligibility", "credit tiers", "covered services", "restrictions", "application link"],
    prohibitedCapture: ["automatic application", "assuming third-party models are covered", "claiming credits before approval"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Separate general Google Cloud credits from any partner-model benefit.",
  },
  {
    id: "microsoft-for-startups",
    name: "Microsoft for Startups Founders Hub",
    owner: "Microsoft",
    url: "https://www.microsoft.com/en-us/startups",
    transport: "manual_snapshot",
    authority: "official_program",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["startup_credit", "partnership", "marketplace_channel", "cost_reduction"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["eligibility", "benefit tiers", "co-sell support", "marketplace requirements", "application link"],
    prohibitedCapture: ["automatic application", "claiming benefits before verification"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Track both direct founder benefits and investor-network/co-sell pathways.",
  },
  {
    id: "cloudflare-for-startups",
    name: "Cloudflare for Startups",
    owner: "Cloudflare",
    url: "https://www.cloudflare.com/startups/",
    transport: "manual_snapshot",
    authority: "official_program",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["startup_credit", "partnership", "cost_reduction"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["eligibility tier", "credit amount", "product caps", "duration", "application link"],
    prohibitedCapture: ["automatic application", "treating maximum awards as approved value"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Record bootstrapped and partner-backed tiers independently and preserve product-specific caps.",
  },
  {
    id: "nvidia-inception",
    name: "NVIDIA Inception",
    owner: "NVIDIA",
    url: "https://www.nvidia.com/en-us/startups/",
    transport: "manual_snapshot",
    authority: "official_program",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["startup_credit", "partnership", "grant_or_challenge", "developer_tool"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["eligibility", "program benefits", "training", "partner offers", "application link"],
    prohibitedCapture: ["automatic application", "claiming unspecified credits or cash"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Treat preferred pricing, technical support, and exposure as separate benefit types rather than cash.",
  },
  {
    id: "openai-apps-sdk",
    name: "OpenAI Apps SDK and App Distribution",
    owner: "OpenAI",
    url: "https://developers.openai.com/apps-sdk",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["app_product", "marketplace_channel", "partnership", "platform_update"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["submission requirements", "supported commerce model", "SDK changes", "review rules", "canonical links"],
    prohibitedCapture: ["assuming unsupported digital-goods monetization", "automatic submission"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Use as a distribution and product surface; monetization claims remain tied to current published rules.",
  },
  {
    id: "microsoft-commercial-marketplace",
    name: "Microsoft Commercial Marketplace AI Apps and Agents",
    owner: "Microsoft",
    url: "https://learn.microsoft.com/en-us/partner-center/marketplace-offers/",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["marketplace_channel", "app_product", "partnership"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["offer types", "fees", "transact models", "technical requirements", "co-sell requirements"],
    prohibitedCapture: ["automatic listing", "unsupported revenue projections"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Potential route for SaaS, AI apps, agents, metered billing, private offers, and co-sell.",
  },
  {
    id: "aws-marketplace-sellers",
    name: "AWS Marketplace Seller Guidance",
    owner: "Amazon Web Services",
    url: "https://docs.aws.amazon.com/marketplace/latest/userguide/user-guide-for-sellers.html",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["marketplace_channel", "app_product", "api_or_data_feed", "data_product", "partnership"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["seller requirements", "fees", "offer types", "API/SaaS/data requirements", "policy deadlines"],
    prohibitedCapture: ["automatic listing", "claiming qualification before approval"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Track SaaS, API, professional-service, private-offer, and data-exchange pathways separately.",
  },
  {
    id: "google-cloud-marketplace-partners",
    name: "Google Cloud Marketplace Partner Guidance",
    owner: "Google Cloud",
    url: "https://cloud.google.com/marketplace/docs/partners",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["marketplace_channel", "app_product", "data_product", "partnership"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["partner requirements", "offer types", "billing integration", "private offers", "policy changes"],
    prohibitedCapture: ["automatic listing", "claiming partner status before approval"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Potential distribution for SaaS, AI agents, data products, and professional services.",
  },
  {
    id: "snowflake-marketplace-providers",
    name: "Snowflake Marketplace Provider Guidance",
    owner: "Snowflake",
    url: "https://docs.snowflake.com/en/collaboration/provider-listings-about",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "vendor_terms_or_program_rules",
    classes: ["marketplace_channel", "data_product", "api_or_data_feed", "partnership"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["provider qualification", "listing models", "pricing support", "data rights requirements", "payout rules"],
    prohibitedCapture: ["listing data without ownership", "automatic listing", "claiming payouts before receipts"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Candidate channel for owned, rights-cleared derived sports intelligence and benchmarks.",
  },
  {
    id: "stripe-agentic-commerce",
    name: "Stripe Agentic Commerce",
    owner: "Stripe",
    url: "https://stripe.com/agentic-commerce",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["platform_update", "app_product", "marketplace_channel", "workflow_arbitrage", "partnership"],
    cadence: "weekly",
    rightsStatus: "public_metadata_only",
    allowedCapture: ["supported payment flows", "platform availability", "protocol changes", "fees", "partner announcements"],
    prohibitedCapture: ["automatic payment activation", "assuming unsupported digital product flows"],
    requiresTermsReview: true,
    enabledByDefault: true,
    notes: "Monitor agent-native checkout, platform enablement, and machine-payment capabilities.",
  },
  {
    id: "coinbase-x402",
    name: "x402 Agentic Payments",
    owner: "Coinbase Developer Platform",
    url: "https://docs.cdp.coinbase.com/x402/",
    transport: "html_changelog",
    authority: "official_vendor",
    evidenceTier: "official_primary",
    classes: ["platform_update", "api_or_data_feed", "workflow_arbitrage", "marketplace_channel"],
    cadence: "weekly",
    rightsStatus: "terms_review_required",
    allowedCapture: ["protocol version", "supported networks", "SDK changes", "fees", "discovery mechanisms"],
    prohibitedCapture: ["automatic wallet creation", "automatic payment", "token speculation", "custody of user funds"],
    requiresTermsReview: true,
    enabledByDefault: false,
    notes: "Experimental only. Crypto, tax, jurisdiction, security, and custody review precede any prototype.",
  },
];

export function getOpportunitySource(id: string): OpportunitySource | undefined {
  return DEFAULT_OPPORTUNITY_SOURCES.find((source) => source.id === id);
}

export function enabledOpportunitySources(): readonly OpportunitySource[] {
  return DEFAULT_OPPORTUNITY_SOURCES.filter((source) => source.enabledByDefault);
}

export function validateSourceRegistry(
  sources: readonly OpportunitySource[] = DEFAULT_OPPORTUNITY_SOURCES,
): readonly string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const source of sources) {
    if (ids.has(source.id)) errors.push(`Duplicate source id: ${source.id}`);
    ids.add(source.id);
    if (!source.url.startsWith("https://")) errors.push(`Source ${source.id} must use HTTPS.`);
    if (source.allowedCapture.length === 0) errors.push(`Source ${source.id} has no allowed-capture contract.`);
    if (source.prohibitedCapture.length === 0) errors.push(`Source ${source.id} has no prohibited-capture contract.`);
    if (source.classes.length === 0) errors.push(`Source ${source.id} has no opportunity classes.`);
  }
  return errors;
}
