/**
 * NFL Data Source Catalog — rights-classified index of every NFL data source
 * the owner has surfaced as a candidate (2026-06-12, 180 URLs).
 *
 * This is the candidate index. It complements SOURCE_RIGHTS_REGISTRY (the
 * canonical, full-schema record for sources we actually extract from). Every
 * URL here is accounted for with an honest rights status so nothing gets
 * ingested without clearance. Per CLAUDE.md legal posture:
 *
 *   - Only OPEN-LICENSED data, DOCUMENTED PUBLIC APIs, or sources that
 *     EXPLICITLY publish public fact downloads receive an "approved_*" status.
 *   - Everything proprietary defaults to permission_required (conservative),
 *     even when the underlying numbers are facts — terms review or written
 *     consent comes first.
 *   - Commercial providers with a known licensable feed/API are vendor_candidate.
 *
 * No status here authorizes evasion (no CAPTCHA/login/paywall bypass, no proxy
 * rotation). Approved-status sources still flow through checkClearance() and
 * carry a RightsSnapshot at extraction time.
 */

import type { SourceRightsStatus, SourceType } from "./source-rights-registry";

export type NflSourceCatalogEntry = {
  readonly id: string;
  readonly name: string;
  readonly url: string;
  readonly status: SourceRightsStatus;
  readonly source_type: SourceType;
  /** True when an adapter already ingests this source today. */
  readonly integrated: boolean;
  /** Canonical registry source_id this maps to, when one exists. */
  readonly registry_id: string | null;
  readonly rationale: string;
  /** Concrete legitimate route to actually USE this source's data ("figure out how to say YES"). */
  readonly path_to_yes: string;
};

const A_OPEN: SourceRightsStatus = "approved_open_license";
const A_PUB: SourceRightsStatus = "approved_public_logged_off";
const A_API: SourceRightsStatus = "approved_api";
const PERM: SourceRightsStatus = "permission_required";
const VENDOR: SourceRightsStatus = "vendor_candidate";

export const NFL_SOURCE_CATALOG: readonly NflSourceCatalogEntry[] = [
  // ── nflverse open-license ecosystem (CC-BY-SA 4.0 data; MIT/Apache tooling) ──
  { id: "nflverse-data-releases", name: "nflverse-data releases", url: "https://github.com/nflverse/nflverse-data/releases", status: A_OPEN, source_type: "open_dataset", integrated: true, registry_id: "nflverse", rationale: "Canonical open release index. CC-BY-SA 4.0; attribution + share-alike.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-pbp-release", name: "nflverse pbp", url: "https://github.com/nflverse/nflverse-data/releases/tag/pbp", status: A_OPEN, source_type: "open_dataset", integrated: true, registry_id: "nflverse", rationale: "Play-by-play. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-player-stats", name: "nflverse player_stats", url: "https://github.com/nflverse/nflverse-data/releases/tag/player_stats", status: A_OPEN, source_type: "open_dataset", integrated: true, registry_id: "nflverse", rationale: "Weekly player stats. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-stats-team", name: "nflverse stats_team", url: "https://github.com/nflverse/nflverse-data/releases/tag/stats_team", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Team stats. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-nextgen", name: "nflverse nextgen_stats", url: "https://github.com/nflverse/nflverse-data/releases/tag/nextgen_stats", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "NGS aggregates republished by nflverse under their open release; underlying NGS is NFL — use the nflverse mirror, attribute nflverse.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-pfr-adv", name: "nflverse pfr_advstats", url: "https://github.com/nflverse/nflverse-data/releases/tag/pfr_advstats", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "PFR advanced stats mirrored by nflverse; access via nflverse open release, carry upstream PFR attribution. Do NOT scrape PFR directly (see pro-football-reference).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-snap-counts", name: "nflverse snap_counts", url: "https://github.com/nflverse/nflverse-data/releases/tag/snap_counts", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Snap counts. Open release. Feeds Players Lab snap %.", path_to_yes: "INTEGRATE NOW — open nflverse snap_counts; powers Players Lab snap%." },
  { id: "nflverse-pbp-participation", name: "nflverse pbp_participation", url: "https://github.com/nflverse/nflverse-data/releases/tag/pbp_participation", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Participation/personnel. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-weekly-rosters", name: "nflverse weekly_rosters", url: "https://github.com/nflverse/nflverse-data/releases/tag/weekly_rosters", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Weekly rosters. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-depth-charts", name: "nflverse depth_charts", url: "https://github.com/nflverse/nflverse-data/releases/tag/depth_charts", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Depth charts. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-injuries", name: "nflverse injuries", url: "https://github.com/nflverse/nflverse-data/releases/tag/injuries", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Injury reports. Open release. Feeds injury signal (currently not implemented).", path_to_yes: "INTEGRATE NOW — open nflverse injuries; feeds the injury signal." },
  { id: "nflverse-officials", name: "nflverse officials", url: "https://github.com/nflverse/nflverse-data/releases/tag/officials", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Game officials. Open release. Feeds officials signal.", path_to_yes: "INTEGRATE NOW — open nflverse officials; feeds the officials signal." },
  { id: "nflverse-draft-picks", name: "nflverse draft_picks", url: "https://github.com/nflverse/nflverse-data/releases/tag/draft_picks", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Draft picks. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-combine", name: "nflverse combine", url: "https://github.com/nflverse/nflverse-data/releases/tag/combine", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Combine results. Open release.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-contracts", name: "nflverse contracts", url: "https://github.com/nflverse/nflverse-data/releases/tag/contracts", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Contracts mirrored from OverTheCap via nflverse open release; use the mirror, do NOT scrape OTC directly.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-ftn-charting", name: "nflverse ftn_charting", url: "https://github.com/nflverse/nflverse-data/releases/tag/ftn_charting", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "FTN charting subset shared open via nflverse; attribute FTN. The commercial FTN site is vendor_candidate.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-espn-data", name: "nflverse espn_data", url: "https://github.com/nflverse/nflverse-data/releases/tag/espn_data", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "ESPN-derived data mirrored by nflverse; use the mirror, attribute upstream.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflfastR", name: "nflfastR", url: "https://github.com/nflverse/nflfastR", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "R package, MIT. EPA/WP models. Methods + outputs usable with attribution.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflreadpy", name: "nflreadpy", url: "https://github.com/nflverse/nflreadpy", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Python loader, MIT.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflreadr", name: "nflreadr", url: "https://github.com/nflverse/nflreadr", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "R loader, MIT.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-pbp-repo", name: "nflverse-pbp", url: "https://github.com/nflverse/nflverse-pbp", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "PBP data repo. Open.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-rosters-repo", name: "nflverse-rosters", url: "https://github.com/nflverse/nflverse-rosters", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Rosters data repo. Open.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-ngs-data", name: "ngs-data", url: "https://github.com/nflverse/ngs-data", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "NGS aggregates repo packaged by nflverse. Open mirror.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-nfldata", name: "nfldata", url: "https://github.com/nflverse/nfldata", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Lee Sharpe misc datasets (schedules, standings, draft). Open.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nfl-data-py", name: "nfl_data_py", url: "https://github.com/nflverse/nfl_data_py", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Python loader (legacy), MIT. Superseded by nflreadpy.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "espnscraper-data", name: "espnscrapeR-data", url: "https://github.com/nflverse/espnscrapeR-data", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "ESPN QBR mirror in nflverse org; use mirror, attribute ESPN upstream.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflseedR", name: "nflseedR", url: "https://github.com/nflverse/nflseedR", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Playoff/seeding sim, MIT.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nfl4th-repo", name: "nfl4th", url: "https://github.com/nflverse/nfl4th", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "4th-down model, MIT.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "fastrmodels", name: "fastrmodels", url: "https://github.com/nflverse/fastrmodels", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Pretrained models for nflfastR, MIT.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflplotR", name: "nflplotR", url: "https://github.com/nflverse/nflplotR", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Plotting helpers (logos/wordmarks), MIT — note team logos are trademarks, do not republish marks.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-meta", name: "nflverse (meta)", url: "https://github.com/nflverse/nflverse", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Org meta-package. Open.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflscrapR", name: "nflscrapR (archived)", url: "https://github.com/maksimhorowitz/nflscrapR", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Archived predecessor to nflfastR, open license. Historical reference only.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflscrapR-data", name: "nflscrapR-data (archived)", url: "https://github.com/ryurko/nflscrapR-data", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: null, rationale: "Archived 2009-2019 data, open. Superseded by nflfastR pbp.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflscrapR-models", name: "nflscrapR-models (archived)", url: "https://github.com/ryurko/nflscrapR-models", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Archived models, open. Historical.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "opensourcefootball", name: "Open Source Football", url: "https://opensourcefootball.com/", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Community methods blog (MIT repo). Use methods/code; article prose is authored content — do not republish bodies.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-trades", name: "nflverse trades", url: "https://github.com/nflverse/nflverse-data/releases/tag/trades", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Trade transactions. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-teams", name: "nflverse teams", url: "https://github.com/nflverse/nflverse-data/releases/tag/teams", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Team metadata/identifiers. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-schedules", name: "nflverse schedules", url: "https://github.com/nflverse/nflverse-data/releases/tag/schedules", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Schedules and game results. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-stats-player", name: "nflverse stats_player", url: "https://github.com/nflverse/nflverse-data/releases/tag/stats_player", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Player stats (current-schema release). Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-players", name: "nflverse players", url: "https://github.com/nflverse/nflverse-data/releases/tag/players", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Canonical player IDs/bios. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-players-components", name: "nflverse players_components", url: "https://github.com/nflverse/nflverse-data/releases/tag/players_components", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Player ID component tables. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-rosters", name: "nflverse rosters", url: "https://github.com/nflverse/nflverse-data/releases/tag/rosters", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Season rosters. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "nflverse-misc", name: "nflverse misc", url: "https://github.com/nflverse/nflverse-data/releases/tag/misc", status: A_OPEN, source_type: "open_dataset", integrated: false, registry_id: "nflverse", rationale: "Miscellaneous datasets. Open nflverse release (CC-BY-SA 4.0).", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },

  // ── Free public fact sites (no login; facts derivable / explicit downloads) ──
  { id: "nflfastr-site", name: "nflfastR docs", url: "https://www.nflfastr.com/", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: "nflverse", rationale: "Docs site for the open package.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },
  { id: "rbsdm-stats", name: "rbsdm.com stats", url: "https://rbsdm.com/", status: A_PUB, source_type: "other", integrated: false, registry_id: null, rationale: "Ben Baldwin free public dashboard built on nflfastR (open) data; prefer regenerating from nflfastR directly. Facts only, no login.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "rbsdm-box-scores", name: "rbsdm box scores", url: "https://rbsdm.com/stats/box_scores/", status: A_PUB, source_type: "other", integrated: false, registry_id: null, rationale: "Free public box-score view over open data. Facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "nflsavant", name: "NFL Savant", url: "https://nflsavant.com/", status: A_PUB, source_type: "open_dataset", integrated: false, registry_id: null, rationale: "Publishes free public CSV downloads (pbp, weather) with no login. Facts only; attribute the source.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "nfl4th-site", name: "nfl4th.com", url: "https://www.nfl4th.com/", status: A_OPEN, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Site for the open nfl4th model.", path_to_yes: "INTEGRATE NOW — fetch the open release/package directly via nflverse; attribute CC-BY-SA 4.0." },

  // ── ESPN public JSON APIs (undocumented, no auth, facts) — already used ──
  { id: "espn-scoreboard", name: "ESPN scoreboard API", url: "https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard", status: A_PUB, source_type: "sports_data_api", integrated: true, registry_id: "espn-public-api", rationale: "Undocumented public JSON, no auth. Facts (scores/schedule). Already an ingestion fallback. Polite rate, facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "espn-teams", name: "ESPN teams API", url: "https://site.api.espn.com/apis/site/v2/sports/football/nfl/teams", status: A_PUB, source_type: "sports_data_api", integrated: true, registry_id: "espn-public-api", rationale: "Public JSON team metadata. Facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "espn-leaders", name: "ESPN leaders API", url: "https://site.web.api.espn.com/apis/site/v3/sports/football/nfl/leaders", status: A_PUB, source_type: "sports_data_api", integrated: false, registry_id: "espn-public-api", rationale: "Public JSON stat leaders. Facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "espn-teamleaders", name: "ESPN team leaders API", url: "https://site.web.api.espn.com/apis/site/v3/sports/football/nfl/teamleaders", status: A_PUB, source_type: "sports_data_api", integrated: false, registry_id: "espn-public-api", rationale: "Public JSON team leaders. Facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "espn-core-events", name: "ESPN core events API", url: "https://sports.core.api.espn.com/v2/sports/football/leagues/nfl/events", status: A_PUB, source_type: "sports_data_api", integrated: false, registry_id: "espn-public-api", rationale: "Public JSON events feed. Facts only.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "nntrn-espn-api-gist", name: "nntrn ESPN API gist", url: "https://gist.github.com/nntrn/ee26cb2a0716de0947a0a4e9a157bc1c", status: A_PUB, source_type: "sports_data_api", integrated: false, registry_id: "espn-public-api", rationale: "Community documentation of ESPN's public JSON API; same facts-only public-API posture as our espn-public-api source.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },
  { id: "pseudo-r-public-espn-api", name: "pseudo-r Public-ESPN-API", url: "https://github.com/pseudo-r/Public-ESPN-API", status: A_PUB, source_type: "sports_data_api", integrated: false, registry_id: "espn-public-api", rationale: "Community documentation of ESPN's public JSON API; same facts-only public-API posture as our espn-public-api source.", path_to_yes: "INTEGRATE NOW — consume the public endpoint/download, facts only, polite rate; no auth/anti-bot bypass." },

  // ── Sleeper documented public API — already used (fantasy) ──
  { id: "sleeper-docs", name: "Sleeper API docs", url: "https://docs.sleeper.com/", status: A_API, source_type: "fantasy_platform", integrated: true, registry_id: "sleeper-api", rationale: "Documented free public read-only API, no auth for reads. Rate-limited (<1000/min). Already integrated.", path_to_yes: "INTEGRATE NOW — use the documented Sleeper API within published rate limits." },
  { id: "sleeper-players", name: "Sleeper players", url: "https://api.sleeper.app/v1/players/nfl", status: A_API, source_type: "fantasy_platform", integrated: true, registry_id: "sleeper-api", rationale: "Public read endpoint. Cache per docs (call once/day).", path_to_yes: "INTEGRATE NOW — use the documented Sleeper API within published rate limits." },
  { id: "sleeper-state", name: "Sleeper NFL state", url: "https://api.sleeper.app/v1/state/nfl", status: A_API, source_type: "fantasy_platform", integrated: true, registry_id: "sleeper-api", rationale: "Public read endpoint (week/season state).", path_to_yes: "INTEGRATE NOW — use the documented Sleeper API within published rate limits." },
  { id: "sleeper-trending-add", name: "Sleeper trending add", url: "https://api.sleeper.app/v1/players/nfl/trending/add", status: A_API, source_type: "fantasy_platform", integrated: false, registry_id: "sleeper-api", rationale: "Public read endpoint (waiver trends).", path_to_yes: "INTEGRATE NOW — use the documented Sleeper API within published rate limits." },
  { id: "sleeper-trending-drop", name: "Sleeper trending drop", url: "https://api.sleeper.app/v1/players/nfl/trending/drop", status: A_API, source_type: "fantasy_platform", integrated: false, registry_id: "sleeper-api", rationale: "Public read endpoint (drop trends).", path_to_yes: "INTEGRATE NOW — use the documented Sleeper API within published rate limits." },

  // ── NFL official proprietary (NGS, NFL.com) — license required ──
  { id: "ngs-site", name: "Next Gen Stats", url: "https://nextgenstats.nfl.com/", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "NFL's proprietary tracking product. No automation without NFL license. Use nflverse nextgen_stats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },
  { id: "ngs-passing", name: "NGS passing", url: "https://nextgenstats.nfl.com/stats/passing", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Mirror available via nflverse.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },
  { id: "ngs-rushing", name: "NGS rushing", url: "https://nextgenstats.nfl.com/stats/rushing", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Mirror via nflverse.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },
  { id: "ngs-receiving", name: "NGS receiving", url: "https://nextgenstats.nfl.com/stats/receiving", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Mirror via nflverse.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },
  { id: "ngs-defense", name: "NGS defense", url: "https://nextgenstats.nfl.com/stats/defense", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Mirror via nflverse.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },
  { id: "nfl-stats", name: "NFL.com stats", url: "https://www.nfl.com/stats/", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Official NFL content, proprietary. License required.", path_to_yes: "USE THE OPEN MIRROR — nflverse player_stats / stats_team." },
  { id: "nfl-player-stats", name: "NFL.com player stats", url: "https://www.nfl.com/stats/player-stats/", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Use nflverse player_stats.", path_to_yes: "USE THE OPEN MIRROR — nflverse player_stats / stats_team." },
  { id: "nfl-team-stats", name: "NFL.com team stats", url: "https://www.nfl.com/stats/team-stats/", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Proprietary NFL. Use nflverse stats_team.", path_to_yes: "USE THE OPEN MIRROR — nflverse player_stats / stats_team." },
  { id: "nfl-ops-bdb", name: "NFL Ops Big Data Bowl", url: "https://operations.nfl.com/gameday/analytics/big-data-bowl/", status: PERM, source_type: "official_league_site", integrated: false, registry_id: null, rationale: "Info page; competition tracking data is NFL-owned, distributed via Kaggle under competition rules.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },

  // ── ESPN proprietary web/analytics (distinct from the public JSON APIs) ──
  { id: "espn-analytics-rec", name: "ESPN Analytics receivers", url: "https://espnanalytics.com/receivers", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "ESPN proprietary analytics (open-score etc). License required; not the public API.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },
  { id: "espn-analytics-decision", name: "ESPN Analytics decision", url: "https://www.espnanalytics.com/decision/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "ESPN proprietary analytics. License required.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },
  { id: "espn-web-stats", name: "ESPN.com NFL stats", url: "https://www.espn.com/nfl/stats", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "ESPN web pages, proprietary. Use the public JSON API for facts instead of scraping HTML.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },
  { id: "espn-web-qbr", name: "ESPN.com QBR", url: "https://www.espn.com/nfl/qbr", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "QBR is ESPN proprietary. Mirror via nflverse espnscrapeR-data.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },
  { id: "espn-web-team", name: "ESPN.com team stats", url: "https://www.espn.com/nfl/team/stats", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "Proprietary web pages. Prefer public API.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },
  { id: "espn-web-injuries", name: "ESPN.com injuries", url: "https://www.espn.com/nfl/injuries", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "Proprietary web pages. Use nflverse injuries for facts.", path_to_yes: "USE THE OPEN MIRROR — ESPN public JSON API + nflverse espn_data/espnscrapeR-data." },

  // ── Kaggle / Big Data Bowl (NFL-owned tracking, competition rules) ──
  { id: "bdb-2026", name: "Big Data Bowl 2026", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2026", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "NFL-owned player-tracking data under Kaggle competition rules; commercial use needs NFL permission.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2025", name: "Big Data Bowl 2025", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2025", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking. Permission for commercial.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2024", name: "Big Data Bowl 2024", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2024", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2023", name: "Big Data Bowl 2023", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2023", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2022", name: "Big Data Bowl 2022", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2022", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2021", name: "Big Data Bowl 2021", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2021", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "bdb-2020", name: "Big Data Bowl 2020", url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2020", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned tracking.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "kaggle-punt", name: "NFL Punt Analytics", url: "https://www.kaggle.com/competitions/NFL-Punt-Analytics-Competition", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned data.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "kaggle-impact", name: "NFL Impact Detection", url: "https://www.kaggle.com/competitions/nfl-impact-detection", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Competition rules; NFL-owned video/data.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "nfl-ops-bdb-repo", name: "NFL Ops BDB repo", url: "https://github.com/nfl-football-ops/Big-Data-Bowl", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "NFL Football Ops repo; data subject to competition terms.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "nfl-ops-bdb-data", name: "NFL Ops BDB data", url: "https://github.com/nfl-football-ops/Big-Data-Bowl/tree/master/Data", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "NFL-owned tracking sample; competition terms.", path_to_yes: "R&D ONLY under competition terms; REQUEST NFL PERMISSION for any commercial use of the tracking data." },
  { id: "ngs-highlights", name: "ngs_highlights", url: "https://github.com/asonty/ngs_highlights", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Personal repo pulling NGS data; no clear OSI license + NGS-derived. Permission required before reuse.", path_to_yes: "USE THE OPEN MIRROR — nflverse nextgen_stats." },

  // ── StatsBomb open data (free for research; commercial needs agreement) ──
  { id: "statsbomb-amf", name: "StatsBomb amf-open-data", url: "https://github.com/statsbomb/amf-open-data", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "StatsBomb open data is free for research/education with attribution; commercial use (this is a paid product) requires a written StatsBomb agreement.", path_to_yes: "SIGN a StatsBomb commercial agreement; the free tier is non-commercial only." },
  { id: "statsbomb-amf-data", name: "StatsBomb amf-open-data data", url: "https://github.com/statsbomb/amf-open-data/tree/main/data", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Same StatsBomb non-commercial license; commercial use needs agreement.", path_to_yes: "SIGN a StatsBomb commercial agreement; the free tier is non-commercial only." },

  // ── Community scraper tool repos — tool license does NOT clear the target ──
  { id: "marclindergit-nfl-stats", name: "MarcLinderGit/NFL_Stats", url: "https://github.com/MarcLinderGit/NFL_Stats", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "nflscrapy", name: "blnkpagelabs/nflscraPy", url: "https://github.com/blnkpagelabs/nflscraPy", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "coleballard-nfl-data-scraper", name: "ColeBallard/nfl-data-scraper", url: "https://github.com/ColeBallard/nfl-data-scraper", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "ewelchman-scrape-pfr", name: "ewelchman/scrape_pfr", url: "https://github.com/ewelchman/scrape_pfr", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "code-jl-kicker-scraper", name: "Code-JL/NFL-Point-Kicker-Data-Scraper", url: "https://github.com/Code-JL/NFL-Point-Kicker-Data-Scraper", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "zackthoutt-nfl-player-stats", name: "zackthoutt/nfl-player-stats", url: "https://github.com/zackthoutt/nfl-player-stats", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },
  { id: "hvpkod-nfl-data", name: "hvpkod/NFL-Data", url: "https://github.com/hvpkod/NFL-Data", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Community data repo of mixed provenance/unclear license; permission/provenance review required before reuse.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "opendoug-nfl-score-scraper", name: "opendoug/nfl-score-scraper", url: "https://github.com/opendoug/nfl-score-scraper", status: PERM, source_type: "research_repo", integrated: false, registry_id: null, rationale: "Open-source scraper TOOL, but it extracts from a rights-gated target (e.g. PFR/ESPN); the TARGET's status governs — must not be used to launder a gated source's ToS.", path_to_yes: "DO NOT use to launder a gated target; obtain rights to the underlying target (PFR/ESPN) directly, or use the nflverse mirror." },

  // ── pro-football-reference (Sports Reference) — ToS prohibits scraping ──
  { id: "pro-football-reference", name: "Pro Football Reference", url: "https://www.pro-football-reference.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping/bots. Data licensing via Sports Reference LLC. Use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-advanced", name: "PFR advanced stats", url: "https://www.pro-football-reference.com/years/2025/advanced.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Same PFR ToS. Use nflverse pfr_advstats.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-passing-advanced", name: "PFR advanced passing", url: "https://www.pro-football-reference.com/years/2025/passing_advanced.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-rushing-advanced", name: "PFR advanced rushing", url: "https://www.pro-football-reference.com/years/2025/rushing_advanced.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-receiving-advanced", name: "PFR advanced receiving", url: "https://www.pro-football-reference.com/years/2025/receiving_advanced.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-defense-advanced", name: "PFR advanced defense", url: "https://www.pro-football-reference.com/years/2025/defense_advanced.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-redzone-passing", name: "PFR red zone passing", url: "https://www.pro-football-reference.com/years/2025/redzone-passing.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-redzone-rushing", name: "PFR red zone rushing", url: "https://www.pro-football-reference.com/years/2025/redzone-rushing.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-redzone-receiving", name: "PFR red zone receiving", url: "https://www.pro-football-reference.com/years/2025/redzone-receiving.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-opp", name: "PFR opponent stats", url: "https://www.pro-football-reference.com/years/2025/opp.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-splits", name: "PFR splits", url: "https://www.pro-football-reference.com/years/2025/splits.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-leaders", name: "PFR leaders", url: "https://www.pro-football-reference.com/years/2025/leaders.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-passing", name: "PFR passing", url: "https://www.pro-football-reference.com/years/2025/passing.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-rushing", name: "PFR rushing", url: "https://www.pro-football-reference.com/years/2025/rushing.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-receiving", name: "PFR receiving", url: "https://www.pro-football-reference.com/years/2025/receiving.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-defense", name: "PFR defense", url: "https://www.pro-football-reference.com/years/2025/defense.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-kicking", name: "PFR kicking", url: "https://www.pro-football-reference.com/years/2025/kicking.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },
  { id: "pfr-returns", name: "PFR returns", url: "https://www.pro-football-reference.com/years/2025/returns.htm", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Sports Reference ToS prohibits automated scraping; use nflverse pfr_advstats mirror for facts.", path_to_yes: "USE THE OPEN MIRROR — nflverse pfr_advstats; never scrape PFR (ToS)." },

  // ── Commercial analytics/stat providers — vendor or permission ──
  { id: "teamrankings-stats", name: "TeamRankings stats", url: "https://www.teamrankings.com/nfl/stats/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial stats product; ToS restricts automated use. Has paid data offering.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "teamrankings-ypp", name: "TeamRankings YPP", url: "https://www.teamrankings.com/nfl/stat/yards-per-play", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial; permission required. Derivable from nflverse pbp.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "sharpfootball-pace", name: "Sharp Football pace", url: "https://www.sharpfootballanalysis.com/stats-nfl/nfl-team-pace-stats/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial analytics site. Pace derivable from nflverse pbp.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "sumersports-qb", name: "SumerSports QB", url: "https://sumersports.com/players/quarterback/", status: VENDOR, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial analytics (Sumer) with proprietary models — candidate for a licensed feed.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "sumersports-rb", name: "SumerSports RB", url: "https://sumersports.com/players/running-back/", status: VENDOR, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial analytics — vendor candidate.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "sumersports-wr", name: "SumerSports WR", url: "https://sumersports.com/players/wide-receiver/", status: VENDOR, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial analytics — vendor candidate.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "sumersports-te", name: "SumerSports TE", url: "https://sumersports.com/players/tight-end/", status: VENDOR, source_type: "other", integrated: false, registry_id: null, rationale: "Commercial analytics — vendor candidate.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "fantasypros-qb", name: "FantasyPros advanced QB", url: "https://www.fantasypros.com/nfl/advanced-stats-qb.php", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FantasyPros offers a commercial API/license; pursue that rather than scraping.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "fantasypros-wr", name: "FantasyPros advanced WR", url: "https://www.fantasypros.com/nfl/advanced-stats-wr.php", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FantasyPros — licensed API candidate.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "fantasypros-rz", name: "FantasyPros red zone WR", url: "https://www.fantasypros.com/nfl/red-zone-stats/wr.php", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FantasyPros — licensed API candidate.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "fantasypros-snaps", name: "FantasyPros snap counts", url: "https://www.fantasypros.com/nfl/reports/snap-counts/", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FantasyPros — licensed API candidate. Snaps also via nflverse snap_counts (open).", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "playerprofiler", name: "PlayerProfiler", url: "https://www.playerprofiler.com/", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Proprietary advanced metrics; ToS restricts automation. Permission required.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "overthecap", name: "OverTheCap", url: "https://overthecap.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary contract/cap data. Use nflverse contracts mirror; do not scrape OTC directly.", path_to_yes: "USE THE OPEN MIRROR — nflverse contracts." },
  { id: "spotrac-cap", name: "Spotrac NFL cap", url: "https://www.spotrac.com/nfl/cap", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary contract data; licensing available. Permission required.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "ourlads-depth", name: "Ourlads depth charts", url: "https://www.ourlads.com/nfldepthcharts/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary depth charts. Use nflverse depth_charts for facts.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "ras-football", name: "RAS (ras.football)", url: "https://ras.football/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Kent Lee Platte's RAS metric — creator-owned. Ask permission; attribute creator.", path_to_yes: "DERIVE FROM OPEN DATA where reconstructable from nflverse combine; OTHERWISE request Kent Lee Platte's written permission and attribute the creator." },
  { id: "mockdraftable", name: "MockDraftable", url: "https://www.mockdraftable.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary combine percentiles (largely inactive). Permission required.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "nflpenalties", name: "NFLPenalties.com", url: "https://www.nflpenalties.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Free hobby site of penalty facts; ToS unstated — conservative permission_required pending review. Penalty facts also in nflverse pbp.", path_to_yes: "DERIVE FROM OPEN DATA — penalty facts from nflverse pbp; OTHERWISE request written permission and credit the site creator." },
  { id: "nflweather", name: "NFL Weather", url: "https://nflweather.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary aggregator; ToS restricts. Underlying weather is public via NWS (public domain) / licensed weather APIs — prefer those.", path_to_yes: "USE A LICENSED/PUBLIC WEATHER SOURCE — NWS (public domain) or a licensed weather API; do not scrape the aggregator." },
  { id: "draftscout", name: "DraftScout", url: "https://draftscout.com/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary scouting database. Permission required.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },

  // ── Broadcast/portal stat pages — proprietary ──
  { id: "yahoo-stats", name: "Yahoo NFL stats", url: "https://sports.yahoo.com/nfl/stats/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "Yahoo proprietary; ToS restricts scraping.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "yahoo-team", name: "Yahoo team stats", url: "https://sports.yahoo.com/nfl/stats/team/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "Yahoo proprietary.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "yahoo-weekly", name: "Yahoo weekly stats", url: "https://sports.yahoo.com/nfl/stats/weekly/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "Yahoo proprietary.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "cbs-stats", name: "CBS Sports stats", url: "https://www.cbssports.com/nfl/stats/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "CBS proprietary; ToS restricts scraping.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "cbs-team", name: "CBS Sports team stats", url: "https://www.cbssports.com/nfl/stats/team/", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "CBS proprietary.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "fox-stats", name: "FOX Sports stats", url: "https://www.foxsports.com/nfl/stats", status: PERM, source_type: "broadcast_media", integrated: false, registry_id: null, rationale: "FOX proprietary; ToS restricts scraping.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "footballdb-stats", name: "FootballDB stats", url: "https://www.footballdb.com/stats/index.html", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary stats site; ToS restricts. Facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-team", name: "FootballDB team stats", url: "https://www.footballdb.com/stats/teamstat.html", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary. Use nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-players", name: "FootballDB players", url: "https://www.footballdb.com/players/index.html", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary. Use nflverse rosters.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-penalties", name: "FootballDB penalties", url: "https://www.footballdb.com/statistics/penalties.html", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-passing", name: "FootballDB player passing", url: "https://www.footballdb.com/statistics/nfl/player-stats/passing", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-rushing", name: "FootballDB player rushing", url: "https://www.footballdb.com/statistics/nfl/player-stats/rushing", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-receiving", name: "FootballDB player receiving", url: "https://www.footballdb.com/statistics/nfl/player-stats/receiving", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-offense-totals", name: "FootballDB offense totals", url: "https://www.footballdb.com/statistics/nfl/team-stats/offense-totals", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-defense-totals", name: "FootballDB defense totals", url: "https://www.footballdb.com/statistics/nfl/team-stats/defense-totals", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-offense-passing", name: "FootballDB offense passing", url: "https://www.footballdb.com/statistics/nfl/team-stats/offense-passing", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-offense-rushing", name: "FootballDB offense rushing", url: "https://www.footballdb.com/statistics/nfl/team-stats/offense-rushing", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-offense-scoring", name: "FootballDB offense scoring", url: "https://www.footballdb.com/statistics/nfl/team-stats/offense-scoring", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-weekly-leaders", name: "FootballDB weekly leaders", url: "https://www.footballdb.com/statistics/weekly-leaders.html", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-player-splits", name: "FootballDB player splits", url: "https://www.footballdb.com/statistics/nfl/player-splits", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "footballdb-offense-punting", name: "FootballDB offense punting", url: "https://www.footballdb.com/statistics/nfl/team-stats/offense-punting/2025/regular-season", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts automation; facts derivable from nflverse.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct from nflverse player_stats/stats_team/pbp; else request permission." },
  { id: "statmuse", name: "StatMuse NFL", url: "https://www.statmuse.com/nfl", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary NL stats search; ToS restricts automation.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },

  // ── Fantasy/snap aggregators — vendor or permission ──
  { id: "ftnfantasy-airyards", name: "FTN air yards", url: "https://ftnfantasy.com/nfl/air-yards", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FTN commercial; an open charting subset is in nflverse ftn_charting. License the rest.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "ftnfantasy-snaps", name: "FTN snaps", url: "https://ftnfantasy.com/nfl/snaps", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "FTN commercial. Snaps also via nflverse snap_counts (open).", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "footballguys-snaps", name: "Footballguys snap counts", url: "https://www.footballguys.com/stats/snap-counts/teams", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Subscription product; permission required. Use nflverse snap_counts.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "footballguys-targets", name: "Footballguys targets", url: "https://www.footballguys.com/stats/targets/teams", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Subscription product. Targets via nflverse pbp.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "footballguys-redzone", name: "Footballguys red zone", url: "https://www.footballguys.com/stats/redzone/teams", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Subscription product. Red-zone via nflverse pbp.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "fantasyalarm-snaps", name: "Fantasy Alarm snap counts", url: "https://www.fantasyalarm.com/nfl/snap-counts", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Subscription product; permission required. Use nflverse snap_counts.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "lineups-snaps", name: "Lineups snap counts", url: "https://www.lineups.com/nfl/snap-counts", status: PERM, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "Proprietary; ToS restricts. Use nflverse snap_counts.", path_to_yes: "DERIVE FROM OPEN DATA where the stat is reconstructable from nflverse pbp/rosters; OTHERWISE request written permission / licensing." },
  { id: "rotowire-stats", name: "RotoWire player stats", url: "https://www.rotowire.com/football/player-stats.php", status: VENDOR, source_type: "fantasy_platform", integrated: false, registry_id: null, rationale: "RotoWire licenses commercial data feeds — pursue a license rather than scraping.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },
  { id: "theanalyst-zone", name: "The Analyst (Opta) zone", url: "https://theanalyst.com/articles/nfl-advanced-stats-zone", status: VENDOR, source_type: "other", integrated: false, registry_id: null, rationale: "Opta / Stats Perform premium data — licensable enterprise feed. Article prose is authored content; do not republish bodies.", path_to_yes: "LICENSE — request the vendor's commercial API/feed terms; INTERIM: derive the equivalent from nflverse open data where the metric is reconstructable." },

  // ── StatRankings advanced stats — proprietary commercial product ──
  { id: "statrankings-players", name: "StatRankings players", url: "https://www.statrankings.com/nfl/advanced/players", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-usage", name: "StatRankings usage", url: "https://www.statrankings.com/nfl/advanced/players/usage", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-snap-rate", name: "StatRankings snap rate", url: "https://www.statrankings.com/nfl/advanced/players/usage/snap-rate", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-opportunity-share", name: "StatRankings opportunity share", url: "https://www.statrankings.com/nfl/advanced/players/usage/opportunity-share", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-route-participation", name: "StatRankings route participation", url: "https://www.statrankings.com/nfl/advanced/players/usage/route-participation", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-first-read-target-share", name: "StatRankings first-read target share", url: "https://www.statrankings.com/nfl/advanced/players/usage/first-read-target-share", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-targets-per-route-run", name: "StatRankings targets per route run", url: "https://www.statrankings.com/nfl/advanced/players/usage/targets-per-route-run", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-routes-run", name: "StatRankings routes run", url: "https://www.statrankings.com/nfl/advanced/players/usage/routes-run", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-total-opportunities", name: "StatRankings total opportunities", url: "https://www.statrankings.com/nfl/advanced/players/usage/total-opportunities", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-air-yards-percentage", name: "StatRankings air yards percentage", url: "https://www.statrankings.com/nfl/advanced/players/receiving/air-yards-percentage", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-air-yards-per-route-run", name: "StatRankings air yards per route run", url: "https://www.statrankings.com/nfl/advanced/players/receiving/air-yards-per-route-run", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-teams", name: "StatRankings teams", url: "https://www.statrankings.com/nfl/advanced/teams", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-teams-epa", name: "StatRankings teams EPA", url: "https://www.statrankings.com/nfl/advanced/teams/epa/", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
  { id: "statrankings-zone-coverage-rate", name: "StatRankings zone coverage rate", url: "https://www.statrankings.com/nfl/advanced/teams/coverage/zone-coverage-rate", status: PERM, source_type: "other", integrated: false, registry_id: null, rationale: "Proprietary commercial advanced-stats product; ToS restricts automation; usage/route metrics partly derivable from nflverse + ftn_charting.", path_to_yes: "DERIVE FROM OPEN DATA — reconstruct usage/route/air-yards from nflverse pbp + ftn_charting; else license." },
];

/** Sources cleared for automated extraction today (still gated by checkClearance). */
export const AUTOMATABLE_STATUSES: readonly SourceRightsStatus[] = [
  "approved_open_license",
  "approved_public_logged_off",
  "approved_api",
  "approved_written_permission",
];

export function isAutomatable(entry: NflSourceCatalogEntry): boolean {
  return AUTOMATABLE_STATUSES.includes(entry.status);
}

export function catalogByStatus(
  status: SourceRightsStatus,
): readonly NflSourceCatalogEntry[] {
  return NFL_SOURCE_CATALOG.filter((e) => e.status === status);
}
