#!/usr/bin/env bash
# Cloud Agent start step — per-boot service reconciliation.
#
# Boots a local PostgreSQL + Redis (as the non-root `node` user), creates the
# app database, pushes the Prisma schema, seeds sports/leagues + cockpit demo
# data + a dev admin, and writes a gitignored apps/web/.env.local pointing the
# app at the local database. Idempotent and restart-tolerant: every step is
# guarded so a warm restart is a no-op and returns quickly.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo /workspace)"
cd "$ROOT"

PGDATA="$HOME/.gse-pgdata"
PGPORT=5433
DBNAME=sports_platform
DBUSER=sports
DBPASS=sports_dev_password
DBURL="postgresql://${DBUSER}:${DBPASS}@127.0.0.1:${PGPORT}/${DBNAME}?schema=public"

# --- PostgreSQL -----------------------------------------------------------
if [ ! -s "$PGDATA/PG_VERSION" ]; then
  echo "[start] initializing Postgres data dir at $PGDATA"
  rm -rf "$PGDATA"; mkdir -p "$PGDATA"
  initdb -D "$PGDATA" -U postgres --auth-local=trust --auth-host=trust >/tmp/gse-initdb.log 2>&1
fi

if ! pg_isready -q -h 127.0.0.1 -p "$PGPORT"; then
  echo "[start] starting Postgres on port $PGPORT"
  pg_ctl -D "$PGDATA" \
    -o "-p ${PGPORT} -k /tmp -c listen_addresses=127.0.0.1" \
    -l /tmp/gse-pg.log -w start
fi
pg_isready -q -h 127.0.0.1 -p "$PGPORT"

# Role + database (idempotent).
if ! psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
    "SELECT 1 FROM pg_roles WHERE rolname='${DBUSER}'" | grep -q 1; then
  echo "[start] creating role ${DBUSER}"
  psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -c \
    "CREATE ROLE ${DBUSER} LOGIN PASSWORD '${DBPASS}' SUPERUSER"
fi
if ! psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
    "SELECT 1 FROM pg_database WHERE datname='${DBNAME}'" | grep -q 1; then
  echo "[start] creating database ${DBNAME}"
  createdb -h 127.0.0.1 -p "$PGPORT" -U postgres -O "${DBUSER}" "${DBNAME}"
fi

# --- Redis (optional; only used by the Claude response cache) -------------
if ! redis-cli -p 6379 ping >/dev/null 2>&1; then
  echo "[start] starting Redis on port 6379"
  redis-server --daemonize yes --port 6379 --dir /tmp --save "" >/tmp/gse-redis.log 2>&1 || \
    echo "[start] WARN: redis failed to start (non-fatal — cache is optional)"
fi

# --- App env file (gitignored; never committed) ---------------------------
ENVFILE="$ROOT/apps/web/.env.local"
if [ ! -f "$ENVFILE" ]; then
  echo "[start] writing apps/web/.env.local (local dev, real Postgres)"
  SECRET="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")"
  cat > "$ENVFILE" <<EOF
# Auto-generated by .cursor/start.sh for Cloud Agent local dev. Gitignored.
DATABASE_URL=${DBURL}
DIRECT_URL=${DBURL}
FORCE_REAL_PRISMA=true
NEXTAUTH_SECRET=${SECRET}
NEXTAUTH_URL=http://localhost:3000
DEV_FAKE_ADMIN=true
NODE_ENV=development
PUBLIC_PICKS_ENABLED=true
DEMO_PICKS_ENABLED=true
REDIS_URL=redis://127.0.0.1:6379
EOF
fi

# --- Schema + seed (idempotent) -------------------------------------------
export DATABASE_URL="$DBURL" DIRECT_URL="$DBURL"
echo "[start] pushing Prisma schema..."
npm run db:push --workspace=packages/db
echo "[start] seeding (sports/leagues + cockpit demo + dev admin; idempotent)..."
npm run db:seed --workspace=packages/db || echo "[start] WARN: seed reported an issue (non-fatal)"

echo "[start] ready. Postgres :$PGPORT db=$DBNAME, Redis :6379. Run 'npm run dev' or use the 'web' terminal."
