#!/usr/bin/env bash
# Cloud Agent start step — per-boot service reconciliation.
#
# Adaptive by base image:
#   * If the image provides PostgreSQL (the .cursor/Dockerfile base), boot a
#     local Postgres + Redis as the non-root user, create the app database,
#     `prisma db push`, seed (sports/leagues + cockpit demo + dev admin), and
#     point apps/web/.env.local at the real local DB.
#   * Otherwise fall back to the repo's documented stub-DB dev mode
#     (QUICKSTART.md Path B): DATABASE_URL=stub + DEMO_PICKS_ENABLED so the app
#     still boots and renders realistic sample data with no database.
#
# Idempotent and restart-tolerant: a warm restart is a near no-op that returns
# quickly. Writes a gitignored apps/web/.env.local; never commits secrets.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo /workspace)"
cd "$ROOT"

ENVFILE="$ROOT/apps/web/.env.local"
PGPORT=5433
DBNAME=sports_platform
DBUSER=sports
DBPASS=sports_dev_password
DBURL="postgresql://${DBUSER}:${DBPASS}@127.0.0.1:${PGPORT}/${DBNAME}?schema=public"

secret() { node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"; }

if command -v initdb >/dev/null 2>&1; then
  # ---------------------------------------------------------------- real DB --
  echo "[start] Postgres available — booting the full local stack."
  PGDATA="$HOME/.gse-pgdata"

  if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "[start] initializing Postgres data dir at $PGDATA"
    rm -rf "$PGDATA"; mkdir -p "$PGDATA"
    initdb -D "$PGDATA" -U postgres --auth-local=trust --auth-host=trust >/tmp/gse-initdb.log 2>&1
  fi
  if ! pg_isready -q -h 127.0.0.1 -p "$PGPORT"; then
    echo "[start] starting Postgres on port $PGPORT"
    pg_ctl -D "$PGDATA" \
      -o "-p ${PGPORT} -k /tmp -c listen_addresses=127.0.0.1" \
      -l /tmp/gse-pg.log -w start
  fi
  pg_isready -q -h 127.0.0.1 -p "$PGPORT"

  if ! psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
      "SELECT 1 FROM pg_roles WHERE rolname='${DBUSER}'" | grep -q 1; then
    psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -c \
      "CREATE ROLE ${DBUSER} LOGIN PASSWORD '${DBPASS}' SUPERUSER"
  fi
  if ! psql -h 127.0.0.1 -p "$PGPORT" -U postgres -d postgres -tAc \
      "SELECT 1 FROM pg_database WHERE datname='${DBNAME}'" | grep -q 1; then
    createdb -h 127.0.0.1 -p "$PGPORT" -U postgres -O "${DBUSER}" "${DBNAME}"
  fi

  if command -v redis-server >/dev/null 2>&1 && ! redis-cli -p 6379 ping >/dev/null 2>&1; then
    echo "[start] starting Redis on port 6379"
    redis-server --daemonize yes --port 6379 --dir /tmp --save "" >/tmp/gse-redis.log 2>&1 || \
      echo "[start] WARN: redis failed to start (non-fatal — cache is optional)"
  fi

  if [ ! -f "$ENVFILE" ]; then
    echo "[start] writing apps/web/.env.local (real Postgres)"
    cat > "$ENVFILE" <<EOF
# Auto-generated by .cursor/start.sh for Cloud Agent local dev. Gitignored.
DATABASE_URL=${DBURL}
DIRECT_URL=${DBURL}
FORCE_REAL_PRISMA=true
NEXTAUTH_SECRET=$(secret)
NEXTAUTH_URL=http://localhost:3000
DEV_FAKE_ADMIN=true
NODE_ENV=development
PUBLIC_PICKS_ENABLED=true
DEMO_PICKS_ENABLED=true
REDIS_URL=redis://127.0.0.1:6379
EOF
  fi

  export DATABASE_URL="$DBURL" DIRECT_URL="$DBURL"
  echo "[start] pushing Prisma schema..."
  npm run db:push --workspace=packages/db
  echo "[start] seeding (idempotent)..."
  npm run db:seed --workspace=packages/db || echo "[start] WARN: seed reported an issue (non-fatal)"
  echo "[start] ready — Postgres :$PGPORT db=$DBNAME, Redis :6379."
else
  # -------------------------------------------------------------- stub mode --
  echo "[start] Postgres not present in base image — using stub-DB dev mode (Path B)."
  if [ ! -f "$ENVFILE" ]; then
    echo "[start] writing apps/web/.env.local (stub DB + demo picks)"
    cat > "$ENVFILE" <<EOF
# Auto-generated by .cursor/start.sh for Cloud Agent local dev. Gitignored.
DATABASE_URL=stub
DIRECT_URL=stub
NEXTAUTH_SECRET=$(secret)
NEXTAUTH_URL=http://localhost:3000
DEV_FAKE_ADMIN=true
NODE_ENV=development
PUBLIC_PICKS_ENABLED=true
DEMO_PICKS_ENABLED=true
EOF
  fi
  echo "[start] ready — stub DB. The app renders realistic sample data with no database."
fi
