const INTERNAL_FANTASY_PREFIXES = ["/fantasy/studio"] as const;

/**
 * Next.js metadata-image routes generated by the opengraph-image / twitter-image
 * file conventions (optionally suffixed, e.g. "opengraph-image-a1b2c3"). These
 * are fetched by social-network crawlers, which do not follow the 307 to the
 * fantasy hub — redirecting them breaks every social card for gated paths, so
 * they are exempt from the gate (verification finding M2, 2026-07-16).
 */
const METADATA_IMAGE_SEGMENT = /\/(?:opengraph|twitter)-image(?:-\w+)?$/;

function isPathOrChild(pathname: string, route: string): boolean {
  return pathname === route || pathname.startsWith(`${route}/`);
}

export function isMetadataImagePath(pathname: string): boolean {
  return METADATA_IMAGE_SEGMENT.test(pathname);
}

export function isPublicFantasyToolPath(pathname: string): boolean {
  if (isMetadataImagePath(pathname)) return false;
  if (isPathOrChild(pathname, "/optimizer")) return true;
  if (!pathname.startsWith("/fantasy/")) return false;

  return !INTERNAL_FANTASY_PREFIXES.some((route) => isPathOrChild(pathname, route));
}

export function fantasyGateDestination(pathname: string): string {
  const params = new URLSearchParams({ from: pathname });
  return `/fantasy?${params.toString()}`;
}
