/**
 * Galaxy Studios. The weekly brief, generated from the whole OS.
 *
 * Pulls the week's signal from every surface. Waiver targets, scheme moves,
 * roster risk from the League Twin, the DFS leverage play, and the sharpest
 * pick'em edge. And composes a production-ready DRAFT. It is a text artifact for
 * a human to review and publish; it never auto-publishes anywhere. Pure,
 * deterministic, illustrative.
 */

import { waiverTargets } from "./waivers";
import { SCHEME_SCENARIOS, applyScheme } from "./scheme";
import { buildLeagueTwin } from "./league-twin";
import { TIER_WEIGHT } from "../news/impact";
import { DFS_SLATE, leverage } from "./dfs-slate";
import { PROPS, readProp } from "./props";

export type BriefSection = { readonly heading: string; readonly items: readonly string[] };
export type WeeklyBrief = {
  readonly draftOnly: true;
  readonly week: number;
  readonly title: string;
  readonly intro: string;
  readonly sections: readonly BriefSection[];
  readonly plaintext: string;
};

export function generateWeeklyBrief(): WeeklyBrief {
  const twin = buildLeagueTwin();
  const week = twin.currentWeek;

  // Waivers. Top 3 adds
  const adds = waiverTargets().slice(0, 3).map((r) =>
    `${r.player.name} (${r.player.team}, ${r.player.pos}). ${r.tier}, bid ~${Math.round(r.bidPct * 100)}% FAAB: ${r.reason}`,
  );

  // Scheme. The most reliable move
  const topScheme = [...SCHEME_SCENARIOS].sort((a, b) => TIER_WEIGHT[b.tier] - TIER_WEIGHT[a.tier])[0]!;
  const cascade = applyScheme(topScheme);
  const topGainer = cascade.impacts.find((i) => i.direction === "up");
  const topFader = cascade.impacts.find((i) => i.direction === "down");
  const scheme = [
    `${topScheme.team}: ${topScheme.headline} (${topScheme.tier}, ${Math.round(cascade.confidence * 100)}% confidence).`,
    topGainer ? `Riser. ${topGainer.player.name} ${topGainer.deltaPct >= 0 ? "+" : ""}${topGainer.deltaPct}%: ${topGainer.why}` : "",
    topFader ? `Fader. ${topFader.player.name} ${topFader.deltaPct}%: ${topFader.why}` : "",
  ].filter(Boolean);

  // Roster risk. Eclipses and shocks
  const risk = twin.nodes
    .filter((n) => n.eclipsed || n.shock === "critical" || n.shock === "caution")
    .slice(0, 4)
    .map((n) => `${n.player.name} (${n.player.team}). ${n.eclipsed ? `on bye W${week}; ` : ""}${n.shockNote}`);

  // DFS leverage play
  const dfsTop = [...DFS_SLATE].sort((a, b) => leverage(b) - leverage(a))[0]!;
  const dfs = [`${dfsTop.name} (${dfsTop.team}, ${dfsTop.pos}). Leverage ${leverage(dfsTop).toFixed(1)} at ${Math.round(dfsTop.own * 100)}% owned: the contrarian ceiling of the slate.`];

  // Pick'em edge
  const topProp = PROPS.map(readProp).sort((a, b) => b.edge - a.edge)[0]!;
  const props = [`${topProp.prop.player} ${topProp.side.toUpperCase()} ${topProp.prop.market} ${topProp.prop.line}. ${Math.round(topProp.pSide * 100)}% on our number. ${topProp.note}`];

  const sections: BriefSection[] = [
    { heading: "Waiver wire. Spend here", items: adds },
    { heading: "Scheme watch", items: scheme },
    { heading: "Roster risk & byes", items: risk.length ? risk : ["No blackout exposure this week. Your starters are clear."] },
    { heading: "DFS leverage play", items: dfs },
    { heading: "Pick'em edge of the week", items: props },
  ];

  const title = `The Galaxy Brief. Week ${week}`;
  const intro = `Your week in one read: where the FAAB goes, the scheme move that's re-pricing an offense, the byes that eclipse your lineup, and the single sharpest edge in DFS and pick'em.`;

  const plaintext = [
    title,
    "",
    intro,
    "",
    ...sections.flatMap((s) => [`## ${s.heading}`, ...s.items.map((i) => `- ${i}`), ""]),
    ",  Generated by Galaxy Studios. DRAFT for human review; not published.",
  ].join("\n");

  return { draftOnly: true, week, title, intro, sections, plaintext };
}
