/**
 * Odds-API / ESPN team names → Kalshi exchange abbreviations.
 * Without this map, full names never resolve → Kalshi independent is dead.
 * Null = honest no-opinion (never invent tickers).
 *
 * Leagues: NFL/NBA/MLB/NHL (majors) + WNBA/CFB/CBB + EPL/MLS (soccer game series).
 * CFB/CBB maps cover high-volume programs; unmapped → null (series search still
 * needs an abbr — expand as Kalshi coverage is verified live).
 */

import type { KalshiLeagueCode } from "@sports/data-ingestion";

/** Normalize for lookup: lower, strip punctuation, collapse whitespace. */
export function normalizeTeamKey(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Full + short keys → Kalshi abbr (uppercase). */
const NFL: Readonly<Record<string, string>> = {
  "arizona cardinals": "ARI",
  cardinals: "ARI",
  ari: "ARI",
  "atlanta falcons": "ATL",
  falcons: "ATL",
  atl: "ATL",
  "baltimore ravens": "BAL",
  ravens: "BAL",
  bal: "BAL",
  "buffalo bills": "BUF",
  bills: "BUF",
  buf: "BUF",
  "carolina panthers": "CAR",
  panthers: "CAR",
  car: "CAR",
  "chicago bears": "CHI",
  bears: "CHI",
  chi: "CHI",
  "cincinnati bengals": "CIN",
  bengals: "CIN",
  cin: "CIN",
  "cleveland browns": "CLE",
  browns: "CLE",
  cle: "CLE",
  "dallas cowboys": "DAL",
  cowboys: "DAL",
  dal: "DAL",
  "denver broncos": "DEN",
  broncos: "DEN",
  den: "DEN",
  "detroit lions": "DET",
  lions: "DET",
  det: "DET",
  "green bay packers": "GB",
  packers: "GB",
  gb: "GB",
  "houston texans": "HOU",
  texans: "HOU",
  hou: "HOU",
  "indianapolis colts": "IND",
  colts: "IND",
  ind: "IND",
  "jacksonville jaguars": "JAX",
  jaguars: "JAX",
  jax: "JAX",
  "kansas city chiefs": "KC",
  chiefs: "KC",
  kc: "KC",
  "las vegas raiders": "LV",
  raiders: "LV",
  lv: "LV",
  "los angeles chargers": "LAC",
  chargers: "LAC",
  lac: "LAC",
  "los angeles rams": "LAR",
  rams: "LAR",
  lar: "LAR",
  "miami dolphins": "MIA",
  dolphins: "MIA",
  mia: "MIA",
  "minnesota vikings": "MIN",
  vikings: "MIN",
  min: "MIN",
  "new england patriots": "NE",
  patriots: "NE",
  ne: "NE",
  "new orleans saints": "NO",
  saints: "NO",
  no: "NO",
  "new york giants": "NYG",
  giants: "NYG",
  nyg: "NYG",
  "new york jets": "NYJ",
  jets: "NYJ",
  nyj: "NYJ",
  "philadelphia eagles": "PHI",
  eagles: "PHI",
  phi: "PHI",
  "pittsburgh steelers": "PIT",
  steelers: "PIT",
  pit: "PIT",
  "san francisco 49ers": "SF",
  "san francisco forty niners": "SF",
  "49ers": "SF",
  sf: "SF",
  "seattle seahawks": "SEA",
  seahawks: "SEA",
  sea: "SEA",
  "tampa bay buccaneers": "TB",
  buccaneers: "TB",
  bucs: "TB",
  tb: "TB",
  "tennessee titans": "TEN",
  titans: "TEN",
  ten: "TEN",
  "washington commanders": "WAS",
  commanders: "WAS",
  was: "WAS",
  wsh: "WAS",
};

const NBA: Readonly<Record<string, string>> = {
  "atlanta hawks": "ATL",
  hawks: "ATL",
  "boston celtics": "BOS",
  celtics: "BOS",
  bos: "BOS",
  "brooklyn nets": "BKN",
  nets: "BKN",
  bkn: "BKN",
  "charlotte hornets": "CHA",
  hornets: "CHA",
  cha: "CHA",
  "chicago bulls": "CHI",
  bulls: "CHI",
  "cleveland cavaliers": "CLE",
  cavaliers: "CLE",
  cavs: "CLE",
  "dallas mavericks": "DAL",
  mavericks: "DAL",
  mavs: "DAL",
  "denver nuggets": "DEN",
  nuggets: "DEN",
  "detroit pistons": "DET",
  pistons: "DET",
  "golden state warriors": "GSW",
  warriors: "GSW",
  gsw: "GSW",
  "houston rockets": "HOU",
  rockets: "HOU",
  "indiana pacers": "IND",
  pacers: "IND",
  "la clippers": "LAC",
  "los angeles clippers": "LAC",
  clippers: "LAC",
  "la lakers": "LAL",
  "los angeles lakers": "LAL",
  lakers: "LAL",
  lal: "LAL",
  "memphis grizzlies": "MEM",
  grizzlies: "MEM",
  mem: "MEM",
  "miami heat": "MIA",
  heat: "MIA",
  "milwaukee bucks": "MIL",
  bucks: "MIL",
  mil: "MIL",
  "minnesota timberwolves": "MIN",
  timberwolves: "MIN",
  "new orleans pelicans": "NOP",
  pelicans: "NOP",
  nop: "NOP",
  "new york knicks": "NYK",
  knicks: "NYK",
  nyk: "NYK",
  "oklahoma city thunder": "OKC",
  thunder: "OKC",
  okc: "OKC",
  "orlando magic": "ORL",
  magic: "ORL",
  orl: "ORL",
  "philadelphia 76ers": "PHI",
  "philadelphia sixers": "PHI",
  "76ers": "PHI",
  sixers: "PHI",
  "phoenix suns": "PHX",
  suns: "PHX",
  phx: "PHX",
  "portland trail blazers": "POR",
  "trail blazers": "POR",
  blazers: "POR",
  por: "POR",
  "sacramento kings": "SAC",
  kings: "SAC",
  sac: "SAC",
  "san antonio spurs": "SAS",
  spurs: "SAS",
  sas: "SAS",
  "toronto raptors": "TOR",
  raptors: "TOR",
  tor: "TOR",
  "utah jazz": "UTA",
  jazz: "UTA",
  uta: "UTA",
  "washington wizards": "WAS",
  wizards: "WAS",
};

const MLB: Readonly<Record<string, string>> = {
  "arizona diamondbacks": "ARI",
  diamondbacks: "ARI",
  "atlanta braves": "ATL",
  braves: "ATL",
  "baltimore orioles": "BAL",
  orioles: "BAL",
  "boston red sox": "BOS",
  "red sox": "BOS",
  "chicago cubs": "CHC",
  cubs: "CHC",
  chc: "CHC",
  "chicago white sox": "CWS",
  "white sox": "CWS",
  cws: "CWS",
  "cincinnati reds": "CIN",
  reds: "CIN",
  "cleveland guardians": "CLE",
  guardians: "CLE",
  "colorado rockies": "COL",
  rockies: "COL",
  col: "COL",
  "detroit tigers": "DET",
  tigers: "DET",
  "houston astros": "HOU",
  astros: "HOU",
  "kansas city royals": "KC",
  royals: "KC",
  "los angeles angels": "LAA",
  angels: "LAA",
  laa: "LAA",
  "los angeles dodgers": "LAD",
  dodgers: "LAD",
  lad: "LAD",
  "miami marlins": "MIA",
  marlins: "MIA",
  "milwaukee brewers": "MIL",
  brewers: "MIL",
  "minnesota twins": "MIN",
  twins: "MIN",
  "new york mets": "NYM",
  mets: "NYM",
  nym: "NYM",
  "new york yankees": "NYY",
  yankees: "NYY",
  nyy: "NYY",
  // Kalshi uses ATH for Athletics (live 2026-08: …TBATH)
  "oakland athletics": "ATH",
  athletics: "ATH",
  "a s": "ATH",
  "the a s": "ATH",
  oak: "ATH",
  ath: "ATH",
  "philadelphia phillies": "PHI",
  phillies: "PHI",
  "pittsburgh pirates": "PIT",
  pirates: "PIT",
  "san diego padres": "SD",
  padres: "SD",
  sd: "SD",
  "san francisco giants": "SF",
  "seattle mariners": "SEA",
  mariners: "SEA",
  "st louis cardinals": "STL",
  "st. louis cardinals": "STL",
  stl: "STL",
  "tampa bay rays": "TB",
  rays: "TB",
  "texas rangers": "TEX",
  rangers: "TEX",
  tex: "TEX",
  "toronto blue jays": "TOR",
  "blue jays": "TOR",
  "washington nationals": "WSH",
  nationals: "WSH",
  wsh: "WSH",
};

const NHL: Readonly<Record<string, string>> = {
  "anaheim ducks": "ANA",
  ducks: "ANA",
  ana: "ANA",
  "boston bruins": "BOS",
  bruins: "BOS",
  "buffalo sabres": "BUF",
  sabres: "BUF",
  "calgary flames": "CGY",
  flames: "CGY",
  cgy: "CGY",
  "carolina hurricanes": "CAR",
  hurricanes: "CAR",
  "chicago blackhawks": "CHI",
  blackhawks: "CHI",
  "colorado avalanche": "COL",
  avalanche: "COL",
  "columbus blue jackets": "CBJ",
  "blue jackets": "CBJ",
  cbj: "CBJ",
  "dallas stars": "DAL",
  stars: "DAL",
  "detroit red wings": "DET",
  "red wings": "DET",
  "edmonton oilers": "EDM",
  oilers: "EDM",
  edm: "EDM",
  "florida panthers": "FLA",
  fla: "FLA",
  "los angeles kings": "LA",
  "la kings": "LA",
  "minnesota wild": "MIN",
  wild: "MIN",
  "montreal canadiens": "MTL",
  canadiens: "MTL",
  mtl: "MTL",
  "nashville predators": "NSH",
  predators: "NSH",
  nsh: "NSH",
  "new jersey devils": "NJD",
  devils: "NJD",
  njd: "NJD",
  "new york islanders": "NYI",
  islanders: "NYI",
  nyi: "NYI",
  "new york rangers": "NYR",
  nyr: "NYR",
  "ottawa senators": "OTT",
  senators: "OTT",
  ott: "OTT",
  "philadelphia flyers": "PHI",
  flyers: "PHI",
  "pittsburgh penguins": "PIT",
  penguins: "PIT",
  "san jose sharks": "SJ",
  sharks: "SJ",
  sj: "SJ",
  "seattle kraken": "SEA",
  kraken: "SEA",
  "st louis blues": "STL",
  "st. louis blues": "STL",
  blues: "STL",
  "tampa bay lightning": "TB",
  lightning: "TB",
  "toronto maple leafs": "TOR",
  "maple leafs": "TOR",
  "utah hockey club": "UTA",
  "vancouver canucks": "VAN",
  canucks: "VAN",
  van: "VAN",
  "vegas golden knights": "VGK",
  "golden knights": "VGK",
  vgk: "VGK",
  "washington capitals": "WSH",
  capitals: "WSH",
  "winnipeg jets": "WPG",
  wpg: "WPG",
};

const WNBA: Readonly<Record<string, string>> = {
  "atlanta dream": "ATL",
  dream: "ATL",
  "chicago sky": "CHI",
  sky: "CHI",
  "connecticut sun": "CON",
  sun: "CON",
  con: "CON",
  "dallas wings": "DAL",
  wings: "DAL",
  "indiana fever": "IND",
  fever: "IND",
  "las vegas aces": "LV",
  aces: "LV",
  "los angeles sparks": "LA",
  sparks: "LA",
  "minnesota lynx": "MIN",
  lynx: "MIN",
  "new york liberty": "NY",
  liberty: "NY",
  "phoenix mercury": "PHX",
  mercury: "PHX",
  "seattle storm": "SEA",
  storm: "SEA",
  "washington mystics": "WAS",
  mystics: "WAS",
  "golden state valkyries": "GS",
  valkyries: "GS",
};

/** High-volume CFB programs (Kalshi CFB game series). Expand as coverage verified. */
const CFB: Readonly<Record<string, string>> = {
  "alabama crimson tide": "ALA",
  alabama: "ALA",
  ala: "ALA",
  "georgia bulldogs": "UGA",
  georgia: "UGA",
  uga: "UGA",
  "ohio state buckeyes": "OHIOST",
  "ohio state": "OHIOST",
  "michigan wolverines": "MICH",
  michigan: "MICH",
  "texas longhorns": "TEX",
  "texas a m": "TXAM",
  "texas am": "TXAM",
  "oregon ducks": "ORE",
  oregon: "ORE",
  "penn state nittany lions": "PSU",
  "penn state": "PSU",
  "notre dame fighting irish": "ND",
  "notre dame": "ND",
  "lsu tigers": "LSU",
  lsu: "LSU",
  "florida state seminoles": "FSU",
  "florida state": "FSU",
  "clemson tigers": "CLEM",
  clemson: "CLEM",
  "usc trojans": "USC",
  usc: "USC",
  "miami hurricanes": "MIA",
  "oklahoma sooners": "OU",
  oklahoma: "OU",
  "tennessee volunteers": "TENN",
  tennessee: "TENN",
  "ole miss rebels": "MISS",
  "ole miss": "MISS",
  "washington huskies": "WASH",
  "florida gators": "FLA",
  "auburn tigers": "AUB",
  auburn: "AUB",
};

const CBB: Readonly<Record<string, string>> = {
  "duke blue devils": "DUKE",
  duke: "DUKE",
  "north carolina tar heels": "UNC",
  "north carolina": "UNC",
  unc: "UNC",
  "kansas jayhawks": "KU",
  kansas: "KU",
  "kentucky wildcats": "UK",
  kentucky: "UK",
  "gonzaga bulldogs": "GONZ",
  gonzaga: "GONZ",
  "uconn huskies": "CONN",
  uconn: "CONN",
  connecticut: "CONN",
  "houston cougars": "HOU",
  "purdue boilermakers": "PUR",
  purdue: "PUR",
  "arizona wildcats": "ARIZ",
  arizona: "ARIZ",
  "michigan state spartans": "MSU",
  "michigan state": "MSU",
  "villanova wildcats": "VILL",
  villanova: "VILL",
  "baylor bears": "BAY",
  baylor: "BAY",
  "indiana hoosiers": "IND",
  "ucla bruins": "UCLA",
  ucla: "UCLA",
};

/** EPL Kalshi abbrs verified live 2026-08 (NEW, LFC, MCI, BOU, BRI, AVL, BRE, TOT). */
const EPL: Readonly<Record<string, string>> = {
  "arsenal": "ARS",
  "arsenal fc": "ARS",
  ars: "ARS",
  "aston villa": "AVL",
  villa: "AVL",
  avl: "AVL",
  "bournemouth": "BOU",
  "afc bournemouth": "BOU",
  bou: "BOU",
  "brentford": "BRE",
  "brentford fc": "BRE",
  bre: "BRE",
  "brighton": "BRI",
  "brighton and hove albion": "BRI",
  "brighton hove albion": "BRI",
  bri: "BRI",
  "chelsea": "CHE",
  "chelsea fc": "CHE",
  che: "CHE",
  "crystal palace": "CRY",
  cry: "CRY",
  "everton": "EVE",
  "everton fc": "EVE",
  eve: "EVE",
  "fulham": "FUL",
  "fulham fc": "FUL",
  ful: "FUL",
  "ipswich": "IPS",
  "ipswich town": "IPS",
  "leicester": "LEI",
  "leicester city": "LEI",
  "liverpool": "LFC",
  "liverpool fc": "LFC",
  lfc: "LFC",
  "manchester city": "MCI",
  "man city": "MCI",
  mci: "MCI",
  "manchester united": "MUN",
  "man united": "MUN",
  "man utd": "MUN",
  mun: "MUN",
  "newcastle": "NEW",
  "newcastle united": "NEW",
  new: "NEW",
  "nottingham forest": "NFO",
  forest: "NFO",
  nfo: "NFO",
  "southampton": "SOU",
  "tottenham": "TOT",
  "tottenham hotspur": "TOT",
  spurs: "TOT",
  tot: "TOT",
  "west ham": "WHU",
  "west ham united": "WHU",
  whu: "WHU",
  "wolves": "WOL",
  "wolverhampton": "WOL",
  "wolverhampton wanderers": "WOL",
  wol: "WOL",
};

const MLS: Readonly<Record<string, string>> = {
  "inter miami": "MIA",
  "inter miami cf": "MIA",
  "la galaxy": "LAG",
  "los angeles galaxy": "LAG",
  "lafc": "LAFC",
  "los angeles fc": "LAFC",
  "seattle sounders": "SEA",
  "seattle sounders fc": "SEA",
  "atlanta united": "ATL",
  "atlanta united fc": "ATL",
  "new york city fc": "NYC",
  "nycfc": "NYC",
  "new york red bulls": "RBNY",
  "portland timbers": "POR",
  "austin fc": "ATX",
  "fc cincinnati": "CIN",
  "columbus crew": "CLB",
  "philadelphia union": "PHI",
  "orlando city": "ORL",
  "orlando city sc": "ORL",
  "chicago fire": "CHI",
  "sporting kansas city": "SKC",
  "minnesota united": "MIN",
  "real salt lake": "RSL",
  "vancouver whitecaps": "VAN",
  "toronto fc": "TOR",
  "cf montreal": "MTL",
  "montreal impact": "MTL",
};

/** Lightweight tables for remaining soccer series (abbr-heavy; expand live). */
const LALIGA: Readonly<Record<string, string>> = {
  "real madrid": "RMA",
  "barcelona": "BAR",
  "fc barcelona": "BAR",
  "atletico madrid": "ATM",
  "atlético madrid": "ATM",
  "sevilla": "SEV",
  "real sociedad": "RSO",
  "athletic club": "ATH",
  "athletic bilbao": "ATH",
  "villarreal": "VIL",
  "real betis": "BET",
};

const BUNDESLIGA: Readonly<Record<string, string>> = {
  "bayern munich": "BAY",
  "bayern munchen": "BAY",
  "fc bayern munich": "BAY",
  "borussia dortmund": "BVB",
  dortmund: "BVB",
  "rb leipzig": "RBL",
  "bayer leverkusen": "B04",
  leverkusen: "B04",
  "eintracht frankfurt": "SGE",
  "borussia monchengladbach": "BMG",
  "vfb stuttgart": "VFB",
  stuttgart: "VFB",
};

const SERIEA: Readonly<Record<string, string>> = {
  "inter": "INT",
  "inter milan": "INT",
  "internazionale": "INT",
  "ac milan": "MIL",
  milan: "MIL",
  "juventus": "JUV",
  "ssc napoli": "NAP",
  napoli: "NAP",
  "as roma": "ROM",
  roma: "ROM",
  "ss lazio": "LAZ",
  lazio: "LAZ",
  "atalanta": "ATA",
  "fiorentina": "FIO",
};

const LIGUE1: Readonly<Record<string, string>> = {
  "paris saint germain": "PSG",
  "paris sg": "PSG",
  psg: "PSG",
  "olympique marseille": "OM",
  marseille: "OM",
  "olympique lyonnais": "OL",
  lyon: "OL",
  "as monaco": "ASM",
  monaco: "ASM",
  "lille": "LIL",
  "rc lens": "RCL",
  lens: "RCL",
  "ogc nice": "NIC",
  nice: "NIC",
};

const UCL: Readonly<Record<string, string>> = {
  ...EPL,
  ...LALIGA,
  ...BUNDESLIGA,
  ...SERIEA,
  ...LIGUE1,
};

const BY_LEAGUE: Readonly<
  Record<KalshiLeagueCode, Readonly<Record<string, string>>>
> = {
  NFL,
  NBA,
  MLB,
  NHL,
  WNBA,
  CFB,
  CBB,
  EPL,
  UCL,
  LALIGA,
  BUNDESLIGA,
  SERIEA,
  LIGUE1,
  MLS,
};

/**
 * Resolve Kalshi team abbreviation for a league + team name.
 * Returns null when unmapped (honest no-opinion).
 */
export function resolveKalshiTeamAbbr(
  league: KalshiLeagueCode,
  teamName: string,
): string | null {
  const t = teamName.trim();
  if (!t) return null;
  // Already a short abbr (2–6 for CFB stems like OHIOST)
  if (/^[A-Za-z]{2,6}$/.test(t)) return t.toUpperCase();
  const paren = t.match(/\(([A-Za-z]{2,6})\)/);
  if (paren?.[1]) return paren[1].toUpperCase();

  const key = normalizeTeamKey(t);
  const table = BY_LEAGUE[league];
  if (!table) return null;
  if (table[key]) return table[key]!;

  // Last token only when unique-ish (e.g. "Cowboys")
  const parts = key.split(" ");
  if (parts.length > 1) {
    const last = parts[parts.length - 1]!;
    if (table[last]) return table[last]!;
  }
  return null;
}
