/**
 * Odds-API / ESPN team names → Kalshi exchange abbreviations.
 * Without this map, full names never resolve → Kalshi independent is dead.
 * Null = honest no-opinion (never invent tickers).
 */

/** Normalize for lookup: lower, strip punctuation, collapse whitespace. */
export function normalizeTeamKey(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Full + short keys → Kalshi abbr (uppercase). */
const NFL: Readonly<Record<string, string>> = {
  "arizona cardinals": "ARI",
  cardinals: "ARI",
  ari: "ARI",
  "atlanta falcons": "ATL",
  falcons: "ATL",
  atl: "ATL",
  "baltimore ravens": "BAL",
  ravens: "BAL",
  bal: "BAL",
  "buffalo bills": "BUF",
  bills: "BUF",
  buf: "BUF",
  "carolina panthers": "CAR",
  panthers: "CAR",
  car: "CAR",
  "chicago bears": "CHI",
  bears: "CHI",
  chi: "CHI",
  "cincinnati bengals": "CIN",
  bengals: "CIN",
  cin: "CIN",
  "cleveland browns": "CLE",
  browns: "CLE",
  cle: "CLE",
  "dallas cowboys": "DAL",
  cowboys: "DAL",
  dal: "DAL",
  "denver broncos": "DEN",
  broncos: "DEN",
  den: "DEN",
  "detroit lions": "DET",
  lions: "DET",
  det: "DET",
  "green bay packers": "GB",
  packers: "GB",
  gb: "GB",
  "houston texans": "HOU",
  texans: "HOU",
  hou: "HOU",
  "indianapolis colts": "IND",
  colts: "IND",
  ind: "IND",
  "jacksonville jaguars": "JAX",
  jaguars: "JAX",
  jax: "JAX",
  "kansas city chiefs": "KC",
  chiefs: "KC",
  kc: "KC",
  "las vegas raiders": "LV",
  raiders: "LV",
  lv: "LV",
  "los angeles chargers": "LAC",
  chargers: "LAC",
  lac: "LAC",
  "los angeles rams": "LAR",
  rams: "LAR",
  lar: "LAR",
  "miami dolphins": "MIA",
  dolphins: "MIA",
  mia: "MIA",
  "minnesota vikings": "MIN",
  vikings: "MIN",
  min: "MIN",
  "new england patriots": "NE",
  patriots: "NE",
  ne: "NE",
  "new orleans saints": "NO",
  saints: "NO",
  no: "NO",
  "new york giants": "NYG",
  giants: "NYG",
  nyg: "NYG",
  "new york jets": "NYJ",
  jets: "NYJ",
  nyj: "NYJ",
  "philadelphia eagles": "PHI",
  eagles: "PHI",
  phi: "PHI",
  "pittsburgh steelers": "PIT",
  steelers: "PIT",
  pit: "PIT",
  "san francisco 49ers": "SF",
  "san francisco forty niners": "SF",
  "49ers": "SF",
  sf: "SF",
  "seattle seahawks": "SEA",
  seahawks: "SEA",
  sea: "SEA",
  "tampa bay buccaneers": "TB",
  buccaneers: "TB",
  bucs: "TB",
  tb: "TB",
  "tennessee titans": "TEN",
  titans: "TEN",
  ten: "TEN",
  "washington commanders": "WAS",
  commanders: "WAS",
  was: "WAS",
  wsh: "WAS",
};

const NBA: Readonly<Record<string, string>> = {
  "atlanta hawks": "ATL",
  hawks: "ATL",
  "boston celtics": "BOS",
  celtics: "BOS",
  bos: "BOS",
  "brooklyn nets": "BKN",
  nets: "BKN",
  bkn: "BKN",
  "charlotte hornets": "CHA",
  hornets: "CHA",
  cha: "CHA",
  "chicago bulls": "CHI",
  bulls: "CHI",
  "cleveland cavaliers": "CLE",
  cavaliers: "CLE",
  cavs: "CLE",
  "dallas mavericks": "DAL",
  mavericks: "DAL",
  mavs: "DAL",
  "denver nuggets": "DEN",
  nuggets: "DEN",
  "detroit pistons": "DET",
  pistons: "DET",
  "golden state warriors": "GSW",
  warriors: "GSW",
  gsw: "GSW",
  "houston rockets": "HOU",
  rockets: "HOU",
  "indiana pacers": "IND",
  pacers: "IND",
  "la clippers": "LAC",
  "los angeles clippers": "LAC",
  clippers: "LAC",
  "la lakers": "LAL",
  "los angeles lakers": "LAL",
  lakers: "LAL",
  lal: "LAL",
  "memphis grizzlies": "MEM",
  grizzlies: "MEM",
  mem: "MEM",
  "miami heat": "MIA",
  heat: "MIA",
  "milwaukee bucks": "MIL",
  bucks: "MIL",
  mil: "MIL",
  "minnesota timberwolves": "MIN",
  timberwolves: "MIN",
  "new orleans pelicans": "NOP",
  pelicans: "NOP",
  nop: "NOP",
  "new york knicks": "NYK",
  knicks: "NYK",
  nyk: "NYK",
  "oklahoma city thunder": "OKC",
  thunder: "OKC",
  okc: "OKC",
  "orlando magic": "ORL",
  magic: "ORL",
  orl: "ORL",
  "philadelphia 76ers": "PHI",
  "philadelphia sixers": "PHI",
  "76ers": "PHI",
  sixers: "PHI",
  "phoenix suns": "PHX",
  suns: "PHX",
  phx: "PHX",
  "portland trail blazers": "POR",
  "trail blazers": "POR",
  blazers: "POR",
  por: "POR",
  "sacramento kings": "SAC",
  kings: "SAC",
  sac: "SAC",
  "san antonio spurs": "SAS",
  spurs: "SAS",
  sas: "SAS",
  "toronto raptors": "TOR",
  raptors: "TOR",
  tor: "TOR",
  "utah jazz": "UTA",
  jazz: "UTA",
  uta: "UTA",
  "washington wizards": "WAS",
  wizards: "WAS",
};

const MLB: Readonly<Record<string, string>> = {
  "arizona diamondbacks": "ARI",
  diamondbacks: "ARI",
  "atlanta braves": "ATL",
  braves: "ATL",
  "baltimore orioles": "BAL",
  orioles: "BAL",
  "boston red sox": "BOS",
  "red sox": "BOS",
  "chicago cubs": "CHC",
  cubs: "CHC",
  chc: "CHC",
  "chicago white sox": "CWS",
  "white sox": "CWS",
  cws: "CWS",
  "cincinnati reds": "CIN",
  reds: "CIN",
  "cleveland guardians": "CLE",
  guardians: "CLE",
  "colorado rockies": "COL",
  rockies: "COL",
  col: "COL",
  "detroit tigers": "DET",
  tigers: "DET",
  "houston astros": "HOU",
  astros: "HOU",
  "kansas city royals": "KC",
  royals: "KC",
  "los angeles angels": "LAA",
  angels: "LAA",
  laa: "LAA",
  "los angeles dodgers": "LAD",
  dodgers: "LAD",
  lad: "LAD",
  "miami marlins": "MIA",
  marlins: "MIA",
  "milwaukee brewers": "MIL",
  brewers: "MIL",
  "minnesota twins": "MIN",
  twins: "MIN",
  "new york mets": "NYM",
  mets: "NYM",
  nym: "NYM",
  "new york yankees": "NYY",
  yankees: "NYY",
  nyy: "NYY",
  "oakland athletics": "OAK",
  athletics: "OAK",
  "a s": "OAK",
  oak: "OAK",
  "philadelphia phillies": "PHI",
  phillies: "PHI",
  "pittsburgh pirates": "PIT",
  pirates: "PIT",
  "san diego padres": "SD",
  padres: "SD",
  sd: "SD",
  "san francisco giants": "SF",
  "seattle mariners": "SEA",
  mariners: "SEA",
  "st louis cardinals": "STL",
  "st. louis cardinals": "STL",
  stl: "STL",
  "tampa bay rays": "TB",
  rays: "TB",
  "texas rangers": "TEX",
  rangers: "TEX",
  tex: "TEX",
  "toronto blue jays": "TOR",
  "blue jays": "TOR",
  "washington nationals": "WSH",
  nationals: "WSH",
  wsh: "WSH",
};

const NHL: Readonly<Record<string, string>> = {
  "anaheim ducks": "ANA",
  ducks: "ANA",
  ana: "ANA",
  "boston bruins": "BOS",
  bruins: "BOS",
  "buffalo sabres": "BUF",
  sabres: "BUF",
  "calgary flames": "CGY",
  flames: "CGY",
  cgy: "CGY",
  "carolina hurricanes": "CAR",
  hurricanes: "CAR",
  "chicago blackhawks": "CHI",
  blackhawks: "CHI",
  "colorado avalanche": "COL",
  avalanche: "COL",
  "columbus blue jackets": "CBJ",
  "blue jackets": "CBJ",
  cbj: "CBJ",
  "dallas stars": "DAL",
  stars: "DAL",
  "detroit red wings": "DET",
  "red wings": "DET",
  "edmonton oilers": "EDM",
  oilers: "EDM",
  edm: "EDM",
  "florida panthers": "FLA",
  fla: "FLA",
  "los angeles kings": "LA",
  "la kings": "LA",
  "minnesota wild": "MIN",
  wild: "MIN",
  "montreal canadiens": "MTL",
  canadiens: "MTL",
  mtl: "MTL",
  "nashville predators": "NSH",
  predators: "NSH",
  nsh: "NSH",
  "new jersey devils": "NJD",
  devils: "NJD",
  njd: "NJD",
  "new york islanders": "NYI",
  islanders: "NYI",
  nyi: "NYI",
  "new york rangers": "NYR",
  nyr: "NYR",
  "ottawa senators": "OTT",
  senators: "OTT",
  ott: "OTT",
  "philadelphia flyers": "PHI",
  flyers: "PHI",
  "pittsburgh penguins": "PIT",
  penguins: "PIT",
  "san jose sharks": "SJ",
  sharks: "SJ",
  sj: "SJ",
  "seattle kraken": "SEA",
  kraken: "SEA",
  "st louis blues": "STL",
  "st. louis blues": "STL",
  blues: "STL",
  "tampa bay lightning": "TB",
  lightning: "TB",
  "toronto maple leafs": "TOR",
  "maple leafs": "TOR",
  "utah hockey club": "UTA",
  "vancouver canucks": "VAN",
  canucks: "VAN",
  van: "VAN",
  "vegas golden knights": "VGK",
  "golden knights": "VGK",
  vgk: "VGK",
  "washington capitals": "WSH",
  capitals: "WSH",
  "winnipeg jets": "WPG",
  wpg: "WPG",
};

const BY_LEAGUE: Readonly<
  Record<"NFL" | "NBA" | "MLB" | "NHL", Readonly<Record<string, string>>>
> = {
  NFL,
  NBA,
  MLB,
  NHL,
};

/**
 * Resolve Kalshi team abbreviation for a league + team name.
 * Returns null when unmapped (honest no-opinion).
 */
export function resolveKalshiTeamAbbr(
  league: "NFL" | "NBA" | "MLB" | "NHL",
  teamName: string,
): string | null {
  const t = teamName.trim();
  if (!t) return null;
  // Already a short abbr
  if (/^[A-Za-z]{2,4}$/.test(t)) return t.toUpperCase();
  const paren = t.match(/\(([A-Za-z]{2,4})\)/);
  if (paren?.[1]) return paren[1].toUpperCase();

  const key = normalizeTeamKey(t);
  const table = BY_LEAGUE[league];
  if (table[key]) return table[key]!;

  // Last token only when unique-ish (e.g. "Cowboys")
  const parts = key.split(" ");
  if (parts.length > 1) {
    const last = parts[parts.length - 1]!;
    if (table[last]) return table[last]!;
  }
  return null;
}
