# PROVENANCE — gse-intelligence-build / coaching / load.py
# Data-table loaders for the coaching tendency engine.
# Tables generated by coaching/build/build_tables.py from the base pipeline's
# pbp_2022..2026.parquet (see build_tables.py header for research basis).
# Runtime deps: stdlib csv only (tests/README.md rule 5 — no pandas/pyarrow).
"""Load coaching/data/*.csv tables with keyed lookup."""
from __future__ import annotations

import csv
import os
from typing import Any

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")

_TABLES: dict[str, list[dict[str, str]]] = {}


def _num(v: str) -> Any:
    if v is None or v == "":
        return None
    try:
        return int(v)
    except ValueError:
        pass
    try:
        return float(v)
    except ValueError:
        return v


def load_table(name: str, coerce: bool = True) -> list[dict[str, Any]]:
    """Load coaching/data/<name> (cached). Values coerced to int/float/None."""
    if name not in _TABLES:
        path = os.path.join(DATA_DIR, name)
        with open(path, newline="") as fh:
            rows = list(csv.DictReader(fh))
        if coerce:
            rows = [{k: _num(v) for k, v in r.items()} for r in rows]
        _TABLES[name] = rows
    return _TABLES[name]


def index_by(name: str, *keys: str) -> dict[tuple, dict[str, Any]]:
    """Index a table by key columns -> row."""
    return {tuple(r[k] for k in keys): r for r in load_table(name)}


def clear_cache() -> None:
    _TABLES.clear()
