/**
 * 2026 NFL clubs and divisions. Source: Firecrawl Alexandria nfl-com/sports-league-data/teams.
 * Observed with the 2026 club list. AZ is stored as ARI and LAR as LA, the GSE spellings.
 * A club not in this map is unknown. It is not assigned a division.
 */
export const NFL_2026_CLUBS_OBSERVED_AT = "2026-10-01T20:38:17Z";

export const NFL_2026_DIVISION: Readonly<Record<string, string>> = {
  ARI: "NFC West",
  ATL: "NFC South",
  BAL: "AFC North",
  BUF: "AFC East",
  CAR: "NFC South",
  CHI: "NFC North",
  CIN: "AFC North",
  CLE: "AFC North",
  DAL: "NFC East",
  DEN: "AFC West",
  DET: "NFC North",
  GB: "NFC North",
  HOU: "AFC South",
  IND: "AFC South",
  JAX: "AFC South",
  KC: "AFC West",
  LA: "NFC West",
  LAC: "AFC West",
  LV: "AFC West",
  MIA: "AFC East",
  MIN: "NFC North",
  NE: "AFC East",
  NO: "NFC South",
  NYG: "NFC East",
  NYJ: "AFC East",
  PHI: "NFC East",
  PIT: "AFC North",
  SEA: "NFC West",
  SF: "NFC West",
  TB: "NFC South",
  TEN: "AFC South",
  WAS: "NFC East",
};

export const NFL_2026_VENUE: Readonly<Record<string, string>> = {
  ARI: "State Farm Stadium",
  ATL: "Mercedes-Benz Stadium",
  BAL: "M&T Bank Stadium",
  BUF: "Highmark Stadium",
  CAR: "Bank of America Stadium",
  CHI: "Soldier Field",
  CIN: "Paycor Stadium",
  CLE: "Huntington Bank Field",
  DAL: "AT&T Stadium",
  DEN: "Empower Field at Mile High",
  DET: "Ford Field",
  GB: "Lambeau Field",
  HOU: "Reliant Stadium",
  IND: "Lucas Oil Stadium",
  JAX: "EverBank Stadium",
  KC: "Arrowhead Stadium",
  LA: "SoFi Stadium",
  LAC: "SoFi Stadium",
  LV: "Allegiant Stadium",
  MIA: "Hard Rock Stadium",
  MIN: "U.S. Bank Stadium",
  NE: "Gillette Stadium",
  NO: "Caesars Superdome",
  NYG: "MetLife Stadium",
  NYJ: "MetLife Stadium",
  PHI: "Lincoln Financial Field",
  PIT: "Acrisure Stadium",
  SEA: "Lumen Field",
  SF: "Levi's® Stadium",
  TB: "Raymond James Stadium",
  TEN: "Nissan Stadium",
  WAS: "Northwest Stadium",
};

