export type EquationCard = {
  id: string;
  name: string;
  law: string;
  owns: string;
  formula: string[];
  touches: string;
  forbidden: string;
};

export const EQUATIONS: EquationCard[] = [
  {
    id: "brier",
    name: "Brier score",
    law: "04",
    owns: "Local CPU",
    formula: ["BS = (1/n) Σ_i (p_i − y_i)²", "y_i ∈ {0, 1},   p_i ∈ [0, 1]"],
    touches: "The 306-drive holdout. Reported BS = 0.1621 against 0.1748 for win-probability-max.",
    forbidden: "Do not mix this with the +6.77 points. That figure is 3,988 decisions, not 306 drives.",
  },
  {
    id: "murphy",
    name: "Murphy decomposition of the Brier score",
    law: "04",
    owns: "Local CPU, diagnostic only",
    formula: ["BS = reliability − resolution + uncertainty"],
    touches:
      "Allan Murphy, 1973. Reliability is calibration. Resolution is how far the forecast separates the outcomes. Uncertainty is the base rate. A lower Brier can come from either of the first two.",
    forbidden: "Do not steer by a reliability diagram. Expected calibration error stays banned as a target.",
  },
  {
    id: "prior-shape",
    name: "Shape of the 2026 time-to-throw prior",
    law: "02",
    owns: "The field, not a cell",
    formula: ["n = 37 season means", "min 2.414    median 2.825    max 3.417", "2.1 is outside the observed support"],
    touches: "Week 0 of the combined passing file. A distribution of means. Watson’s 2.794 sits near the median.",
    forbidden: "Do not draw a snap from this distribution and call it observed.",
  },
  {
    id: "weighted-prior",
    name: "Attempt-weighted time-to-throw prior",
    law: "02",
    owns: "Local CPU, from the sealed week-0 table",
    formula: ["μ_w = Σ_i (attempts_i · ttt_i) / Σ_i attempts_i", "Unweighted mean treats a 34-attempt rate like a 153-attempt rate."],
    touches: "Computed on the Field from the 37 published 2026 season means. Still a distribution of means. Still not a snap.",
    forbidden: "Do not shrink a weekly mean toward this and call the result observed. Do not sample a play from it.",
  },
  {
    id: "drift",
    name: "Prior drift, week minus season",
    law: "02",
    owns: "Local CPU, Watson’s published means only",
    formula: ["Δ_w = ttt_week − ttt_season", "Both sides are means. The play remains NULL."],
    touches: "How far each of Watson’s 2026 weekly means sits from his season mean of 2.794 on 115 attempts. A movement of the prior, not evidence about a snap.",
    forbidden: "Do not explain a delta by an offensive-line injury. That is the ecological leap.",
  },
  {
    id: "skill",
    name: "Brier skill against the baseline",
    law: "04",
    owns: "Local CPU",
    formula: ["Δ = BS_base − BS", "BSS = 1 − BS / BS_base"],
    touches: "A relative reading of the same 306 drives. Computed in this console from the sealed inputs, not refit.",
    forbidden: "Skill is not a probability of winning a bet, and it is not a pick.",
  },
  {
    id: "log",
    name: "Logarithmic score",
    law: "04",
    owns: "Local CPU, not yet reported",
    formula: ["LS = −(1/n) Σ_i [ y_i log p_i + (1 − y_i) log(1 − p_i) ]"],
    touches: "The other strictly proper binary score. Gneiting and Raftery. Use it as a second look if Brier and a decision metric ever disagree.",
    forbidden: "The closed record does not report it. Do not backfill a number.",
  },
  {
    id: "isotonic",
    name: "Isotonic regression, pool-adjacent-violators",
    law: "04",
    owns: "Local CPU",
    formula: [
      "Sort by the raw score.",
      "While some adjacent pair falls, replace the pair by its weighted mean.",
      "The map m is monotone: m(s) estimates P(Y = 1 | score = s).",
    ],
    touches: "A post-hoc map on held-out scores. Niculescu-Mizil and Caruana. Manokhin and Grønhaug (2026) show it can worsen Brier.",
    forbidden: "Do not replace the shipped probabilities until the 306-drive Brier is recomputed and is not worse.",
  },
  {
    id: "wpmax",
    name: "Win-probability max, the comparator",
    law: "03",
    owns: "Baseline, not the shipped model",
    formula: ["a* = argmax_{a ∈ {go, fg, punt}} WP(state, a)"],
    touches: "The policy the estimator is compared with. nfl4th is the public implementation of this family. Lock and Nettleton are the ancestor.",
    forbidden: "Do not describe the shipped estimator as this rule. The record says it beats this rule by 6.77 points. The internal objective is not in the record.",
  },
  {
    id: "humility",
    name: "Humility constraint",
    law: "03",
    owns: "Admitted research, Brill, Yurko, Wyner",
    formula: [
      "For each alternative a and a′ ≠ a, build the bootstrap of WP(a) − WP(a′).",
      "Recommend a only if every difference is positive.",
      "Otherwise abstain.",
    ],
    touches: "The mathematical form of 'does not emit a pick.'",
    forbidden: "Not a claim about how the 6.77 was produced. Do not turn an abstention into a lean.",
  },
  {
    id: "spo",
    name: "Decision regret",
    law: "03",
    owns: "Not implemented. No fourth job.",
    formula: ["regret(θ̂, x, y) = c(x, y, w*(θ̂)) − c(x, y, w*(θ))"],
    touches: "Elmachtoub and Grigas; the Mandi survey. The research direction if someone later wants the training loss to be the decision, not the Brier.",
    forbidden: "Do not start a training job. Do not rent the H100. Do not assert that the shipped model already optimizes this.",
  },
  {
    id: "join",
    name: "Injury join",
    law: "01",
    owns: "The feature store",
    formula: [
      "row = injuries.lookup(gsis_id, team, week)",
      "if row is absent: cell = NULL",
      "NULL is not 0, not 'healthy', and not a draw",
    ],
    touches: "Starters from rosters onto the nflverse injury file. Gate 1 may cite Cleveland's two Out linemen.",
    forbidden: "Pittsburgh week 4 has zero offensive-line rows. Leave it null. Do not copy injury fields onto play-by-play.",
  },
  {
    id: "ttt",
    name: "Time-to-throw prior",
    law: "02",
    owns: "A prior. The play is unidentified.",
    formula: [
      "T_play = NULL",
      "T_prior = avg_time_to_throw at a named grain",
      "2.1 ∉ the support",
    ],
    touches: "Watson 2026 season grain is 2.794 on 115 attempts, which the record calls 2.79. Weekly means exist and are still means. Week 4 of the public passing table has two passers.",
    forbidden: "A weekly mean is not a snap. The 616-byte 2024 file is not a source. Gate 3 stays unvalidated. Trust labels do not exist.",
  },
  {
    id: "support",
    name: "Change of grain",
    law: "02",
    owns: "A ban, with Robinson 1950 underneath it",
    formula: [
      "A measurement on support W (a week) may shift a prior on support P (a play).",
      "It may not be substituted for a measurement on P.",
    ],
    touches: "How an Out lineman is allowed to enter a drive-level note, and how it is forbidden to enter a time-to-throw cell.",
    forbidden: "No ecological leap. No 'the line was hurt so this snap took 2.9 seconds.'",
  },
  {
    id: "clv",
    name: "Closing-line value",
    law: "05",
    owns: "Local CPU, once the column exists",
    formula: [
      "CLV = d_bet / d_close − 1",
      "Positive when the price taken is longer than the close.",
      "Crude de-vig: π_i = (1/d_i) / Σ_j (1/d_j)",
    ],
    touches: "The unlock for any rented card: 200 settled rows. Shin 1992 is the de-vig that should eventually replace the crude one.",
    forbidden: "A single spread_line is not a bet and a close. Do not count it. The Shin solver is not sealed here, because a wrong de-vig invents a probability.",
  },
  {
    id: "tau",
    name: "τ̂",
    law: "04",
    owns: "Named, not defined",
    formula: ["τ̂  is owned by local CPU.", "The closed record does not define it."],
    touches: "Nothing, until the definition is written down by the person who owns the estimator.",
    forbidden: "Keel will not guess whether this is a temperature, a threshold, a shrinkage weight, or a time constant.",
  },
  {
    id: "reviewer",
    name: "Reviewer contract",
    law: "05",
    owns: "A paid call, only if a key is later armed",
    formula: [
      '{ "verdict": "admit" | "hold" | "reject",',
      '  "grain": "play" | "week" | "season" | "market" | "theory",',
      '  "fills_null": false,',
      '  "equation": null,',
      '  "why": "one sentence" }',
    ],
    touches: "The JSON has to be in content. A reasoning trace with empty content is a miss, even if it was billed. Qwen3.5-9B already missed at 220 tokens.",
    forbidden: "This console does not call a model. NIM would be first and is not wired. Together stays under $20 a week if it is ever wired. No fourth LoRA. No H100 for a 20-row probe.",
  },
];
