import type { Finding } from "@/lib/types";

const AT = "2026-10-04T18:00:00.000Z";

function shelf(partial: Omit<Finding, "origin" | "foundAt">): Finding {
  return { ...partial, origin: "shelf", foundAt: AT };
}

/** Hand-verified. Not keyword-scored. Citations checked against the public record on 4 Oct 2026. */
export const SHELF: Finding[] = [
  shelf({
    id: "brill-2025",
    title: "Analytics, Have Some Humility: A Statistical View of Fourth-Down Decision Making",
    authors: "Ryan S. Brill, Ronald Yurko, Abraham J. Wyner",
    year: "2025",
    venue: "The American Statistician 79(3)",
    url: "https://arxiv.org/abs/2311.03490",
    abstract:
      "The standard mathematical approach is to maximize estimated win probability. Those models are high-variance and the plays are autocorrelated. Brill, Yurko, and Wyner put a bootstrap around the decision and recommend a call only when it is confidently better than the alternatives. Far fewer fourth downs are obvious than analysts claim.",
    verdict: "admit",
    grain: "decision",
    join: "none — constraint, not a feature",
    law: "03",
    lane: "fourth",
    equation: "Recommend a only if WP(a) beats every alternative on the bootstrap set; else abstain.",
    why: "This is the decision constraint that matches a partial label. It is not a claim that the shipped +6.77 points were computed this way. It does not emit a pick.",
  }),
  shelf({
    id: "sandholtz-2023",
    title: "Learning Risk Preferences in Markov Decision Processes: an Application to the Fourth Down Decision in the National Football League",
    authors: "Nathan Sandholtz, Lucas Wu, Martin Puterman, Timothy C. Y. Chan",
    year: "2023",
    venue: "arXiv:2309.00756",
    url: "https://arxiv.org/abs/2309.00756",
    abstract:
      "Coaches' fourth-down choices disagree with win-probability prescriptions. This paper fits a risk preference inside a Markov decision process so the disagreement is a parameter, not a moral. Found by the Alexandria research index.",
    verdict: "admit",
    grain: "decision",
    join: "none — a preference, not a feature",
    law: "03",
    lane: "fourth",
    equation: "A risk-sensitive value, not argmax of win probability.",
    why: "Admitted because it explains a gap between WP-max and observed calls without turning the gap into a pick. It does not replace the shipped estimator.",
  }),
  shelf({
    id: "lock-2014",
    title: "Using Random Forests to Estimate Win Probability Before Each Play of an NFL Game",
    authors: "Dennis Lock, Dan Nettleton",
    year: "2014",
    venue: "JQAS 10(2)",
    url: "https://doi.org/10.1515/jqas-2013-0100",
    abstract:
      "Random-forest win probability from score, time, field position, down and distance, timeouts, and the pre-game spread, trained on 2001–2012 plays. The ancestor of win-probability-max.",
    verdict: "hold",
    grain: "play",
    join: "game state, not gsis_id",
    law: "03",
    lane: "fourth",
    equation: null,
    why: "The shipped comparator is win-probability-max. Another point-estimate WP model is the baseline, not new feed.",
  }),
  shelf({
    id: "romer-2006",
    title: "Do Firms Maximize? Evidence from Professional Football",
    authors: "David Romer",
    year: "2006",
    venue: "Journal of Political Economy 114(2)",
    url: "https://doi.org/10.1086/501171",
    abstract:
      "A dynamic program for the fourth-down choice between kicking and going, scored on the chance of winning. Teams kick too often, by a wide margin. This is the ancestor of the literature. It is not the shipped estimator, and it is not the source of the +6.77 figure.",
    verdict: "hold",
    grain: "decision",
    join: "none",
    law: "03",
    lane: "fourth",
    equation: "Value of going versus kicking from a dynamic program aimed at the chance of winning.",
    why: "History, held on purpose. The closed record compares against modern win-probability-max, not against this 2006 program.",
  }),
  shelf({
    id: "yurko-2019",
    title: "nflWAR: A Reproducible Method for Offensive Player Evaluation in Football",
    authors: "Ronald Yurko, Samuel Ventura, Maksim Horowitz",
    year: "2019",
    venue: "JQAS",
    url: "https://doi.org/10.1515/jqas-2018-0010",
    abstract:
      "Multinomial expected-points model on public play-by-play. The state-value layer underneath modern win probability. Play-by-play still has no offensive-line injury fields and no time-to-throw.",
    verdict: "hold",
    grain: "play",
    join: "play state",
    law: "02",
    lane: "fourth",
    equation: null,
    why: "Background for the state value. It does not supply the two missing columns.",
  }),
  shelf({
    id: "nfl4th",
    title: "nfl4th — fourth-down win-probability recommendations",
    authors: "Ben Baldwin and the nflverse authors",
    year: "2020–",
    venue: "nflverse",
    url: "https://github.com/nflverse/nfl4th",
    abstract:
      "Open implementation of the fourth-down policy that picks the alternative with the highest estimated win probability. This is the family of the comparator named in the closed record. It is not the source of the +6.77 figure.",
    verdict: "hold",
    grain: "decision",
    join: "play state",
    law: "03",
    lane: "fourth",
    equation: "a* = argmax over {go, field goal, punt} of WP(state, a)",
    why: "Name the baseline precisely. Do not treat the package as the shipped estimator.",
  }),
  shelf({
    id: "gneiting-2007",
    title: "Strictly Proper Scoring Rules, Prediction, and Estimation",
    authors: "Tilmann Gneiting, Adrian E. Raftery",
    year: "2007",
    venue: "JASA 102(477)",
    url: "https://doi.org/10.1198/016214506000001437",
    abstract:
      "A scoring rule is strictly proper when the forecaster's expected score is uniquely maximized by reporting their true distribution. Brier and the logarithmic score are strictly proper for a binary event. Propriety is what makes the 306-drive Brier a legal report.",
    verdict: "admit",
    grain: "theory",
    join: "none — score, not a feature",
    law: "04",
    lane: "calibration",
    equation: "BS = (1/n) Σ (p_i − y_i)²",
    why: "Local CPU owns Brier. This is the reason that number is the right one to own.",
  }),
  shelf({
    id: "gneiting-sharp",
    title: "Probabilistic Forecasts, Calibration and Sharpness",
    authors: "Tilmann Gneiting, Fadoua Balabdaoui, Adrian E. Raftery",
    year: "2007",
    venue: "JRSS-B 69",
    url: "https://doi.org/10.1111/j.1467-9868.2007.00587.x",
    abstract:
      "Maximize sharpness subject to calibration. A sharp forecast that is not calibrated is not a better forecast. The paradigm the CPU bench is allowed to optimize.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "04",
    lane: "calibration",
    equation: null,
    why: "Admitted as the objective on the scoring side. It does not outrank the decision comparison, and it does not justify a pick.",
  }),
  shelf({
    id: "niculescu-2005",
    title: "Predicting Good Probabilities with Supervised Learning",
    authors: "Alexandru Niculescu-Mizil, Rich Caruana",
    year: "2005",
    venue: "ICML",
    url: "https://www.cs.cornell.edu/~alexn/papers/calibration.icml05.crc.rev3.pdf",
    abstract:
      "Platt scaling versus isotonic regression for turning scores into probabilities. Isotonic is more flexible and overfits small calibration sets. Three hundred six drives is a small calibration set.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "04",
    lane: "calibration",
    equation: "Pool adjacent violators until the map is monotone.",
    why: "CPU may fit isotonic. It may not fit it on a pile this small without a Brier check.",
  }),
  shelf({
    id: "kull-2017",
    title: "Beta Calibration: A Well-Founded and Easily Implemented Improvement on Logistic Calibration",
    authors: "Meelis Kull, Telmo Silva Filho, Peter Flach",
    year: "2017",
    venue: "AISTATS, PMLR 54",
    url: "https://proceedings.mlr.press/v54/kull17a.html",
    abstract:
      "A three-parameter map from the beta likelihood, strictly better-founded than Platt when the score is already a probability. A candidate the CPU may try against isotonic. It does not get a free pass onto the 0.1621.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "04",
    lane: "calibration",
    equation: "The three-parameter beta family of Kull, Silva Filho, and Flach. Fit on a calibration split; keep it only if the 306-drive Brier does not rise.",
    why: "Admitted as an alternative calibrator. The holdout Brier is the referee.",
  }),
  shelf({
    id: "kumar-2019",
    title: "Verified Uncertainty Calibration",
    authors: "Ananya Kumar, Percy Liang, Tengyu Ma",
    year: "2019",
    venue: "NeurIPS",
    url: "https://arxiv.org/abs/1909.10155",
    abstract:
      "Expected calibration error is a biased, optimizable-in-sample diagnostic. A prettier reliability diagram is not evidence. Do not steer the estimator by ECE.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "04",
    lane: "calibration",
    equation: null,
    why: "Admitted as a ban. Brier stays. ECE does not become a target.",
  }),
  shelf({
    id: "manokhin-2026",
    title: "Classifier Calibration at Scale: An Empirical Study of Model-Agnostic Post-Hoc Methods",
    authors: "Valery Manokhin, Daniel Grønhaug",
    year: "2026",
    venue: "arXiv:2601.19944",
    url: "https://arxiv.org/abs/2601.19944",
    abstract:
      "On real tabular tasks, isotonic regression and Platt scaling can systematically degrade log-loss and Brier for strong models. Venn-Abers and beta calibration degrade less often. No method dominates.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "04",
    lane: "calibration",
    equation: null,
    why: "The brake on law 04. Owning isotonic is not permission to apply it. Recompute Brier on the 306 drives first.",
  }),
  shelf({
    id: "bensimon-2026",
    title: "Isotonic Conformal Prediction",
    authors: "Daniel Bensimon, Sean Xiang Yu, Eric D. Kolaczyk, Archer Y. Yang",
    year: "2026",
    venue: "arXiv:2607.16675",
    url: "https://arxiv.org/abs/2607.16675",
    abstract:
      "A point forecast calibrated on average can still be biased conditional on its own value. Split and transductive isotonic conformal procedures target that conditional validity without refitting the calibrator for every candidate outcome.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "03",
    lane: "calibration",
    equation: null,
    why: "This is Brill's humility in the language of conformal prediction. Admitted. Not a pick, and not a GPU job.",
  }),
  shelf({
    id: "elmachtoub-2022",
    title: "Smart Predict, then Optimize",
    authors: "Adam N. Elmachtoub, Paul Grigas",
    year: "2022",
    venue: "Management Science 68(1)",
    url: "https://doi.org/10.1287/mnsc.2020.3922",
    abstract:
      "Train the prediction model for downstream decision cost, not for prediction error alone. The SPO+ surrogate is convex where the true decision regret is not differentiable.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "03",
    lane: "decision",
    equation: "regret = c(x, y, w*(θ̂)) − c(x, y, w*(θ))",
    why: "Explains how a model can beat win-probability-max on decisions and still be judged by Brier on a different slice. The shipped objective is not in the record. Do not pretend this is it. No fourth job.",
  }),
  shelf({
    id: "mandi-2024",
    title: "Decision-Focused Learning: Foundations, State of the Art, Benchmark and Future Opportunities",
    authors: "Jayanta Mandi, James Kotary, Senne Berden, Maxime Mulamba, Victor Bucarey, Tias Guns, Ferdinando Fioretto",
    year: "2024",
    venue: "JAIR 81",
    url: "https://arxiv.org/abs/2307.13565",
    abstract:
      "Survey and benchmark of gradient-based and gradient-free decision-focused learning. Eleven methods, seven problems. The state of the art for training against a decision, not against a proxy loss.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "05",
    lane: "decision",
    equation: null,
    why: "The reading list for anyone who wants the decision metric to be the training metric. It is not a license to rent an H100 or to launch a fourth training job.",
  }),
  shelf({
    id: "shin-1992",
    title: "Prices of State Contingent Claims with Insider Traders, and the Favourite-Longshot Bias",
    authors: "Hyun Song Shin",
    year: "1992",
    venue: "The Economic Journal 102(411)",
    url: "https://doi.org/10.2307/2234526",
    abstract:
      "The insider-trading model behind the Shin de-vig. Proportional removal of the margin is the crude method and is biased when favourites and longshots are not bet equally.",
    verdict: "admit",
    grain: "market",
    join: "a two-timestamp odds tape, which the record does not yet have",
    law: "05",
    lane: "market",
    equation: "De-vig by solving Shin's insider share. Proportional de-vig is labeled crude.",
    why: "Admitted as the de-vig the closing-line column should use. The CPU routine is not sealed in this console: a wrong de-vig is a filled null. The 200-row gate stays shut.",
  }),
  shelf({
    id: "robinson-1950",
    title: "Ecological Correlations and the Behavior of Individuals",
    authors: "W. S. Robinson",
    year: "1950",
    venue: "American Sociological Review 15(3)",
    url: "https://doi.org/10.2307/2087176",
    abstract:
      "A correlation at the group level need not hold at the individual level. The original statement of the grain error.",
    verdict: "admit",
    grain: "theory",
    join: "none",
    law: "02",
    lane: "support",
    equation: null,
    why: "The reason a weekly offensive-line report cannot be written into a play-level time-to-throw. Old, and not optional.",
  }),
  shelf({
    id: "rubin-1976",
    title: "Inference and Missing Data",
    authors: "Donald B. Rubin",
    year: "1976",
    venue: "Biometrika 63(3)",
    url: "https://doi.org/10.1093/biomet/63.3.581",
    abstract:
      "Missingness mechanisms. The operator law is stricter than an imputation under MAR: in this file, a missing offensive-line row is not given a value at all.",
    verdict: "admit",
    grain: "theory",
    join: "the missingness indicator itself",
    law: "01",
    lane: "support",
    equation: "If the join misses: the cell is NULL. It is not drawn.",
    why: "Language for Pittsburgh week 4. Zero offensive-line rows is a recorded null. Rubin is admitted so nobody 'helps' by imputing healthy.",
  }),
  shelf({
    id: "injuries-file",
    title: "nflverse injuries release — injuries_2026.csv.gz",
    authors: "nflverse, via nflapi injury and practice reports",
    year: "2026",
    venue: "GitHub release: injuries",
    url: "https://github.com/nflverse/nflverse-data/releases/tag/injuries",
    abstract:
      "Keyed by gsis_id, team, and week, with report status and practice status. Recounted 4 Oct 2026: 1,052 rows, weeks 1–4, week 4 has 318 rows, 41 offensive-line rows (C, G, T), 15 of them Out. Cleveland week 4 cites two Out linemen. Pittsburgh week 4 cites zero. 2025 file: 6,068 rows, 1,086 offensive-line rows. The closed record said this provider did not exist. It does.",
    verdict: "admit",
    grain: "week",
    join: "gsis_id × team × week, starters from rosters",
    law: "01",
    lane: "injury",
    equation: "left join roster starters onto injuries; a miss stays NULL",
    why: "This is the feature join. Play-by-play still has no offensive-line injury fields. Do not invent them there.",
  }),
  shelf({
    id: "ngs-combined",
    title: "nflverse combined Next Gen Stats passing — ngs_passing.csv.gz",
    authors: "NFL Next Gen Stats, packaged by nflverse",
    year: "2016–2026",
    venue: "GitHub release: nextgen_stats",
    url: "https://github.com/nflverse/nflverse-data/releases/tag/nextgen_stats",
    abstract:
      "Player-week rows, plus week 0 as the season aggregate. Column avg_time_to_throw is a mean. The file also carries player_gsis_id, so the injury join key is already on this table. Recounted 4 Oct 2026: 596,642 bytes, touched 12:58 UTC. Watson 2026 week 0 is 2.794 on 115 attempts. Week 4 of the passing table contains two passers, not a league.",
    verdict: "hold",
    grain: "week, and season at week 0",
    join: "player_gsis_id × week — a prior, not a play",
    law: "02",
    lane: "injury",
    equation: "T_play = NULL;  T_prior = avg_time_to_throw at a named grain",
    why: "Legal as a prior with an error bar. Illegal as a snap. The closed record's 2.79 is this season mean rounded. Other columns (CPOE, aggressiveness, air yards) are not admitted features.",
  }),
  shelf({
    id: "ngs-stub",
    title: "ngs_2024_passing.csv.gz",
    authors: "nflverse release asset",
    year: "2024",
    venue: "nextgen_stats",
    url: "https://github.com/nflverse/nflverse-data/releases/download/nextgen_stats/ngs_2024_passing.csv.gz",
    abstract: "616 bytes on the release. A stub. The closed record forbids it. Use the combined ngs_passing file.",
    verdict: "reject",
    grain: "none",
    join: "do not join",
    law: "02",
    lane: "injury",
    equation: null,
    why: "Do not use it. Confirmed 616 bytes on the GitHub asset.",
  }),
  shelf({
    id: "bdb-2026",
    title: "NFL Big Data Bowl 2026 — Prediction",
    authors: "NFL Next Gen Stats via Kaggle",
    year: "2025–2026",
    venue: "Kaggle competition",
    url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2026-prediction",
    abstract:
      "Tracking at 10 frames per second, stopped at the throw, with the task of predicting movement while the ball is in the air. On historical competition plays, release time is a frame difference. The key is game_id and play_id, not the 2026 public season grain.",
    verdict: "hold",
    grain: "play, historical competition seasons",
    join: "game_id + play_id — not the live Gate 3 key",
    law: "02",
    lane: "kaggle",
    equation: null,
    why: "The right shape of a play-level time-to-throw, on the wrong population. It may inform the prior's shape. It may not fill Watson's snap.",
  }),
  shelf({
    id: "bdb-2024",
    title: "NFL Big Data Bowl 2024 — tackling",
    authors: "NFL / Kaggle",
    year: "2023–2024",
    venue: "Kaggle competition",
    url: "https://www.kaggle.com/competitions/nfl-big-data-bowl-2024",
    abstract:
      "Tracking through the tackle, with a missed-tackle flag from PFF. Pressure and finishing exist here as events. They are not the official injury report and they are not avg_time_to_throw.",
    verdict: "hold",
    grain: "play, historical",
    join: "game_id + play_id",
    law: "02",
    lane: "kaggle",
    equation: null,
    why: "Hold as context for what a play-level pressure measurement looks like. Not a substitute for the injury join.",
  }),
  shelf({
    id: "schedules-spread",
    title: "nflverse schedules — a single spread_line",
    authors: "Lee Sharpe's nfldata, via nflverse",
    year: "ongoing",
    venue: "GitHub release: schedules",
    url: "https://github.com/nflverse/nflverse-data/releases/tag/schedules",
    abstract:
      "Game rows with a spread and moneylines. One number per game is not a bet-time price and a close. Closing-line value needs both timestamps, then a de-vig, then a settled result.",
    verdict: "reject",
    grain: "game",
    join: "game_id, but the wrong shape",
    law: "05",
    lane: "market",
    equation: null,
    why: "Cannot fill the closing-line column. Using it as CLV would invent the second timestamp. The rented card stays off.",
  }),
];
