import Link from "next/link";

export function Shell({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) {
  return <main className="min-h-screen bg-carbon px-6 py-10 text-ion"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs uppercase tracking-[0.2em] text-orbital-cyan">{eyebrow ?? "StatKing"}</p><h1 className="mt-2 text-4xl font-bold text-ion-white">{title}</h1><div className="mt-8 space-y-8">{children}</div></div></main>;
}
export function Cards({ items }: { items: Array<{label:string; value:string|number; note?:string}> }) { return <div className="grid gap-4 md:grid-cols-4">{items.map(i=><div key={i.label} className="border border-mineral bg-eclipse p-4"><p className="text-xs uppercase tracking-wide text-ion-2">{i.label}</p><p className="mt-2 text-3xl font-semibold text-ion-white">{i.value}</p>{i.note?<p className="mt-2 text-sm text-ion-1">{i.note}</p>:null}</div>)}</div>; }
export function Badge({ children, tone="neutral" }: { children: React.ReactNode; tone?: "good"|"warn"|"bad"|"neutral" }) { const c={good:"border-orbital-cyan text-orbital-cyan",warn:"border-amber-300 text-amber-300",bad:"border-alert text-alert",neutral:"border-mineral text-ion-1"}[tone]; return <span className={`inline-flex rounded border px-2 py-1 text-xs ${c}`}>{children}</span>; }
export function PlayerTable({ players }: { players: Array<any> }) { return <div className="overflow-x-auto border border-mineral"><table className="w-full text-left text-sm"><thead className="bg-eclipse text-xs uppercase text-ion-2"><tr><th className="p-3">Player</th><th>Team</th><th>Pos</th><th>GPI</th><th>Usage</th><th>Eff</th><th>Fantasy</th><th>Vol</th><th>Confidence</th></tr></thead><tbody>{players.map(p=><tr key={p.player_id} className="border-t border-mineral"><td className="p-3 text-ion-white"><Link href={`/stats/player/${p.player_id}`}>{p.name}</Link></td><td>{p.team}</td><td>{p.position}</td><td>{p.galaxy_player_index}</td><td>{p.usage_score}</td><td>{p.efficiency_score}</td><td>{p.fantasy_edge}</td><td>{p.volatility_score}</td><td>{p.data_confidence}%</td></tr>)}</tbody></table></div>; }
export function SimpleTable({ rows }: { rows: Array<Record<string, any>> }) { const keys=Object.keys(rows[0]??{}).slice(0,8); return <div className="overflow-x-auto border border-mineral"><table className="w-full text-left text-sm"><thead className="bg-eclipse text-xs uppercase text-ion-2"><tr>{keys.map(k=><th key={k} className="p-3">{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t border-mineral">{keys.map(k=><td key={k} className="p-3">{Array.isArray(r[k])?r[k].join(", "):String(r[k])}</td>)}</tr>)}</tbody></table></div>; }
