/**
 * Codebase Twin v0 — committed evidence table (docs/genesis/FIRST_BUILD_CONTRACT.md
 * §8.2, cross-checked against docs/genesis/CODEBASE_TWIN_SPEC.md §12's v0
 * boundary: "packages and modules; relevant capabilities; model
 * routes/providers; source rights gates; feature flags; guardrails; tests;
 * docs claims; PR #124, #112 and #52 asset summaries when available").
 *
 * Every entry cites exact repo-relative paths/symbols verified in-tree during
 * the 2026-07-17 GG-000/GX-000 sessions (see docs/frontier/GENESIS_CONVERGENCE_MAP.md
 * §2 for the full narrative). Capability state is asserted from that
 * evidence, never an optimistic default. No process environment values are
 * read anywhere in this file (twin test 5 enforces it via source scan) —
 * only repo-relative paths, symbol names, and PR/branch shas.
 */

import type { GenesisCapability } from "./contracts";

const VERIFIED_AT = "2026-07-17T00:00:00.000Z";

export const REPO_EVIDENCE: readonly GenesisCapability[] = [
  {
    id: "claude-direct-generation",
    version: "main@0e56c477",
    kind: "MODEL",
    purpose: "The one approved Anthropic Messages API dispatch point.",
    owner: "apps/web/lib/claude-api",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "ClaudeMessagesRequest" }],
    outputs: [{ name: "ClaudeMessagesResult" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.02, estimatedLatencyMs: 2000 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.02, latencyMsP50: 2000 },
    tests: ["apps/web/__tests__/claude-api-messages.test.ts"],
    provenance: {
      evidence: [
        "apps/web/lib/claude-api/messages.ts (callClaudeMessages)",
        "scripts/guardrails/claude-api-usage.mjs (WHITELIST_FILES enforcement)",
      ],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "claude-bedrock-provider",
    version: "main@0e56c477",
    kind: "MODEL",
    purpose: "Bedrock-routed Claude generation (AWS credit lane).",
    owner: "apps/web/lib/claude-api/providers",
    implementationState: "IMPLEMENTED_PURE",
    inputs: [{ name: "ClaudeMessagesRequest" }],
    outputs: [{ name: "ClaudeMessagesResult" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.015, estimatedLatencyMs: 2500 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.015, latencyMsP50: 2500 },
    tests: ["apps/web/lib/claude-api/providers/bedrock.test.ts", "apps/web/lib/claude-api/providers/aws-sigv4.test.ts"],
    provenance: {
      evidence: ["apps/web/lib/claude-api/providers/bedrock.ts (callBedrockClaudeMessages, isBedrockProviderSelected)"],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "claude-vertex-provider",
    version: "main@0e56c477",
    kind: "MODEL",
    purpose: "Vertex-routed Claude generation (GCP partner-credit lane).",
    owner: "apps/web/lib/claude-api/providers",
    implementationState: "IMPLEMENTED_PURE",
    inputs: [{ name: "ClaudeMessagesRequest" }],
    outputs: [{ name: "ClaudeMessagesResult" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.015, estimatedLatencyMs: 2500 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.015, latencyMsP50: 2500 },
    tests: ["apps/web/lib/claude-api/providers/vertex.test.ts", "apps/web/lib/claude-api/providers/google-oauth.test.ts"],
    provenance: {
      evidence: ["apps/web/lib/claude-api/providers/vertex.ts (callVertexClaudeMessages, isVertexProviderSelected)"],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "cerebras-free-lane",
    version: "main@0e56c477",
    kind: "MODEL",
    purpose: "Cerebras free lane for the brief surface — implemented but not wired to a live call site.",
    owner: "apps/web/lib/claude-api",
    implementationState: "IMPLEMENTED_PURE",
    inputs: [{ name: "ClaudeMessagesRequest" }],
    outputs: [{ name: "ClaudeMessagesResult" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.001, estimatedLatencyMs: 900 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.001, latencyMsP50: 900 },
    tests: ["apps/web/__tests__/claude-api-cerebras.test.ts", "apps/web/__tests__/claude-api-free-lane.test.ts"],
    provenance: {
      evidence: [
        "apps/web/lib/claude-api/providers/cerebras.ts (callCerebrasMessages)",
        "apps/web/lib/claude-api/free-lane.ts (shouldUseFreeLane, FREE_LANE_SURFACES={\"brief\"}; generateContentMessages referenced only by its test)",
      ],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "model-router-surface-tier",
    version: "main@0e56c477",
    kind: "TRANSFORM",
    purpose: "Deterministic surface-to-model-tier routing table.",
    owner: "apps/web/lib/claude-api",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "ClaudeSurface" }],
    outputs: [{ name: "ModelId" }],
    executionProfiles: [{ placement: "LOCAL_SERVER", estimatedCostUsd: 0, estimatedLatencyMs: 1 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 1 },
    tests: ["apps/web/__tests__/model-router.test.ts"],
    provenance: { evidence: ["apps/web/lib/claude-api/model-router.ts (pickModelForSurface, SURFACE_TIER, MODELS)"], verifiedAt: VERIFIED_AT },
  },
  {
    id: "provider-dispatcher",
    version: "main@0e56c477",
    kind: "TRANSFORM",
    purpose: "Routes to Bedrock/Vertex/direct Anthropic with automatic fallback; wired into all 7 generation surfaces.",
    owner: "apps/web/lib/claude-api",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "ClaudeMessagesRequest" }],
    outputs: [{ name: "ClaudeMessagesResult" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.02, estimatedLatencyMs: 2200 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.02, latencyMsP50: 2200 },
    tests: ["apps/web/lib/claude-api/provider-dispatch.test.ts"],
    provenance: { evidence: ["apps/web/lib/claude-api/provider-dispatch.ts (callClaude)"], verifiedAt: VERIFIED_AT },
  },
  {
    id: "model-economics-and-spend-governance",
    version: "main@0e56c477",
    kind: "TRANSFORM",
    purpose: "Cost estimation, budget tiers (green to hard_cap), spend tracking, and a default-BLOCK paid-op governor.",
    owner: "apps/web/lib/claude-api + apps/web/lib/cost",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "ClaudeSurface" }],
    outputs: [{ name: "BudgetDecision" }],
    executionProfiles: [{ placement: "LOCAL_SERVER", estimatedCostUsd: 0, estimatedLatencyMs: 5 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 5 },
    tests: ["apps/web/__tests__/cost-governor.test.ts", "apps/web/__tests__/claude-api-dashboard.test.ts"],
    provenance: {
      evidence: [
        "apps/web/lib/claude-api/cost-monitor.ts (evaluateClaudeBudgetUsage)",
        "apps/web/lib/claude-api/credit-pool.ts (aws_activate|vertex_partner|anthropic_direct)",
        "apps/web/lib/cost/cost-governor.ts (requirePaidOperation, default-BLOCK)",
      ],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "source-clearance-and-rights",
    version: "main@0e56c477",
    kind: "SOURCE",
    purpose: "The canonical rights-gate every extraction job must pass; throws unless allowed.",
    owner: "apps/web/lib/scraping",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "ClearanceRequest" }],
    outputs: [{ name: "ClearanceResult" }],
    executionProfiles: [{ placement: "LOCAL_SERVER", estimatedCostUsd: 0, estimatedLatencyMs: 5 }],
    policy: { requiresClearance: true, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 5 },
    tests: ["apps/web/__tests__/scraping-clearance.test.ts"],
    provenance: {
      evidence: [
        "apps/web/lib/scraping/clearance-engine.ts (checkClearance, wrapExtractedRecord)",
        "apps/web/lib/scraping/source-rights-registry.ts (9-status vocabulary)",
      ],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "deterministic-proof-of-record",
    version: "main@0e56c477 (#120)",
    kind: "PROOF",
    purpose: "Hash-chained, Merkle-committed pick proof — the reference deterministic evidence capability.",
    owner: "packages/prediction-engine",
    implementationState: "LIVE_PUBLIC",
    inputs: [{ name: "PickRecord" }],
    outputs: [{ name: "MerkleProof" }],
    executionProfiles: [{ placement: "LOCAL_SERVER", estimatedCostUsd: 0, estimatedLatencyMs: 1 }],
    policy: { requiresClearance: false, publicationBoundary: "PUBLIC", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 1 },
    tests: ["packages/prediction-engine/src/__tests__/proof-of-record.test.ts"],
    provenance: { evidence: ["packages/prediction-engine/src/proof-of-record.ts (hashLeaf, merkleRoot, canonicalPickPayload)"], verifiedAt: VERIFIED_AT },
  },
  {
    id: "draft-only-human-review-boundary",
    version: "main@0e56c477",
    kind: "HUMAN_REVIEW",
    purpose: "CI-enforced boundary: AI-generated content can never auto-publish or auto-send.",
    owner: "scripts/guardrails",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "RepositorySourceTree" }],
    outputs: [{ name: "GuardrailVerdict" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0, estimatedLatencyMs: 3000 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 3000 },
    uncertaintyEffect: { reducesUncertainty: false, note: "Publication-boundary enforcement, not an uncertainty reduction." },
    tests: [],
    provenance: { evidence: ["scripts/guardrails/draft-only.mjs"], verifiedAt: VERIFIED_AT },
  },
  {
    id: "agent-foundry-resource-radar-shadow-router",
    version: "PR #124 @ a7b38043",
    kind: "AGENT",
    purpose: "Agent Foundry manifests, Assurance reports, Resource Radar, and a shadow-only AI Model Portfolio Router.",
    owner: "STRANDED — provenance only, never imported",
    implementationState: "STRANDED_BRANCH",
    inputs: [],
    outputs: [],
    executionProfiles: [],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0, latencyMsP50: 0 },
    tests: [],
    provenance: {
      evidence: [
        "PR #124 (claude/frontier-superset-rebased @ a7b38043), base e9fab35d, open, NOT on main",
        "local branch claude/frontier-model-router-shadow-2026-07-11 (AI_MODEL_ROUTER_SHADOW_ENABLED default off)",
      ],
      verifiedAt: VERIFIED_AT,
    },
  },
  {
    id: "promptfoo-parity-gate-and-eval-contracts",
    version: "main@0e56c477",
    kind: "PROOF",
    purpose: "Model-downgrade parity evaluation gate plus the markdown eval-contract validator (last step of the guardrails chain).",
    owner: "eval/promptfoo + scripts",
    implementationState: "LIVE_INTERNAL",
    inputs: [{ name: "EvalCase" }],
    outputs: [{ name: "EvalVerdict" }],
    executionProfiles: [{ placement: "CLOUD_JOB", estimatedCostUsd: 0.01, estimatedLatencyMs: 5000 }],
    policy: { requiresClearance: false, publicationBoundary: "COCKPIT_DRAFT", dataClass: "INTERNAL_NON_PERSONAL" },
    economics: { costUsdPerCall: 0.01, latencyMsP50: 5000 },
    tests: [],
    provenance: {
      evidence: ["eval/promptfoo/promptfooconfig.yaml", "scripts/eval-contracts.mjs"],
      verifiedAt: VERIFIED_AT,
    },
  },
];
