import type { ProfileWriteback, QuestDef } from "./types.js";
import { routeForDistrict } from "./world-map.js";

const writeback = (adminEvent: string, xp = 20, credits = 10): ProfileWriteback => ({
  targets: ["profile", "sports_iq_xp", "galaxy_score", "quest_state", "reward_wallet", "admin_event"],
  reason: "QUEST_REWARD",
  xp,
  credits,
  adminEvent,
});

export const QUESTS: readonly QuestDef[] = [
  {
    id: "first-signal",
    title: "First Signal",
    districtId: "academy",
    prerequisites: [],
    objectives: [
      { id: "talk-coach", label: "Talk to Coach Signal", kind: "talk", targetId: "coach-signal" },
      { id: "complete-first-check", label: "Complete the first Signal Check", kind: "signal_check", targetId: "academy-1" },
      { id: "claim-rookie-card", label: "Claim the Rookie Signal Card", kind: "inventory", targetId: "rookie-signal-card" },
    ],
    dialogueTriggers: ["coach-signal-first"],
    repeatable: "never",
    rewards: { ...writeback("rookie_plaza_first_signal_completed", 30, 15), targets: ["profile", "sports_iq_xp", "inventory", "card_state", "quest_state", "galaxy_score", "reward_wallet", "admin_event"] },
    routeTargets: [routeForDistrict("war-room"), routeForDistrict("vault")],
  },
  {
    id: "meet-the-board-scout",
    title: "Meet the Board Scout",
    districtId: "war-room",
    prerequisites: ["first-signal"],
    objectives: [{ id: "talk-board-scout", label: "Ask the Board Scout for a context route", kind: "talk", targetId: "board-scout" }],
    dialogueTriggers: ["board-scout-first"],
    repeatable: "never",
    rewards: writeback("rookie_plaza_board_scout_met"),
    routeTargets: [routeForDistrict("war-room")],
  },
  {
    id: "claim-rookie-signal-card",
    title: "Claim Rookie Signal Card",
    districtId: "vault",
    prerequisites: ["first-signal"],
    objectives: [{ id: "inspect-card", label: "Inspect the Rookie Signal Card", kind: "inventory", targetId: "rookie-signal-card" }],
    dialogueTriggers: ["vault-keeper-first"],
    repeatable: "never",
    rewards: { ...writeback("rookie_signal_card_claimed"), targets: ["profile", "inventory", "card_state", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("vault")],
  },
  {
    id: "visit-the-vault",
    title: "Visit the Vault",
    districtId: "vault",
    prerequisites: ["claim-rookie-signal-card"],
    objectives: [{ id: "route-vault", label: "Use the Vault entrance", kind: "route", targetId: "vault-door" }],
    dialogueTriggers: ["vault-keeper-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_vault_visit", 15, 8),
    routeTargets: [routeForDistrict("vault")],
  },
  {
    id: "join-the-crew-board",
    title: "Join the Crew Board",
    districtId: "crew-hall",
    prerequisites: ["first-signal"],
    objectives: [{ id: "talk-crew-captain", label: "Talk to the Crew Captain", kind: "talk", targetId: "crew-captain" }],
    dialogueTriggers: ["crew-captain-first"],
    repeatable: "never",
    rewards: { ...writeback("rookie_plaza_crew_board_opened"), targets: ["profile", "crew_contribution", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("crew-hall")],
  },
  {
    id: "run-the-blacktop",
    title: "Run the Blacktop",
    districtId: "blacktop",
    prerequisites: ["first-signal"],
    objectives: [{ id: "blacktop-rep", label: "Complete a Blacktop rep", kind: "signal_check", targetId: "blacktop-token" }],
    dialogueTriggers: ["blacktop-runner-first"],
    repeatable: "daily",
    rewards: { ...writeback("rookie_plaza_blacktop_rep", 25, 12), reason: "BLACKTOP_REWARD" },
    routeTargets: [routeForDistrict("blacktop")],
  },
  {
    id: "face-the-public-trap",
    title: "Face the Public Trap",
    districtId: "depths",
    prerequisites: ["first-signal"],
    objectives: [{ id: "depths-route", label: "Route to the Depths gate", kind: "boss", targetId: "public_trap" }],
    dialogueTriggers: ["depths-guard-first"],
    repeatable: "weekly",
    rewards: { ...writeback("rookie_plaza_public_trap_attempt", 35, 18), reason: "BOSS_REWARD" },
    routeTargets: [routeForDistrict("depths")],
  },
  {
    id: "check-the-season-gate",
    title: "Check the Season Gate",
    districtId: "season-gate",
    prerequisites: ["first-signal"],
    objectives: [{ id: "season-route", label: "Check the active Season route", kind: "route", targetId: "season-gate" }],
    dialogueTriggers: ["season-agent-first"],
    repeatable: "daily",
    rewards: { ...writeback("rookie_plaza_season_gate_checked"), targets: ["profile", "season_progress", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("season-gate")],
  },
  {
    id: "inspect-proof-kiosk",
    title: "Inspect Proof Kiosk",
    districtId: "war-room",
    prerequisites: ["first-signal"],
    objectives: [{ id: "proof-route", label: "Inspect the Proof Kiosk", kind: "inspect", targetId: "proof-kiosk" }],
    dialogueTriggers: ["proof-clerk-first"],
    repeatable: "daily",
    rewards: { ...writeback("rookie_plaza_proof_kiosk_inspected"), targets: ["profile", "gse_prompt_history", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("war-room")],
  },
  {
    id: "read-rookie-heat",
    title: "Read Rookie Heat",
    districtId: "academy",
    prerequisites: ["first-signal"],
    objectives: [{ id: "weather-rookie-heat", label: "Ask the Weather Analyst about Rookie Heat", kind: "talk", targetId: "weather-analyst" }],
    dialogueTriggers: ["weather-analyst-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_rookie_heat_read"),
    routeTargets: [routeForDistrict("academy"), routeForDistrict("vault")],
  },
  {
    id: "mark-injury-fog",
    title: "Mark Injury Fog",
    districtId: "war-room",
    prerequisites: ["inspect-proof-kiosk"],
    objectives: [{ id: "weather-injury-fog", label: "Mark uncertainty before a read", kind: "inspect", targetId: "weather-chip" }],
    dialogueTriggers: ["weather-analyst-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_injury_fog_marked"),
    routeTargets: [routeForDistrict("war-room"), routeForDistrict("depths")],
  },
  {
    id: "track-card-heat",
    title: "Track Card Heat",
    districtId: "vault",
    prerequisites: ["claim-rookie-signal-card"],
    objectives: [{ id: "card-heat", label: "Track a fictional card-state change", kind: "inspect", targetId: "market-compass" }],
    dialogueTriggers: ["card-scout-first"],
    repeatable: "daily",
    rewards: { ...writeback("rookie_plaza_card_heat_tracked"), targets: ["profile", "card_state", "watchlist", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("vault")],
  },
  {
    id: "check-market-whiplash",
    title: "Check Market Whiplash",
    districtId: "war-room",
    prerequisites: ["meet-the-board-scout"],
    objectives: [{ id: "market-map", label: "Map a movement reason", kind: "inspect", targetId: "market-mapper" }],
    dialogueTriggers: ["market-mapper-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_market_whiplash_checked"),
    routeTargets: [routeForDistrict("war-room")],
  },
  {
    id: "learn-proof-stamp",
    title: "Learn Proof Stamp",
    districtId: "war-room",
    prerequisites: ["inspect-proof-kiosk"],
    objectives: [{ id: "proof-stamp", label: "Claim the Proof Stamp lesson", kind: "inventory", targetId: "proof-stamp" }],
    dialogueTriggers: ["proof-clerk-first"],
    repeatable: "never",
    rewards: { ...writeback("rookie_plaza_proof_stamp_learned"), targets: ["profile", "inventory", "gse_prompt_history", "quest_state", "admin_event"] },
    routeTargets: [routeForDistrict("war-room")],
  },
  {
    id: "visit-calibration-kiosk",
    title: "Visit Calibration Kiosk",
    districtId: "academy",
    prerequisites: ["first-signal"],
    objectives: [{ id: "calibration-chip", label: "Review confidence feedback", kind: "inspect", targetId: "calibration-chip" }],
    dialogueTriggers: ["coach-signal-weather"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_calibration_kiosk_visited"),
    routeTargets: [routeForDistrict("academy")],
  },
  {
    id: "find-ghost-rival",
    title: "Find Ghost Rival",
    districtId: "proving-grounds",
    prerequisites: ["first-signal"],
    objectives: [{ id: "talk-ghost-rival", label: "Find the Ghost Rival path", kind: "talk", targetId: "ghost-rival" }],
    dialogueTriggers: ["ghost-rival-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_ghost_rival_found"),
    routeTargets: [routeForDistrict("proving-grounds")],
  },
  {
    id: "choose-crew-role",
    title: "Choose Crew Role",
    districtId: "crew-hall",
    prerequisites: ["join-the-crew-board"],
    objectives: [{ id: "crew-role", label: "Pick a crew contribution lane", kind: "crew", targetId: "crew-signal-pin" }],
    dialogueTriggers: ["crew-captain-first"],
    repeatable: "weekly",
    rewards: { ...writeback("rookie_plaza_crew_role_chosen"), targets: ["profile", "crew_contribution", "quest_state", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("crew-hall")],
  },
  {
    id: "scout-opportunity",
    title: "Scout Opportunity",
    districtId: "academy",
    prerequisites: ["meet-the-board-scout"],
    objectives: [{ id: "scout-lens", label: "Use the Scout Lens on a generic role change", kind: "inspect", targetId: "scout-lens" }],
    dialogueTriggers: ["board-scout-first"],
    repeatable: "daily",
    rewards: writeback("rookie_plaza_opportunity_scouted"),
    routeTargets: [routeForDistrict("academy"), routeForDistrict("vault")],
  },
  {
    id: "open-daily-route",
    title: "Open Daily Route",
    districtId: "stadium-gates",
    prerequisites: ["first-signal"],
    objectives: [{ id: "daily-route", label: "Open today's Campus route", kind: "route", targetId: "route-map" }],
    dialogueTriggers: ["transit-operator-first"],
    repeatable: "daily",
    rewards: { ...writeback("rookie_plaza_daily_route_opened"), targets: ["profile", "season_progress", "quest_state", "admin_event"] },
    routeTargets: [routeForDistrict("stadium-gates")],
  },
  {
    id: "complete-rookie-loop",
    title: "Complete Rookie Loop",
    districtId: "my-dynasty",
    prerequisites: ["first-signal", "inspect-proof-kiosk", "visit-the-vault"],
    objectives: [{ id: "return-dynasty", label: "Return to My Dynasty with a first route complete", kind: "route", targetId: "my-dynasty-exit" }],
    dialogueTriggers: ["coach-signal-weather"],
    repeatable: "weekly",
    rewards: { ...writeback("rookie_plaza_loop_completed", 50, 25), targets: ["profile", "sports_iq_xp", "inventory", "quest_state", "season_progress", "galaxy_score", "admin_event"] },
    routeTargets: [routeForDistrict("my-dynasty")],
  },
];

export function getQuest(id: string): QuestDef | null {
  return QUESTS.find((quest) => quest.id === id) ?? null;
}
