/**
 * FBS conference -> team -> ESPN id map (ledger C-176, NCAA Specialist).
 *
 * Source: live ESPN core API, fetched 2026-09-09 00:0x UTC, no key, no login:
 *   https://sports.core.api.espn.com/v2/sports/football/leagues/college-football/
 *     seasons/2026/types/2/groups/80/children  (11 conferences)
 *     seasons/2026/types/2/groups/{conferenceId}/teams  (member teams per conference)
 *     seasons/2026/teams/{espnId}  (team detail: displayName, shortDisplayName,
 *     location, abbreviation, slug)
 * Same free, cleared ESPN public source apps/web/lib/data-sources/free-adapters/
 * espn-scores.ts already uses for group 80/81 boards (approved_public_logged_off,
 * facts only). 138 FBS teams across 11 conferences, verified live for the 2026 season.
 * FBS Independents is ESPN's own grouping body for programs with no conference, kept
 * here with isIndependent=true rather than a synthetic 12th conference.
 *
 * cfbdId is intentionally always null: CollegeFootballData (CFBD) ingestion is BLOCKED
 * (source-rights-registry.ts, status vendor_candidate; see
 * docs/ops/CFBD_TERMS_EVIDENCE_2026-09-08.md) and this repo holds no CFBD API key, so no
 * CFBD id can be verified today (rule 1: no fabricated data - an invented id is worse
 * than a missing one). Populate cfbdId from a live CFBD /teams call once a key is
 * approved and the adapter lands; never hand-guess it.
 *
 * Do not hand-edit team rows below; regenerate from the same live endpoints if ESPN
 * renames, relocates, or realigns a program (conference realignment happens most
 * offseasons). This file is a reference table, not the source of truth for a live
 * board - espn-scores.ts still reads scores live.
 */

export interface FbsConferenceTeam {
  /** ESPN numeric team id, e.g. "2" for Auburn. Stable across seasons. */
  readonly espnId: string;
  /** e.g. "Auburn Tigers". */
  readonly displayName: string;
  /** ESPN's own short form, e.g. "Ole Miss" for "Ole Miss Rebels", "FIU" for
   * "Florida International Panthers". The verified alias source below. */
  readonly shortDisplayName: string;
  /** e.g. "Auburn". */
  readonly location: string;
  /** e.g. "Tigers". */
  readonly name: string;
  /** e.g. "AUB". */
  readonly abbreviation: string;
  /** e.g. "auburn-tigers". */
  readonly slug: string;
  /** ESPN group id for the team's conference, e.g. "8" for the SEC. */
  readonly conferenceId: string;
  /** e.g. "Southeastern Conference". */
  readonly conferenceName: string;
  /** e.g. "SEC". */
  readonly conferenceShortName: string;
  /** True only for the "FBS Independents" body (not a real conference). */
  readonly isIndependent: boolean;
  /**
   * CollegeFootballData team id. Always null today - see file header. Never fabricate
   * this value; a wrong id silently mis-joins a game to the wrong program.
   */
  readonly cfbdId: string | null;
}

export const FBS_CONFERENCE_TEAMS: readonly FbsConferenceTeam[] = [
  {
    espnId: "349",
    displayName: "Army Black Knights",
    shortDisplayName: "Army",
    location: "Army",
    name: "Black Knights",
    abbreviation: "ARMY",
    slug: "army-black-knights",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2429",
    displayName: "Charlotte 49ers",
    shortDisplayName: "Charlotte",
    location: "Charlotte",
    name: "49ers",
    abbreviation: "CLT",
    slug: "charlotte-49ers",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "151",
    displayName: "East Carolina Pirates",
    shortDisplayName: "East Carolina",
    location: "East Carolina",
    name: "Pirates",
    abbreviation: "ECU",
    slug: "east-carolina-pirates",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2226",
    displayName: "Florida Atlantic Owls",
    shortDisplayName: "FAU",
    location: "Florida Atlantic",
    name: "Owls",
    abbreviation: "FAU",
    slug: "florida-atlantic-owls",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "235",
    displayName: "Memphis Tigers",
    shortDisplayName: "Memphis",
    location: "Memphis",
    name: "Tigers",
    abbreviation: "MEM",
    slug: "memphis-tigers",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2426",
    displayName: "Navy Midshipmen",
    shortDisplayName: "Navy",
    location: "Navy",
    name: "Midshipmen",
    abbreviation: "NAVY",
    slug: "navy-midshipmen",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "249",
    displayName: "North Texas Mean Green",
    shortDisplayName: "North Texas",
    location: "North Texas",
    name: "Mean Green",
    abbreviation: "UNT",
    slug: "north-texas-mean-green",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "242",
    displayName: "Rice Owls",
    shortDisplayName: "Rice",
    location: "Rice",
    name: "Owls",
    abbreviation: "RICE",
    slug: "rice-owls",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "58",
    displayName: "South Florida Bulls",
    shortDisplayName: "South Florida",
    location: "South Florida",
    name: "Bulls",
    abbreviation: "USF",
    slug: "south-florida-bulls",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "218",
    displayName: "Temple Owls",
    shortDisplayName: "Temple",
    location: "Temple",
    name: "Owls",
    abbreviation: "TEM",
    slug: "temple-owls",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2655",
    displayName: "Tulane Green Wave",
    shortDisplayName: "Tulane",
    location: "Tulane",
    name: "Green Wave",
    abbreviation: "TULN",
    slug: "tulane-green-wave",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "202",
    displayName: "Tulsa Golden Hurricane",
    shortDisplayName: "Tulsa",
    location: "Tulsa",
    name: "Golden Hurricane",
    abbreviation: "TLSA",
    slug: "tulsa-golden-hurricane",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "5",
    displayName: "UAB Blazers",
    shortDisplayName: "UAB",
    location: "UAB",
    name: "Blazers",
    abbreviation: "UAB",
    slug: "uab-blazers",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2636",
    displayName: "UTSA Roadrunners",
    shortDisplayName: "UTSA",
    location: "UTSA",
    name: "Roadrunners",
    abbreviation: "UTSA",
    slug: "utsa-roadrunners",
    conferenceId: "151",
    conferenceName: "American Conference",
    conferenceShortName: "American",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "103",
    displayName: "Boston College Eagles",
    shortDisplayName: "Boston College",
    location: "Boston College",
    name: "Eagles",
    abbreviation: "BC",
    slug: "boston-college-eagles",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "25",
    displayName: "California Golden Bears",
    shortDisplayName: "California",
    location: "California",
    name: "Golden Bears",
    abbreviation: "CAL",
    slug: "california-golden-bears",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "228",
    displayName: "Clemson Tigers",
    shortDisplayName: "Clemson",
    location: "Clemson",
    name: "Tigers",
    abbreviation: "CLEM",
    slug: "clemson-tigers",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "150",
    displayName: "Duke Blue Devils",
    shortDisplayName: "Duke",
    location: "Duke",
    name: "Blue Devils",
    abbreviation: "DUKE",
    slug: "duke-blue-devils",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "52",
    displayName: "Florida State Seminoles",
    shortDisplayName: "Florida St",
    location: "Florida State",
    name: "Seminoles",
    abbreviation: "FSU",
    slug: "florida-state-seminoles",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "59",
    displayName: "Georgia Tech Yellow Jackets",
    shortDisplayName: "Georgia Tech",
    location: "Georgia Tech",
    name: "Yellow Jackets",
    abbreviation: "GT",
    slug: "georgia-tech-yellow-jackets",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "97",
    displayName: "Louisville Cardinals",
    shortDisplayName: "Louisville",
    location: "Louisville",
    name: "Cardinals",
    abbreviation: "LOU",
    slug: "louisville-cardinals",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2390",
    displayName: "Miami Hurricanes",
    shortDisplayName: "Miami",
    location: "Miami",
    name: "Hurricanes",
    abbreviation: "MIA",
    slug: "miami-hurricanes",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "152",
    displayName: "NC State Wolfpack",
    shortDisplayName: "NC State",
    location: "NC State",
    name: "Wolfpack",
    abbreviation: "NCSU",
    slug: "nc-state-wolfpack",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "153",
    displayName: "North Carolina Tar Heels",
    shortDisplayName: "North Carolina",
    location: "North Carolina",
    name: "Tar Heels",
    abbreviation: "UNC",
    slug: "north-carolina-tar-heels",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "221",
    displayName: "Pittsburgh Panthers",
    shortDisplayName: "Pitt",
    location: "Pittsburgh",
    name: "Panthers",
    abbreviation: "PITT",
    slug: "pittsburgh-panthers",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2567",
    displayName: "SMU Mustangs",
    shortDisplayName: "SMU",
    location: "SMU",
    name: "Mustangs",
    abbreviation: "SMU",
    slug: "smu-mustangs",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "24",
    displayName: "Stanford Cardinal",
    shortDisplayName: "Stanford",
    location: "Stanford",
    name: "Cardinal",
    abbreviation: "STAN",
    slug: "stanford-cardinal",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "183",
    displayName: "Syracuse Orange",
    shortDisplayName: "Syracuse",
    location: "Syracuse",
    name: "Orange",
    abbreviation: "SYR",
    slug: "syracuse-orange",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "258",
    displayName: "Virginia Cavaliers",
    shortDisplayName: "Virginia",
    location: "Virginia",
    name: "Cavaliers",
    abbreviation: "UVA",
    slug: "virginia-cavaliers",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "259",
    displayName: "Virginia Tech Hokies",
    shortDisplayName: "Virginia Tech",
    location: "Virginia Tech",
    name: "Hokies",
    abbreviation: "VT",
    slug: "virginia-tech-hokies",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "154",
    displayName: "Wake Forest Demon Deacons",
    shortDisplayName: "Wake Forest",
    location: "Wake Forest",
    name: "Demon Deacons",
    abbreviation: "WAKE",
    slug: "wake-forest-demon-deacons",
    conferenceId: "1",
    conferenceName: "Atlantic Coast Conference",
    conferenceShortName: "ACC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "9",
    displayName: "Arizona State Sun Devils",
    shortDisplayName: "Arizona St",
    location: "Arizona State",
    name: "Sun Devils",
    abbreviation: "ASU",
    slug: "arizona-state-sun-devils",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "12",
    displayName: "Arizona Wildcats",
    shortDisplayName: "Arizona",
    location: "Arizona",
    name: "Wildcats",
    abbreviation: "ARIZ",
    slug: "arizona-wildcats",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "252",
    displayName: "BYU Cougars",
    shortDisplayName: "BYU",
    location: "BYU",
    name: "Cougars",
    abbreviation: "BYU",
    slug: "byu-cougars",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "239",
    displayName: "Baylor Bears",
    shortDisplayName: "Baylor",
    location: "Baylor",
    name: "Bears",
    abbreviation: "BAY",
    slug: "baylor-bears",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2132",
    displayName: "Cincinnati Bearcats",
    shortDisplayName: "Cincinnati",
    location: "Cincinnati",
    name: "Bearcats",
    abbreviation: "CIN",
    slug: "cincinnati-bearcats",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "38",
    displayName: "Colorado Buffaloes",
    shortDisplayName: "Colorado",
    location: "Colorado",
    name: "Buffaloes",
    abbreviation: "COLO",
    slug: "colorado-buffaloes",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "248",
    displayName: "Houston Cougars",
    shortDisplayName: "Houston",
    location: "Houston",
    name: "Cougars",
    abbreviation: "HOU",
    slug: "houston-cougars",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "66",
    displayName: "Iowa State Cyclones",
    shortDisplayName: "Iowa State",
    location: "Iowa State",
    name: "Cyclones",
    abbreviation: "ISU",
    slug: "iowa-state-cyclones",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2305",
    displayName: "Kansas Jayhawks",
    shortDisplayName: "Kansas",
    location: "Kansas",
    name: "Jayhawks",
    abbreviation: "KU",
    slug: "kansas-jayhawks",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2306",
    displayName: "Kansas State Wildcats",
    shortDisplayName: "Kansas St",
    location: "Kansas State",
    name: "Wildcats",
    abbreviation: "KSU",
    slug: "kansas-state-wildcats",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "197",
    displayName: "Oklahoma State Cowboys",
    shortDisplayName: "Oklahoma St",
    location: "Oklahoma State",
    name: "Cowboys",
    abbreviation: "OKST",
    slug: "oklahoma-state-cowboys",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2628",
    displayName: "TCU Horned Frogs",
    shortDisplayName: "TCU",
    location: "TCU",
    name: "Horned Frogs",
    abbreviation: "TCU",
    slug: "tcu-horned-frogs",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2641",
    displayName: "Texas Tech Red Raiders",
    shortDisplayName: "Texas Tech",
    location: "Texas Tech",
    name: "Red Raiders",
    abbreviation: "TTU",
    slug: "texas-tech-red-raiders",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2116",
    displayName: "UCF Knights",
    shortDisplayName: "UCF",
    location: "UCF",
    name: "Knights",
    abbreviation: "UCF",
    slug: "ucf-knights",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "254",
    displayName: "Utah Utes",
    shortDisplayName: "Utah",
    location: "Utah",
    name: "Utes",
    abbreviation: "UTAH",
    slug: "utah-utes",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "277",
    displayName: "West Virginia Mountaineers",
    shortDisplayName: "West Virginia",
    location: "West Virginia",
    name: "Mountaineers",
    abbreviation: "WVU",
    slug: "west-virginia-mountaineers",
    conferenceId: "4",
    conferenceName: "Big 12 Conference",
    conferenceShortName: "Big 12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "356",
    displayName: "Illinois Fighting Illini",
    shortDisplayName: "Illinois",
    location: "Illinois",
    name: "Fighting Illini",
    abbreviation: "ILL",
    slug: "illinois-fighting-illini",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "84",
    displayName: "Indiana Hoosiers",
    shortDisplayName: "Indiana",
    location: "Indiana",
    name: "Hoosiers",
    abbreviation: "IU",
    slug: "indiana-hoosiers",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2294",
    displayName: "Iowa Hawkeyes",
    shortDisplayName: "Iowa",
    location: "Iowa",
    name: "Hawkeyes",
    abbreviation: "IOWA",
    slug: "iowa-hawkeyes",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "120",
    displayName: "Maryland Terrapins",
    shortDisplayName: "Maryland",
    location: "Maryland",
    name: "Terrapins",
    abbreviation: "MD",
    slug: "maryland-terrapins",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "127",
    displayName: "Michigan State Spartans",
    shortDisplayName: "Michigan St",
    location: "Michigan State",
    name: "Spartans",
    abbreviation: "MSU",
    slug: "michigan-state-spartans",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "130",
    displayName: "Michigan Wolverines",
    shortDisplayName: "Michigan",
    location: "Michigan",
    name: "Wolverines",
    abbreviation: "MICH",
    slug: "michigan-wolverines",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "135",
    displayName: "Minnesota Golden Gophers",
    shortDisplayName: "Minnesota",
    location: "Minnesota",
    name: "Golden Gophers",
    abbreviation: "MINN",
    slug: "minnesota-golden-gophers",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "158",
    displayName: "Nebraska Cornhuskers",
    shortDisplayName: "Nebraska",
    location: "Nebraska",
    name: "Cornhuskers",
    abbreviation: "NEB",
    slug: "nebraska-cornhuskers",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "77",
    displayName: "Northwestern Wildcats",
    shortDisplayName: "Northwestern",
    location: "Northwestern",
    name: "Wildcats",
    abbreviation: "NU",
    slug: "northwestern-wildcats",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "194",
    displayName: "Ohio State Buckeyes",
    shortDisplayName: "Ohio State",
    location: "Ohio State",
    name: "Buckeyes",
    abbreviation: "OSU",
    slug: "ohio-state-buckeyes",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2483",
    displayName: "Oregon Ducks",
    shortDisplayName: "Oregon",
    location: "Oregon",
    name: "Ducks",
    abbreviation: "ORE",
    slug: "oregon-ducks",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "213",
    displayName: "Penn State Nittany Lions",
    shortDisplayName: "Penn State",
    location: "Penn State",
    name: "Nittany Lions",
    abbreviation: "PSU",
    slug: "penn-state-nittany-lions",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2509",
    displayName: "Purdue Boilermakers",
    shortDisplayName: "Purdue",
    location: "Purdue",
    name: "Boilermakers",
    abbreviation: "PUR",
    slug: "purdue-boilermakers",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "164",
    displayName: "Rutgers Scarlet Knights",
    shortDisplayName: "Rutgers",
    location: "Rutgers",
    name: "Scarlet Knights",
    abbreviation: "RUTG",
    slug: "rutgers-scarlet-knights",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "26",
    displayName: "UCLA Bruins",
    shortDisplayName: "UCLA",
    location: "UCLA",
    name: "Bruins",
    abbreviation: "UCLA",
    slug: "ucla-bruins",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "30",
    displayName: "USC Trojans",
    shortDisplayName: "USC",
    location: "USC",
    name: "Trojans",
    abbreviation: "USC",
    slug: "usc-trojans",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "264",
    displayName: "Washington Huskies",
    shortDisplayName: "Washington",
    location: "Washington",
    name: "Huskies",
    abbreviation: "WASH",
    slug: "washington-huskies",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "275",
    displayName: "Wisconsin Badgers",
    shortDisplayName: "Wisconsin",
    location: "Wisconsin",
    name: "Badgers",
    abbreviation: "WIS",
    slug: "wisconsin-badgers",
    conferenceId: "5",
    conferenceName: "Big Ten Conference",
    conferenceShortName: "Big Ten",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "48",
    displayName: "Delaware Blue Hens",
    shortDisplayName: "Delaware",
    location: "Delaware",
    name: "Blue Hens",
    abbreviation: "DEL",
    slug: "delaware-blue-hens",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2229",
    displayName: "Florida International Panthers",
    shortDisplayName: "FIU",
    location: "Florida International",
    name: "Panthers",
    abbreviation: "FIU",
    slug: "florida-international-panthers",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "55",
    displayName: "Jacksonville State Gamecocks",
    shortDisplayName: "Jax State",
    location: "Jacksonville State",
    name: "Gamecocks",
    abbreviation: "JVST",
    slug: "jacksonville-state-gamecocks",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "338",
    displayName: "Kennesaw State Owls",
    shortDisplayName: "Kennesaw St",
    location: "Kennesaw State",
    name: "Owls",
    abbreviation: "KENN",
    slug: "kennesaw-state-owls",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2335",
    displayName: "Liberty Flames",
    shortDisplayName: "Liberty",
    location: "Liberty",
    name: "Flames",
    abbreviation: "LIB",
    slug: "liberty-flames",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2393",
    displayName: "Middle Tennessee Blue Raiders",
    shortDisplayName: "MTSU",
    location: "Middle Tennessee",
    name: "Blue Raiders",
    abbreviation: "MTSU",
    slug: "middle-tennessee-blue-raiders",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2623",
    displayName: "Missouri State Bears",
    shortDisplayName: "Missouri St",
    location: "Missouri State",
    name: "Bears",
    abbreviation: "MOST",
    slug: "missouri-state-bears",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "166",
    displayName: "New Mexico State Aggies",
    shortDisplayName: "New Mexico St",
    location: "New Mexico State",
    name: "Aggies",
    abbreviation: "NMSU",
    slug: "new-mexico-state-aggies",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2534",
    displayName: "Sam Houston Bearkats",
    shortDisplayName: "Sam Houston",
    location: "Sam Houston",
    name: "Bearkats",
    abbreviation: "SHSU",
    slug: "sam-houston-bearkats",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "98",
    displayName: "Western Kentucky Hilltoppers",
    shortDisplayName: "Western KY",
    location: "Western Kentucky",
    name: "Hilltoppers",
    abbreviation: "WKU",
    slug: "western-kentucky-hilltoppers",
    conferenceId: "12",
    conferenceName: "Conference USA",
    conferenceShortName: "CUSA",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "87",
    displayName: "Notre Dame Fighting Irish",
    shortDisplayName: "Notre Dame",
    location: "Notre Dame",
    name: "Fighting Irish",
    abbreviation: "ND",
    slug: "notre-dame-fighting-irish",
    conferenceId: "18",
    conferenceName: "FBS Independents",
    conferenceShortName: "FBS Indep.",
    isIndependent: true,
    cfbdId: null,
  },
  {
    espnId: "41",
    displayName: "UConn Huskies",
    shortDisplayName: "UConn",
    location: "UConn",
    name: "Huskies",
    abbreviation: "CONN",
    slug: "uconn-huskies",
    conferenceId: "18",
    conferenceName: "FBS Independents",
    conferenceShortName: "FBS Indep.",
    isIndependent: true,
    cfbdId: null,
  },
  {
    espnId: "2006",
    displayName: "Akron Zips",
    shortDisplayName: "Akron",
    location: "Akron",
    name: "Zips",
    abbreviation: "AKR",
    slug: "akron-zips",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2050",
    displayName: "Ball State Cardinals",
    shortDisplayName: "Ball State",
    location: "Ball State",
    name: "Cardinals",
    abbreviation: "BALL",
    slug: "ball-state-cardinals",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "189",
    displayName: "Bowling Green Falcons",
    shortDisplayName: "Bowling Green",
    location: "Bowling Green",
    name: "Falcons",
    abbreviation: "BGSU",
    slug: "bowling-green-falcons",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2084",
    displayName: "Buffalo Bulls",
    shortDisplayName: "Buffalo",
    location: "Buffalo",
    name: "Bulls",
    abbreviation: "BUFF",
    slug: "buffalo-bulls",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2117",
    displayName: "Central Michigan Chippewas",
    shortDisplayName: "C Michigan",
    location: "Central Michigan",
    name: "Chippewas",
    abbreviation: "CMU",
    slug: "central-michigan-chippewas",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2199",
    displayName: "Eastern Michigan Eagles",
    shortDisplayName: "E Michigan",
    location: "Eastern Michigan",
    name: "Eagles",
    abbreviation: "EMU",
    slug: "eastern-michigan-eagles",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2309",
    displayName: "Kent State Golden Flashes",
    shortDisplayName: "Kent State",
    location: "Kent State",
    name: "Golden Flashes",
    abbreviation: "KENT",
    slug: "kent-state-golden-flashes",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "113",
    displayName: "Massachusetts Minutemen",
    shortDisplayName: "UMass",
    location: "Massachusetts",
    name: "Minutemen",
    abbreviation: "MASS",
    slug: "massachusetts-minutemen",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "193",
    displayName: "Miami (OH) RedHawks",
    shortDisplayName: "Miami OH",
    location: "Miami (OH)",
    name: "RedHawks",
    abbreviation: "M-OH",
    slug: "miami-oh-redhawks",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "195",
    displayName: "Ohio Bobcats",
    shortDisplayName: "Ohio",
    location: "Ohio",
    name: "Bobcats",
    abbreviation: "OHIO",
    slug: "ohio-bobcats",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "16",
    displayName: "Sacramento State Hornets",
    shortDisplayName: "Sacramento St",
    location: "Sacramento State",
    name: "Hornets",
    abbreviation: "SAC",
    slug: "sacramento-state-hornets",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2649",
    displayName: "Toledo Rockets",
    shortDisplayName: "Toledo",
    location: "Toledo",
    name: "Rockets",
    abbreviation: "TOL",
    slug: "toledo-rockets",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2711",
    displayName: "Western Michigan Broncos",
    shortDisplayName: "W Michigan",
    location: "Western Michigan",
    name: "Broncos",
    abbreviation: "WMU",
    slug: "western-michigan-broncos",
    conferenceId: "15",
    conferenceName: "Mid-American Conference",
    conferenceShortName: "MAC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2005",
    displayName: "Air Force Falcons",
    shortDisplayName: "Air Force",
    location: "Air Force",
    name: "Falcons",
    abbreviation: "AFA",
    slug: "air-force-falcons",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "62",
    displayName: "Hawai'i Rainbow Warriors",
    shortDisplayName: "Hawai'i",
    location: "Hawai'i",
    name: "Rainbow Warriors",
    abbreviation: "HAW",
    slug: "hawaii-rainbow-warriors",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2440",
    displayName: "Nevada Wolf Pack",
    shortDisplayName: "Nevada",
    location: "Nevada",
    name: "Wolf Pack",
    abbreviation: "NEV",
    slug: "nevada-wolf-pack",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "167",
    displayName: "New Mexico Lobos",
    shortDisplayName: "New Mexico",
    location: "New Mexico",
    name: "Lobos",
    abbreviation: "UNM",
    slug: "new-mexico-lobos",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2449",
    displayName: "North Dakota State Bison",
    shortDisplayName: "N Dakota St",
    location: "North Dakota State",
    name: "Bison",
    abbreviation: "NDSU",
    slug: "north-dakota-state-bison",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2459",
    displayName: "Northern Illinois Huskies",
    shortDisplayName: "N Illinois",
    location: "Northern Illinois",
    name: "Huskies",
    abbreviation: "NIU",
    slug: "northern-illinois-huskies",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "23",
    displayName: "San José State Spartans",
    shortDisplayName: "San José St",
    location: "San José State",
    name: "Spartans",
    abbreviation: "SJSU",
    slug: "san-jose-state-spartans",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2439",
    displayName: "UNLV Rebels",
    shortDisplayName: "UNLV",
    location: "UNLV",
    name: "Rebels",
    abbreviation: "UNLV",
    slug: "unlv-rebels",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2638",
    displayName: "UTEP Miners",
    shortDisplayName: "UTEP",
    location: "UTEP",
    name: "Miners",
    abbreviation: "UTEP",
    slug: "utep-miners",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2751",
    displayName: "Wyoming Cowboys",
    shortDisplayName: "Wyoming",
    location: "Wyoming",
    name: "Cowboys",
    abbreviation: "WYO",
    slug: "wyoming-cowboys",
    conferenceId: "17",
    conferenceName: "Mountain West Conference",
    conferenceShortName: "Mountain West",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "68",
    displayName: "Boise State Broncos",
    shortDisplayName: "Boise St",
    location: "Boise State",
    name: "Broncos",
    abbreviation: "BOIS",
    slug: "boise-state-broncos",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "36",
    displayName: "Colorado State Rams",
    shortDisplayName: "Colorado St",
    location: "Colorado State",
    name: "Rams",
    abbreviation: "CSU",
    slug: "colorado-state-rams",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "278",
    displayName: "Fresno State Bulldogs",
    shortDisplayName: "Fresno St",
    location: "Fresno State",
    name: "Bulldogs",
    abbreviation: "FRES",
    slug: "fresno-state-bulldogs",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "204",
    displayName: "Oregon State Beavers",
    shortDisplayName: "Oregon St",
    location: "Oregon State",
    name: "Beavers",
    abbreviation: "ORST",
    slug: "oregon-state-beavers",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "21",
    displayName: "San Diego State Aztecs",
    shortDisplayName: "San Diego St",
    location: "San Diego State",
    name: "Aztecs",
    abbreviation: "SDSU",
    slug: "san-diego-state-aztecs",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "326",
    displayName: "Texas State Bobcats",
    shortDisplayName: "Texas St",
    location: "Texas State",
    name: "Bobcats",
    abbreviation: "TXST",
    slug: "texas-state-bobcats",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "328",
    displayName: "Utah State Aggies",
    shortDisplayName: "Utah State",
    location: "Utah State",
    name: "Aggies",
    abbreviation: "USU",
    slug: "utah-state-aggies",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "265",
    displayName: "Washington State Cougars",
    shortDisplayName: "Washington St",
    location: "Washington State",
    name: "Cougars",
    abbreviation: "WSU",
    slug: "washington-state-cougars",
    conferenceId: "9",
    conferenceName: "Pac-12 Conference",
    conferenceShortName: "Pac-12",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "333",
    displayName: "Alabama Crimson Tide",
    shortDisplayName: "Alabama",
    location: "Alabama",
    name: "Crimson Tide",
    abbreviation: "ALA",
    slug: "alabama-crimson-tide",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "8",
    displayName: "Arkansas Razorbacks",
    shortDisplayName: "Arkansas",
    location: "Arkansas",
    name: "Razorbacks",
    abbreviation: "ARK",
    slug: "arkansas-razorbacks",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2",
    displayName: "Auburn Tigers",
    shortDisplayName: "Auburn",
    location: "Auburn",
    name: "Tigers",
    abbreviation: "AUB",
    slug: "auburn-tigers",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "57",
    displayName: "Florida Gators",
    shortDisplayName: "Florida",
    location: "Florida",
    name: "Gators",
    abbreviation: "FLA",
    slug: "florida-gators",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "61",
    displayName: "Georgia Bulldogs",
    shortDisplayName: "Georgia",
    location: "Georgia",
    name: "Bulldogs",
    abbreviation: "UGA",
    slug: "georgia-bulldogs",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "96",
    displayName: "Kentucky Wildcats",
    shortDisplayName: "Kentucky",
    location: "Kentucky",
    name: "Wildcats",
    abbreviation: "UK",
    slug: "kentucky-wildcats",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "99",
    displayName: "LSU Tigers",
    shortDisplayName: "LSU",
    location: "LSU",
    name: "Tigers",
    abbreviation: "LSU",
    slug: "lsu-tigers",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "344",
    displayName: "Mississippi State Bulldogs",
    shortDisplayName: "Mississippi St",
    location: "Mississippi State",
    name: "Bulldogs",
    abbreviation: "MSST",
    slug: "mississippi-state-bulldogs",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "142",
    displayName: "Missouri Tigers",
    shortDisplayName: "Missouri",
    location: "Missouri",
    name: "Tigers",
    abbreviation: "MIZ",
    slug: "missouri-tigers",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "201",
    displayName: "Oklahoma Sooners",
    shortDisplayName: "Oklahoma",
    location: "Oklahoma",
    name: "Sooners",
    abbreviation: "OU",
    slug: "oklahoma-sooners",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "145",
    displayName: "Ole Miss Rebels",
    shortDisplayName: "Ole Miss",
    location: "Ole Miss",
    name: "Rebels",
    abbreviation: "MISS",
    slug: "ole-miss-rebels",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2579",
    displayName: "South Carolina Gamecocks",
    shortDisplayName: "South Carolina",
    location: "South Carolina",
    name: "Gamecocks",
    abbreviation: "SC",
    slug: "south-carolina-gamecocks",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2633",
    displayName: "Tennessee Volunteers",
    shortDisplayName: "Tennessee",
    location: "Tennessee",
    name: "Volunteers",
    abbreviation: "TENN",
    slug: "tennessee-volunteers",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "245",
    displayName: "Texas A&M Aggies",
    shortDisplayName: "Texas A&M",
    location: "Texas A&M",
    name: "Aggies",
    abbreviation: "TA&M",
    slug: "texas-am-aggies",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "251",
    displayName: "Texas Longhorns",
    shortDisplayName: "Texas",
    location: "Texas",
    name: "Longhorns",
    abbreviation: "TEX",
    slug: "texas-longhorns",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "238",
    displayName: "Vanderbilt Commodores",
    shortDisplayName: "Vanderbilt",
    location: "Vanderbilt",
    name: "Commodores",
    abbreviation: "VAN",
    slug: "vanderbilt-commodores",
    conferenceId: "8",
    conferenceName: "Southeastern Conference",
    conferenceShortName: "SEC",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2026",
    displayName: "App State Mountaineers",
    shortDisplayName: "App State",
    location: "App State",
    name: "Mountaineers",
    abbreviation: "APP",
    slug: "app-state-mountaineers",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2032",
    displayName: "Arkansas State Red Wolves",
    shortDisplayName: "Arkansas St",
    location: "Arkansas State",
    name: "Red Wolves",
    abbreviation: "ARST",
    slug: "arkansas-state-red-wolves",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "324",
    displayName: "Coastal Carolina Chanticleers",
    shortDisplayName: "Coastal",
    location: "Coastal Carolina",
    name: "Chanticleers",
    abbreviation: "CCU",
    slug: "coastal-carolina-chanticleers",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "290",
    displayName: "Georgia Southern Eagles",
    shortDisplayName: "GA Southern",
    location: "Georgia Southern",
    name: "Eagles",
    abbreviation: "GASO",
    slug: "georgia-southern-eagles",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2247",
    displayName: "Georgia State Panthers",
    shortDisplayName: "Georgia St",
    location: "Georgia State",
    name: "Panthers",
    abbreviation: "GAST",
    slug: "georgia-state-panthers",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "256",
    displayName: "James Madison Dukes",
    shortDisplayName: "James Madison",
    location: "James Madison",
    name: "Dukes",
    abbreviation: "JMU",
    slug: "james-madison-dukes",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "309",
    displayName: "Louisiana Ragin' Cajuns",
    shortDisplayName: "Louisiana",
    location: "Louisiana",
    name: "Ragin' Cajuns",
    abbreviation: "UL",
    slug: "louisiana-ragin-cajuns",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2348",
    displayName: "Louisiana Tech Bulldogs",
    shortDisplayName: "Louisiana Tech",
    location: "Louisiana Tech",
    name: "Bulldogs",
    abbreviation: "LT",
    slug: "louisiana-tech-bulldogs",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "276",
    displayName: "Marshall Thundering Herd",
    shortDisplayName: "Marshall",
    location: "Marshall",
    name: "Thundering Herd",
    abbreviation: "MRSH",
    slug: "marshall-thundering-herd",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "295",
    displayName: "Old Dominion Monarchs",
    shortDisplayName: "Old Dominion",
    location: "Old Dominion",
    name: "Monarchs",
    abbreviation: "ODU",
    slug: "old-dominion-monarchs",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "6",
    displayName: "South Alabama Jaguars",
    shortDisplayName: "South Alabama",
    location: "South Alabama",
    name: "Jaguars",
    abbreviation: "USA",
    slug: "south-alabama-jaguars",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2572",
    displayName: "Southern Miss Golden Eagles",
    shortDisplayName: "Southern Miss",
    location: "Southern Miss",
    name: "Golden Eagles",
    abbreviation: "USM",
    slug: "southern-miss-golden-eagles",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2653",
    displayName: "Troy Trojans",
    shortDisplayName: "Troy",
    location: "Troy",
    name: "Trojans",
    abbreviation: "TROY",
    slug: "troy-trojans",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
  {
    espnId: "2433",
    displayName: "UL Monroe Warhawks",
    shortDisplayName: "UL Monroe",
    location: "UL Monroe",
    name: "Warhawks",
    abbreviation: "ULM",
    slug: "ul-monroe-warhawks",
    conferenceId: "37",
    conferenceName: "Sun Belt Conference",
    conferenceShortName: "Sun Belt",
    isIndependent: false,
    cfbdId: null,
  },
];

/** Lookup by ESPN numeric id (as returned in scoreboard competitor.team.id). */
export const FBS_TEAM_BY_ESPN_ID: ReadonlyMap<string, FbsConferenceTeam> = new Map(
  FBS_CONFERENCE_TEAMS.map((t) => [t.espnId, t]),
)

/** Lookup by ESPN slug (stable, lowercase-hyphenated; e.g. odds feeds keyed on slug). */
export const FBS_TEAM_BY_SLUG: ReadonlyMap<string, FbsConferenceTeam> = new Map(
  FBS_CONFERENCE_TEAMS.map((t) => [t.slug, t]),
)

/**
 * Lookup by every exact name string ESPN itself reports for a team: displayName AND
 * shortDisplayName ("Ole Miss Rebels" -> also keyed under "Ole Miss"). Both come from
 * the same fetch as the table above, so this is not a guessed alias list - only names
 * ESPN itself uses. game-identity.ts disables prefix matching on purpose ("Texas" is a
 * prefix of "Texas Tech", "Miami" of "Miami (OH)", "Washington" of "Washington State"),
 * so a spelling mismatch must be solved by an exact alias, never a looser match.
 *
 * This does NOT cover odds-feed-specific spellings (e.g. a bookmaker's own short name),
 * which are unverifiable from ESPN alone. Add a specific pair here only once observed
 * live (watch fixtureUnconfirmed on production, per C-111's own disclosed limit) -
 * never a guessed spelling (rule 1: no fabricated data applies to reference tables too).
 */
export const FBS_NAME_ALIASES: ReadonlyMap<string, FbsConferenceTeam> = new Map([
  ...FBS_CONFERENCE_TEAMS.map((t): readonly [string, FbsConferenceTeam] => [t.displayName, t]),
  ...FBS_CONFERENCE_TEAMS.filter((t) => t.shortDisplayName !== t.displayName).map(
    (t): readonly [string, FbsConferenceTeam] => [t.shortDisplayName, t],
  ),
]);

/**
 * Resolve any of: ESPN numeric id, ESPN slug, or an ESPN-verified display/short name, to
 * its FBS team row. Returns null rather than guessing - a caller that gets null must
 * treat the fixture as unconfirmed (fixture-confirmation.ts's own rule), never invent a
 * match.
 */
export function resolveFbsTeam(identifier: string): FbsConferenceTeam | null {
  return (
    FBS_TEAM_BY_ESPN_ID.get(identifier) ??
    FBS_TEAM_BY_SLUG.get(identifier) ??
    FBS_NAME_ALIASES.get(identifier) ??
    null
  );
}

