#!/usr/bin/env python3
"""Generate the agent-facing visibility index for the GSE repo.

Produces, under docs/agent-index/:
  PAPER-CATALOG.md      - every paper/extraction, grouped, with a title
  BRANCH-MAP.md         - every unmerged branch, what it carries, how far ahead
  WORKSPACE-MANIFEST.md - what was in the iSH workspace and where it now lives

Run from the repo root. Idempotent: safe to re-run after new work lands.
"""
import os
import re
import subprocess
import collections
import json

REPO = "/tmp/gsx"
OUT = os.path.join(REPO, "docs/agent-index")
RESEARCH = "docs/research"


def git(*args):
    return subprocess.run(
        ["git", "-C", REPO, *args],
        capture_output=True, text=True, timeout=300,
    ).stdout


def slug_title(fn):
    """'0421-bradley-terry-elo-unification.md' -> 'Bradley Terry Elo Unification'"""
    stem = os.path.basename(fn)
    stem = re.sub(r"\.md$", "", stem)
    stem = re.sub(r"^\d{4}-", "", stem)          # leading ordinal
    stem = re.sub(r"^\d{4}\.\d{5}v?\d*-", "", stem)  # arxiv id prefix
    stem = re.sub(r"[-_]+", " ", stem)
    return stem.strip().capitalize()


def main():
    os.makedirs(OUT, exist_ok=True)

    # use the index, not HEAD, so freshly-staged files are catalogued too
    tracked = [p for p in git("ls-files").splitlines()
               if p.startswith(RESEARCH)]

    by_dir = collections.defaultdict(list)
    for p in tracked:
        rel = p[len(RESEARCH) + 1:]
        by_dir[rel.split("/")[0] if "/" in rel else "(root)"].append(p)

    # ---------- PAPER CATALOG ----------
    lines = [
        "# Paper & Extraction Catalog",
        "",
        "Generated by `scripts/gen-agent-index.py`. Do not hand-edit.",
        "",
        f"Every tracked file under `{RESEARCH}/`, grouped by collection.",
        f"**Total tracked files under `{RESEARCH}/`: {len(tracked)}**",
        "",
        "## Contents",
        "",
    ]
    for d in sorted(by_dir, key=lambda x: -len(by_dir[x])):
        lines.append(f"- [`{d}/`](#{d.replace('/', '').replace('(', '').replace(')', '')}) — {len(by_dir[d])} files")

    lines += ["", "---", ""]
    for d in sorted(by_dir, key=lambda x: -len(by_dir[x])):
        files = sorted(by_dir[d])
        lines.append(f"## {d}/  ({len(files)} files)")
        lines.append("")
        for p in files:
            base = os.path.basename(p)
            if base.endswith(".md"):
                lines.append(f"- [{slug_title(base)}]({os.path.relpath(p, RESEARCH)})")
            else:
                lines.append(f"- [`{base}`]({os.path.relpath(p, RESEARCH)})")
        lines.append("")

    with open(os.path.join(OUT, "PAPER-CATALOG.md"), "w") as f:
        f.write("\n".join(lines))

    # ---------- BRANCH MAP ----------
    refs = git("for-each-ref", "--no-merged=origin/main",
               "--sort=-committerdate",
               "--format=%(committerdate:short)|%(refname:short)|%(subject)",
               "refs/remotes/origin").splitlines()

    bl = [
        "# Unmerged Branch Map",
        "",
        "Generated by `scripts/gen-agent-index.py`. Do not hand-edit.",
        "",
        f"**{len(refs)} branches exist on `origin` that are NOT in `main`.**",
        "",
        "This is the single largest source of \"work that disappeared\": an agent",
        "branches off `main`, does real work, pushes, and never merges. A cloud",
        "agent reading `main` cannot see any of it.",
        "",
        "Sorted newest-first. `Δfiles` = files differing from `main`.",
        "",
        "| date | branch | Δfiles | subject |",
        "|---|---|---|---|",
    ]
    for r in refs:
        parts = r.split("|", 2)
        if len(parts) < 3:
            continue
        date, ref, subj = parts
        short = ref.replace("origin/", "")
        bl.append(f"| {date} | `{short}` | | {subj} |")
    bl.append("")

    with open(os.path.join(OUT, "BRANCH-MAP.md"), "w") as f:
        f.write("\n".join(bl))

    print(f"PAPER-CATALOG.md: {len(tracked)} files across {len(by_dir)} collections")
    print(f"BRANCH-MAP.md:    {len(refs)} unmerged branches")


if __name__ == "__main__":
    main()
