#!/usr/bin/env bash
# ============================================================
# Sports Prediction Platform — local one-command bootstrap.
#
# Usage (from repo root):
#   bash scripts/local.sh           # set up everything + run app + worker
#   bash scripts/local.sh setup     # just set up (no run)
#   bash scripts/local.sh run       # just run app + worker (assumes setup done)
#   bash scripts/local.sh reset     # wipe DB volume and re-setup
#
# Safe to re-run. Every step is idempotent.
# ============================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

log()  { printf '\033[1;34m[local]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ ok  ]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[fail]\033[0m %s\n' "$*"; exit 1; }

# ── prereqs ─────────────────────────────────────────────────
check_prereqs() {
  command -v node >/dev/null || die "Node 20+ required. Install from https://nodejs.org"
  local node_major
  node_major="$(node -p 'process.versions.node.split(".")[0]')"
  [ "$node_major" -ge 20 ] || die "Node $node_major detected; need 20+"
  command -v npm >/dev/null  || die "npm required"
  command -v docker >/dev/null || die "Docker required. Install Docker Desktop."
  docker info >/dev/null 2>&1 || die "Docker daemon not running. Start Docker Desktop."
  ok "Prereqs OK (node $(node -v), docker running)"
}

# ── .env ────────────────────────────────────────────────────
write_env() {
  if [ -f .env ]; then
    ok ".env already exists (keeping yours)"
    return
  fi
  log "Writing .env with working local defaults + your Odds API key..."
  local secret
  secret="$(openssl rand -base64 32 2>/dev/null || node -e 'console.log(require("crypto").randomBytes(32).toString("base64"))')"
  cat > .env <<EOF
# Local development — generated by scripts/local.sh
# Postgres/Redis credentials match docker/docker-compose.yml.

DATABASE_URL="postgresql://sports:sports_dev_password@127.0.0.1:5432/sports_platform?schema=public"
DIRECT_URL="postgresql://sports:sports_dev_password@127.0.0.1:5432/sports_platform?schema=public"

NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:3000"

GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

STRIPE_SECRET_KEY="sk_test_placeholder"
STRIPE_WEBHOOK_SECRET="whsec_placeholder"
STRIPE_PRO_PRICE_ID="price_placeholder_pro"
STRIPE_ELITE_PRICE_ID="price_placeholder_elite"
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_placeholder"

THE_ODDS_API_KEY="e7f1bc97f419509c7426bad7a2504019"

ANTHROPIC_API_KEY=""

REDIS_URL="redis://127.0.0.1:6379"

NODE_ENV="development"
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# Bootstrap progression flags (safe defaults — see .env.example for the progression guide)
CANONICAL_HISTORY_ENABLED="false"
DERIVED_MODEL_HISTORY_ENABLED="false"
PUBLIC_PICKS_ENABLED="false"
FEATURED_PICK_PROMOTION_ENABLED="false"
PERFORMANCE_STATS_ENABLED="false"
PUBLIC_BLOG_ENABLED="false"
CONFIDENCE_DISPLAY_MODE="labels"
MIN_DATA_QUALITY_FOR_GAME_LOG="40"
OUTCOME_LEARNING_ENABLED="false"
MIN_SETTLED_PICKS_FOR_LEARNING="100"
EOF
  ok "Wrote .env"
}

link_envs() {
  local targets=(apps/web/.env packages/db/.env)
  for target in "${targets[@]}"; do
    if [ -L "$target" ]; then
      rm -f "$target"
    elif [ -e "$target" ]; then
      warn "$target exists as a regular file — keeping (remove manually to re-link)"
      continue
    fi
    ln -s ../../.env "$target"
  done
  ok "Linked .env into apps/web and packages/db"
}

# ── docker ──────────────────────────────────────────────────
start_docker_services() {
  log "Starting Postgres + Redis via docker compose..."
  docker compose -f docker/docker-compose.yml up -d
  log "Waiting for Postgres to accept connections..."
  local tries=0
  until docker exec sports_postgres pg_isready -U sports -q 2>/dev/null; do
    tries=$((tries+1))
    [ $tries -gt 60 ] && die "Postgres did not become ready within 60s"
    sleep 1
  done
  ok "Postgres + Redis are up"
}

# ── deps ────────────────────────────────────────────────────
install_deps() {
  if [ -d node_modules/.bin ]; then
    ok "node_modules already installed"
  else
    log "Running npm install (this takes ~1 min the first time)..."
    npm install
    ok "Dependencies installed"
  fi
}

# ── prisma ──────────────────────────────────────────────────
setup_database() {
  log "Generating Prisma client..."
  npm run db:generate --silent
  log "Pushing schema to Postgres..."
  npm run db:push --silent
  log "Seeding sports + leagues..."
  npm run db:seed --silent
  ok "Database ready"
}

# ── run ─────────────────────────────────────────────────────
run_all() {
  [ -f .env ] || die ".env missing — run: bash scripts/local.sh setup"
  log "Loading .env into shell..."
  set -a
  # shellcheck disable=SC1091
  . ./.env
  set +a

  log "Starting Next.js dev server on http://localhost:3000 ..."
  npm run dev > /tmp/sports-app.log 2>&1 &
  APP_PID=$!

  log "Starting data-refresh worker..."
  npm run start --workspace=workers/data-refresh > /tmp/sports-worker.log 2>&1 &
  WORKER_PID=$!

  cleanup() {
    echo
    log "Shutting down (app=$APP_PID worker=$WORKER_PID)..."
    kill "$APP_PID" "$WORKER_PID" 2>/dev/null || true
    wait "$APP_PID" "$WORKER_PID" 2>/dev/null || true
    ok "Stopped"
  }
  trap cleanup EXIT INT TERM

  # Wait for Next.js to be reachable
  local tries=0
  until curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:3000/ 2>/dev/null | grep -qE '200|307|308'; do
    tries=$((tries+1))
    [ $tries -gt 60 ] && { tail -40 /tmp/sports-app.log; die "App did not start within 60s"; }
    sleep 1
  done
  ok "App is live: http://localhost:3000"

  cat <<BANNER

────────────────────────────────────────────────────────────
  🏈  Sports platform running
────────────────────────────────────────────────────────────
  App:      http://localhost:3000
  App log:  tail -f /tmp/sports-app.log
  Worker log: tail -f /tmp/sports-worker.log

  Ctrl-C to stop both.
────────────────────────────────────────────────────────────
BANNER

  # Stream both logs together until user hits Ctrl-C
  tail -n 0 -f /tmp/sports-app.log /tmp/sports-worker.log
}

# ── reset (destructive, explicit) ──────────────────────────
reset_all() {
  warn "Resetting: stopping containers and wiping Postgres volume."
  docker compose -f docker/docker-compose.yml down -v || true
  ok "Volumes wiped. Re-running setup..."
  setup_all
}

setup_all() {
  check_prereqs
  write_env
  link_envs
  start_docker_services
  install_deps
  setup_database
  ok "Setup complete."
}

case "${1:-all}" in
  setup) setup_all ;;
  run)   run_all ;;
  reset) reset_all ;;
  all|"") setup_all; run_all ;;
  *)     die "Unknown command: $1 (use: setup | run | reset | all)" ;;
esac
