/**
 * GSE Competitor Intelligence — structured data contracts for 45+ competitors
 * across fantasy football, DFS, sports prediction, and betting analytics.
 *
 * Sources: public product pages, official feature listings, published pricing.
 * All pricing figures labeled as public-page estimates — verify before citing.
 * Confidence levels reflect strength of public knowledge.
 */

// ── Enums ──────────────────────────────────────────────────────────────────

export type CompetitorCategory =
  | "draft-assistant"
  | "mock-simulator"
  | "live-draft-sync"
  | "league-sync"
  | "dfs-optimizer"
  | "dfs-portfolio"
  | "sports-prediction"
  | "betting-analytics"
  | "odds-intelligence"
  | "all-in-one-fantasy"
  | "roster-analyzer"
  | "trade-calculator"
  | "waiver-assistant"
  | "player-insights"
  | "fantasy-hub"
  | "dynasty-tools"
  | "best-ball-platform"
  | "auction-tools"
  | "league-host"
  | "content-media"
  | "adjacent-analytics";

export type ConfidenceLevel = "HIGH" | "MEDIUM" | "LOW" | "UNVERIFIED";

export type SyncSupport =
  | "live-extension"
  | "oauth-api"
  | "manual-upload"
  | "csv-import"
  | "none"
  | "unknown";

export type MonetizationModel =
  | "freemium-subscription"
  | "seasonal-draft-kit"
  | "annual-nfl-plan"
  | "free-with-ads"
  | "sportsbook-affiliate"
  | "content-tools-bundle"
  | "premium-community"
  | "b2b-data-licensing"
  | "platform-host-fees";

export type GseExceedMethod =
  | "first-of-kind-system"
  | "deeper-evidence-layer"
  | "league-memory"
  | "voice-jarvis"
  | "pick-thesis-counter"
  | "calibration-loop"
  | "process-grading"
  | "narrative-inflation-detection"
  | "draft-futures-engine"
  | "opponent-modeling"
  | "roster-destiny"
  | "bias-mirror"
  | "trust-ledger";

// ── Core interface ──────────────────────────────────────────────────────────

export interface CompetitorEntry {
  readonly id: string;
  readonly name: string;
  readonly url: string; // public page — source gap noted where unknown
  readonly categories: ReadonlyArray<CompetitorCategory>;
  readonly targetUser: string;
  readonly corePain: string; // what problem they solve
  readonly corePromise: string;

  // Feature flags
  readonly features: {
    readonly draftAssistant: boolean;
    readonly mockDraft: boolean;
    readonly liveDraftSync: SyncSupport;
    readonly leagueSync: boolean;
    readonly customScoring: boolean;
    readonly auctionSupport: boolean;
    readonly keeperDynasty: boolean;
    readonly superflex: boolean;
    readonly idp: boolean;
    readonly bestBall: boolean;
    readonly projections: boolean;
    readonly adp: boolean;
    readonly tiers: boolean;
    readonly positionRunAlerts: boolean;
    readonly projectedAvailability: boolean;
    readonly rosterNeeds: boolean;
    readonly pickRecommendations: boolean;
    readonly draftGradeAnalyzer: boolean;
    readonly tradeCalculator: boolean;
    readonly waiverTool: boolean;
    readonly startSit: boolean;
    readonly dfsOptimizer: boolean;
    readonly playerNewsInjury: boolean;
    readonly browserExtension: boolean;
    readonly mobileApp: boolean;
    readonly customProjections: boolean;
    readonly historicalDraftStorage: boolean;
    readonly managerGenome: boolean; // first-of-kind; almost none have this
    readonly voiceAssistant: boolean; // first-of-kind
    readonly pickThesisCounterThesis: boolean; // first-of-kind
    readonly draftFuturesEngine: boolean; // first-of-kind
    readonly opponentModeling: boolean; // rare
    readonly rosterDestinySimulator: boolean; // first-of-kind
    readonly biasDetection: boolean; // rare
    readonly processGrading: boolean; // rare
    readonly calibrationTracking: boolean; // rare
    readonly narrativeInflationDetection: boolean; // first-of-kind
  };

  readonly monetization: ReadonlyArray<MonetizationModel>;
  readonly pricingNote: string; // public estimate or "source gap"

  readonly strongestFeature: string;
  readonly weakestOrMissing: string;
  readonly mechanicGseLearn: string;
  readonly gseExceedMethods: ReadonlyArray<GseExceedMethod>;
  readonly gseExceedNarrative: string;

  readonly confidence: ConfidenceLevel;
  readonly sourceNote: string;
}

// ── Helper functions ────────────────────────────────────────────────────────

export function summarizeCompetitorCategories(
  entries: ReadonlyArray<CompetitorEntry>
): Record<CompetitorCategory, number> {
  const counts = {} as Record<CompetitorCategory, number>;
  for (const e of entries) {
    for (const cat of e.categories) {
      counts[cat] = (counts[cat] ?? 0) + 1;
    }
  }
  return counts;
}

export function topCompetitorMechanics(
  entries: ReadonlyArray<CompetitorEntry>
): ReadonlyArray<{ name: string; mechanic: string }> {
  return entries.map((e) => ({ name: e.name, mechanic: e.mechanicGseLearn }));
}

export function competitorsMissingFeature(
  entries: ReadonlyArray<CompetitorEntry>,
  feature: keyof CompetitorEntry["features"]
): ReadonlyArray<CompetitorEntry> {
  return entries.filter((e) => !e.features[feature]);
}

export function gseGapSummary(
  entries: ReadonlyArray<CompetitorEntry>
): {
  missingManagerGenome: number;
  missingVoiceAssistant: number;
  missingDraftFuturesEngine: number;
  missingPickThesis: number;
  missingRosterDestiny: number;
  missingBiasDetection: number;
  missingProcessGrading: number;
  missingCalibrationTracking: number;
  missingNarrativeInflation: number;
} {
  return {
    missingManagerGenome: competitorsMissingFeature(entries, "managerGenome").length,
    missingVoiceAssistant: competitorsMissingFeature(entries, "voiceAssistant").length,
    missingDraftFuturesEngine: competitorsMissingFeature(entries, "draftFuturesEngine").length,
    missingPickThesis: competitorsMissingFeature(entries, "pickThesisCounterThesis").length,
    missingRosterDestiny: competitorsMissingFeature(entries, "rosterDestinySimulator").length,
    missingBiasDetection: competitorsMissingFeature(entries, "biasDetection").length,
    missingProcessGrading: competitorsMissingFeature(entries, "processGrading").length,
    missingCalibrationTracking: competitorsMissingFeature(entries, "calibrationTracking").length,
    missingNarrativeInflation: competitorsMissingFeature(entries, "narrativeInflationDetection").length,
  };
}

// ── Competitor data ─────────────────────────────────────────────────────────

export const COMPETITOR_INTELLIGENCE: ReadonlyArray<CompetitorEntry> = [
  {
    id: "fantasypros",
    name: "FantasyPros",
    url: "https://www.fantasypros.com",
    categories: ["draft-assistant", "mock-simulator", "all-in-one-fantasy", "player-insights"],
    targetUser: "Mainstream fantasy player — casual to serious",
    corePain: "Too many rankings sources; hard to know who to trust or who to pick",
    corePromise: "Expert consensus rankings aggregated from 100+ analysts; one trusted starting point",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "live-extension",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: true,
      idp: true,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: true,
      rosterNeeds: true,
      pickRecommendations: true,
      draftGradeAnalyzer: true,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: true,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "seasonal-draft-kit", "sportsbook-affiliate"],
    pricingNote: "Draft Kit ~$9.99/month or seasonal; annual plans available — public-page estimate, verify",
    strongestFeature: "Expert Consensus Rankings aggregated from 100+ analysts; broad platform support (Yahoo, ESPN, Sleeper, CBS, NFL, MFL, Fantrax, FFPC, RTS)",
    weakestOrMissing: "No multi-season league memory; no pick thesis or counter-thesis; recommendations are board-based, not decision-tree based",
    mechanicGseLearn: "Draft Assistant + Mock Lobby + Cheat Sheet Creator as a seasonal funnel: free tools convert to draft kit purchase at peak urgency",
    gseExceedMethods: ["league-memory", "pick-thesis-counter", "draft-futures-engine", "voice-jarvis", "calibration-loop"],
    gseExceedNarrative: "GSE beats FantasyPros by adding league-specific memory, a pick thesis with mandatory counter-evidence, and a draft futures engine that shows what survives to your next pick — not just what's best available now",
    confidence: "HIGH",
    sourceNote: "Public product page, well-documented feature set",
  },
  {
    id: "draftkick",
    name: "DraftKick",
    url: "https://www.draftkick.com",
    categories: ["draft-assistant", "live-draft-sync", "league-sync"],
    targetUser: "Serious fantasy player who drafts on Yahoo, ESPN, or Sleeper",
    corePain: "Drafting in-platform without external intelligence is leaving value on the table",
    corePromise: "Chrome extension overlays your draft room with live rankings, ADP, standings impact, projected availability, and pick recommendations",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "live-extension",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: true,
      rosterNeeds: true,
      pickRecommendations: true,
      draftGradeAnalyzer: true,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: true,
      mobileApp: false,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "seasonal-draft-kit"],
    pricingNote: "Free tier + premium plans; seasonal pricing — source gap, verify on public page",
    strongestFeature: "Standings impact score per pick — shows how a player affects championship odds, not just value; real-time ADP for projected availability",
    weakestOrMissing: "No season-long tools (waiver, trade, start/sit); no multi-year league memory; draft-only product",
    mechanicGseLearn: "Standings impact: every pick recommendation includes title-odds delta. This is the single most important mechanic to internalize — picks affect the future, not just the board",
    gseExceedMethods: ["league-memory", "voice-jarvis", "draft-futures-engine", "opponent-modeling", "roster-destiny", "process-grading"],
    gseExceedNarrative: "GSE absorbs DraftKick's standings-impact mechanic and extends it: title-odds delta powered by full season simulation, league memory that learns each manager's behavior, and Voice Jarvis for on-clock decision support",
    confidence: "HIGH",
    sourceNote: "Product page and screenshots reviewed",
  },
  {
    id: "footballguys",
    name: "Footballguys Draft Dominator",
    url: "https://www.footballguys.com",
    categories: ["draft-assistant", "mock-simulator", "league-sync", "all-in-one-fantasy"],
    targetUser: "Serious/advanced fantasy player; dynasty and keeper league managers",
    corePain: "Generic draft tools don't understand my league's custom settings, keeper values, or dynasty context",
    corePromise: "Real-time draft advice customized to your exact league: scoring, format, keeper rules, IDP, superflex, auction",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: true,
      idp: true,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: true,
      pickRecommendations: true,
      draftGradeAnalyzer: true,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "annual-nfl-plan", "seasonal-draft-kit"],
    pricingNote: "Annual subscriptions; seasonal draft access — public-page estimate, verify",
    strongestFeature: "Deepest custom league support of any draft tool: IDP, superflex, keeper, dynasty, auction, best ball all properly weighted against your scoring",
    weakestOrMissing: "No league memory across seasons; no pick thesis; advice is board-based not decision-tree based; UI is functional but dated",
    mechanicGseLearn: "League import + custom scoring properly weighted into pick value — not just rankings adjusted for PPR vs standard. Real positional weighting changes recommendations significantly",
    gseExceedMethods: ["league-memory", "draft-futures-engine", "voice-jarvis", "pick-thesis-counter", "bias-mirror"],
    gseExceedNarrative: "GSE matches Footballguys on custom league depth then surpasses it: multi-season league memory that learns manager behavior, pick thesis with counter-evidence, and voice Jarvis for on-clock support",
    confidence: "HIGH",
    sourceNote: "Well-documented product; direct competitor in serious fantasy market",
  },
  {
    id: "4for4",
    name: "4for4 Draft Hero",
    url: "https://www.4for4.com",
    categories: ["draft-assistant", "live-draft-sync", "player-insights"],
    targetUser: "Data-driven fantasy player who wants projections + draft advice unified",
    corePain: "Rankings and draft advice are usually from different sources; they don't update together as the draft unfolds",
    corePromise: "Personalized draft advice that updates after every pick, powered by 4for4 projections",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "live-extension",
      leagueSync: true,
      customScoring: true,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: true,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: true,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "seasonal-draft-kit"],
    pricingNote: "Annual and seasonal plans — public-page estimate, verify",
    strongestFeature: "Dynamic recommendation refresh after every pick; projections and draft advice come from the same proprietary projection system",
    weakestOrMissing: "Limited format support (no auction/keeper/dynasty); no post-draft analysis; no counter-thesis",
    mechanicGseLearn: "Post-pick recommendation refresh: every pick by anyone changes the value landscape. The pick engine must re-score after every selection, not just at the user's turn",
    gseExceedMethods: ["pick-thesis-counter", "draft-futures-engine", "league-memory", "voice-jarvis", "calibration-loop"],
    gseExceedNarrative: "GSE matches 4for4's post-pick refresh, adds the WHY (pick thesis + counter-thesis), multi-year league memory, and voice Jarvis",
    confidence: "HIGH",
    sourceNote: "Well-known product in fantasy community",
  },
  {
    id: "rotowire-draft",
    name: "RotoWire Draft Assistant",
    url: "https://www.rotowire.com",
    categories: ["draft-assistant", "live-draft-sync", "player-insights", "all-in-one-fantasy"],
    targetUser: "Mainstream to serious fantasy player wanting expert-backed draft support",
    corePain: "Draft decisions need real-time injury/news context alongside rankings; most tools don't integrate both",
    corePromise: "Custom draft advice tied to expert rankings, real-time news/injuries, cheat sheets, and Yahoo/ESPN/CBS sync",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "live-extension",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: true,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: true,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "annual-nfl-plan", "sportsbook-affiliate"],
    pricingNote: "Annual NFL plans; includes DFS and fantasy tools — source gap, verify",
    strongestFeature: "Real-time injury/news integration during draft; expert notes and queue during live draft; multi-platform sync (Yahoo/ESPN/CBS)",
    weakestOrMissing: "No pick counter-thesis; no multi-year memory; recommendations don't model opponent behavior",
    mechanicGseLearn: "News-tied draft advice: an injury update should immediately reprice the injured player and elevate alternatives. Narrative/news must be wired into the pick engine",
    gseExceedMethods: ["narrative-inflation-detection", "deeper-evidence-layer", "league-memory", "pick-thesis-counter"],
    gseExceedNarrative: "GSE goes deeper on news: not just injecting the headline but classifying narrative reliability, detecting hype inflation, and requiring football mechanism before adjusting projections",
    confidence: "HIGH",
    sourceNote: "Well-documented all-in-one fantasy platform",
  },
  {
    id: "draft-sharks",
    name: "Draft Sharks Draft War Room",
    url: "https://www.draftsharks.com",
    categories: ["draft-assistant", "mock-simulator", "player-insights"],
    targetUser: "Value-focused serious fantasy player",
    corePain: "Not knowing what a player is truly worth vs. what the field is paying",
    corePromise: "3D Value System with real-time value calculations, war room, mock trainer, and keeper calculator",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "manual-upload",
      leagueSync: false,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Subscription-based — source gap, verify",
    strongestFeature: "3D Value System framing: positions value across three axes simultaneously; League Analyzer and ADP Market Index",
    weakestOrMissing: "No live draft sync; no league memory; no season-long roster intelligence integration",
    mechanicGseLearn: "Multi-dimensional value framing: a pick isn't just ranked — it has value on multiple axes. This vocabulary gives users a richer mental model",
    gseExceedMethods: ["first-of-kind-system", "draft-futures-engine", "league-memory"],
    gseExceedNarrative: "GSE builds a Draft Edge Score with more dimensions plus league memory and pick thesis",
    confidence: "MEDIUM",
    sourceNote: "Product feature list from public page; some features may have changed",
  },
  {
    id: "fantasy-life",
    name: "Fantasy Life / FantasyHQ / Best Ball HQ",
    url: "https://fantasylife.com",
    categories: ["all-in-one-fantasy", "draft-assistant", "best-ball-platform", "content-media"],
    targetUser: "Mainstream to serious fantasy player seeking season-long hub",
    corePain: "Fantasy tools are fragmented; managing draft, roster, trades, waivers, and standings requires multiple apps",
    corePromise: "One app for everything: draft, roster, trades, waivers, start/sit, standings, and player exposure across leagues",
    features: {
      draftAssistant: true,
      mockDraft: false,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "sportsbook-affiliate"],
    pricingNote: "Freemium + premium tiers — source gap, verify current pricing",
    strongestFeature: "Player exposure tracking across all leagues; all-season hub approach; Best Ball HQ for best ball specific tooling",
    weakestOrMissing: "No multi-year league memory; no draft futures engine; no pick thesis",
    mechanicGseLearn: "Player exposure across leagues: a user in 5+ leagues needs to know their total exposure to each player across all of them — this is a portfolio view of fantasy decisions",
    gseExceedMethods: ["league-memory", "draft-futures-engine", "process-grading"],
    gseExceedNarrative: "GSE treats multi-league exposure as a portfolio problem with correlation and fragility scoring, not just a list",
    confidence: "MEDIUM",
    sourceNote: "Public product page; features evolve frequently",
  },
  {
    id: "dynasty-nerds",
    name: "Dynasty Nerds",
    url: "https://www.dynastynerds.com",
    categories: ["dynasty-tools", "draft-assistant", "mock-simulator", "trade-calculator"],
    targetUser: "Serious dynasty fantasy manager",
    corePain: "Dynasty valuation requires multi-year modeling that redraft tools don't support",
    corePromise: "Dynasty-first tools: Nerd Score, AI mock drafts, trade calculator, rookie tools, league analyzer",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "none",
      leagueSync: true,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: true,
      superflex: true,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: true,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Premium subscription — source gap, verify",
    strongestFeature: "Nerd Score dynasty valuation; AI mock draft opponents for dynasty; rookie pick tracking and valuation",
    weakestOrMissing: "No redraft support; no league memory beyond current season; no pick thesis",
    mechanicGseLearn: "Dynasty aging curves and rookie performance curves as a multi-year valuation model — not just current projection but trajectory",
    gseExceedMethods: ["league-memory", "pick-thesis-counter", "roster-destiny"],
    gseExceedNarrative: "GSE applies dynasty-style trajectory modeling to all formats and adds League Memory that learns the specific room's dynasty valuation tendencies",
    confidence: "MEDIUM",
    sourceNote: "Public product page + community reputation",
  },
  {
    id: "fantasy-nerds",
    name: "Fantasy Nerds",
    url: "https://www.fantasynerds.com",
    categories: ["draft-assistant", "player-insights", "all-in-one-fantasy"],
    targetUser: "Value-seeking mainstream fantasy player",
    corePain: "Too many tools scattered across sites; want consolidated rankings, ADP, handcuffs, tiers, and injury risk",
    corePromise: "Draft Buddy with consensus rankings, mock drafts, draft values, handcuffs, tiers, SOS, injury risk",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: false,
      idp: false,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Free with paid tier — source gap, verify",
    strongestFeature: "Comprehensive small-tool coverage: handcuffs, tiers, injury risk, consensus, SOS all in one place",
    weakestOrMissing: "No live draft sync; no league memory; shallow intelligence layer",
    mechanicGseLearn: "Handcuff identification is underrated: knowing the backup to your starting RB is a roster construction strategy, not just a curiosity",
    gseExceedMethods: ["draft-futures-engine", "league-memory", "deeper-evidence-layer"],
    gseExceedNarrative: "GSE treats handcuff planning as part of roster destiny simulation — not just who the backup is, but what your lineup looks like if your RB1 misses 4 weeks",
    confidence: "MEDIUM",
    sourceNote: "Public product page",
  },
  {
    id: "udk-plus",
    name: "The Fantasy Footballers UDK+",
    url: "https://www.thefantasyfootballers.com",
    categories: ["draft-assistant", "all-in-one-fantasy", "content-media"],
    targetUser: "Fantasy Footballers podcast listeners; mainstream to serious players",
    corePain: "Content and tools are from different sources; expert commentary and data tools don't connect",
    corePromise: "Ultimate Draft Kit: tiered rankings, premium projections, sleepers/busts, consistency, market share, SOS, red-zone, Draft Analyzer, league sync",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: true,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: true,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "seasonal-draft-kit", "content-tools-bundle"],
    pricingNote: "UDK+ seasonal access; bundled with podcast/content — source gap, verify",
    strongestFeature: "Content-tool integration: podcast listeners feel continuity between what they hear and what the tool shows; video player profiles, consistency/durability metrics",
    weakestOrMissing: "No live draft sync extension; tool is post-draft without waiver/trade; limited formats",
    mechanicGseLearn: "Content-to-tool continuity: every piece of content (article, podcast clip, insight) should link into the tool's recommendation engine. GSN Transmission → GSE Decision Engine",
    gseExceedMethods: ["first-of-kind-system", "league-memory", "process-grading"],
    gseExceedNarrative: "GSE makes every content insight machine-readable evidence inside the decision engine — not just adjacent content",
    confidence: "MEDIUM",
    sourceNote: "Public product page + well-known fantasy media brand",
  },
  {
    id: "sleeper",
    name: "Sleeper",
    url: "https://sleeper.com",
    categories: ["league-host", "draft-assistant"],
    targetUser: "Dynasty, keeper, and younger-skewing fantasy managers; all formats",
    corePain: "Yahoo/ESPN feel dated; need a modern platform with better UX and notifications",
    corePromise: "Modern fantasy app with league hosting, real-time chat, trades, news feed, and all draft formats",
    features: {
      draftAssistant: false,
      mockDraft: true,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: true,
      idp: false,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "platform-host-fees"],
    pricingNote: "Free platform with premium features — source gap, verify",
    strongestFeature: "Best mobile draft experience; strong dynasty/keeper ecosystem; API access for developers",
    weakestOrMissing: "Not an intelligence tool — it is an environment; no pick recommendations or draft intelligence",
    mechanicGseLearn: "Sleeper is an environment GSE must read, not compete with. Its developer API (if available for read access with user auth) is a potential sync target",
    gseExceedMethods: ["first-of-kind-system"],
    gseExceedNarrative: "GSE overlays intelligence on top of Sleeper-hosted drafts rather than replacing the platform",
    confidence: "HIGH",
    sourceNote: "Well-documented platform with developer API",
  },
  {
    id: "yahoo-fantasy",
    name: "Yahoo Fantasy",
    url: "https://sports.yahoo.com/fantasy",
    categories: ["league-host", "draft-assistant"],
    targetUser: "Mainstream fantasy player; established leagues",
    corePain: "Need a trusted, free platform to host a league",
    corePromise: "Largest free fantasy platform with all formats, commissioner tools, and NFL integration",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: true,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["free-with-ads", "sportsbook-affiliate"],
    pricingNote: "Free platform; monetizes through advertising and affiliate sports betting",
    strongestFeature: "Largest user base; historical league data stored; most people have Yahoo leagues already",
    weakestOrMissing: "Draft recommendations are basic; no pick thesis; no intelligence layer",
    mechanicGseLearn: "Historical draft data is stored by Yahoo — if users can export or sync it, GSE can build Manager Genomes from real prior-year data",
    gseExceedMethods: ["league-memory", "draft-futures-engine", "voice-jarvis", "process-grading"],
    gseExceedNarrative: "Yahoo has the data. GSE has the intelligence. The combination of Yahoo export + GSE League Memory Graph is the moat",
    confidence: "HIGH",
    sourceNote: "Well-documented major platform",
  },
  {
    id: "espn-fantasy",
    name: "ESPN Fantasy",
    url: "https://www.espn.com/fantasy",
    categories: ["league-host", "draft-assistant"],
    targetUser: "Mainstream fantasy player; sports media ecosystem",
    corePain: "Want fantasy integrated with news, scores, and sports content from ESPN",
    corePromise: "Fantasy integrated with ESPN's sports content ecosystem: news, scores, analysis, live scoring",
    features: {
      draftAssistant: true,
      mockDraft: true,
      liveDraftSync: "none",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: true,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: true,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["free-with-ads", "sportsbook-affiliate"],
    pricingNote: "Free platform with ESPN+ ecosystem; ESPN Bet affiliate integration",
    strongestFeature: "ESPN content integration; large established user base; historical league data",
    weakestOrMissing: "Third-party API access is severely restricted; minimal decision intelligence",
    mechanicGseLearn: "ESPN's API restrictions mean GSE must rely on user-uploaded export data for ESPN leagues — manual upload UX must be excellent",
    gseExceedMethods: ["league-memory", "draft-futures-engine", "voice-jarvis"],
    gseExceedNarrative: "ESPN hosts the league; GSE provides the intelligence layer above it",
    confidence: "HIGH",
    sourceNote: "Major platform with well-known restrictions",
  },
  {
    id: "sabersim",
    name: "SaberSim",
    url: "https://sabersim.com",
    categories: ["dfs-optimizer", "dfs-portfolio"],
    targetUser: "Serious DFS grinder; tournament and cash game players",
    corePain: "Building optimal DFS lineups requires simulation, not just ranking — single optimal lineup doesn't win GPPs",
    corePromise: "Monte Carlo DFS simulation: simulates thousands of outcomes to find lineups that win across many scenarios",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Monthly subscription for full simulation access — source gap, verify",
    strongestFeature: "Monte Carlo portfolio simulation: finds lineups optimal across a distribution of outcomes, not just the single highest-projection lineup",
    weakestOrMissing: "No narrative intelligence; no source reliability; DFS-only with no fantasy season integration",
    mechanicGseLearn: "Simulation over single-point optimization: GSE's DFS optimizer phases 1-10 already implement this. The key insight is portfolio construction via simulation, not single lineup optimization",
    gseExceedMethods: ["narrative-inflation-detection", "deeper-evidence-layer", "calibration-loop"],
    gseExceedNarrative: "GSE already built Monte Carlo simulation in DFS phases 1-10. The differentiation is wiring narrative intelligence and source reliability into projection inputs",
    confidence: "HIGH",
    sourceNote: "Well-known DFS tool with clear simulation-based positioning",
  },
  {
    id: "rotogrinders",
    name: "RotoGrinders / LineupHQ",
    url: "https://rotogrinders.com",
    categories: ["dfs-optimizer", "content-media", "player-insights"],
    targetUser: "DFS community member; casual to serious DFS player",
    corePain: "DFS requires a community to share ownership, projections, and strategy — can't grind alone",
    corePromise: "DFS community hub: optimizer, projections, ownership models, player ratings, game theory, forum, and content",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "premium-community", "content-tools-bundle"],
    pricingNote: "Freemium + premium community tiers — source gap, verify",
    strongestFeature: "Community ownership models: crowdsourced ownership projections and game-theory optimizer (GTO lineups)",
    weakestOrMissing: "No narrative intelligence layer; no source reliability scoring; community-dependent ownership accuracy",
    mechanicGseLearn: "Game theory optimal (GTO) lineup construction: when the field is predictable, optimal ownership deviation maximizes expected ROI in tournaments",
    gseExceedMethods: ["narrative-inflation-detection", "deeper-evidence-layer", "trust-ledger"],
    gseExceedNarrative: "GSE applies GTO reasoning to DFS but adds narrative/source reliability layer to identify when ownership models are wrong because they're based on hype",
    confidence: "HIGH",
    sourceNote: "Well-known DFS platform",
  },
  {
    id: "fantasylabs",
    name: "FantasyLabs",
    url: "https://www.fantasylabs.com",
    categories: ["dfs-optimizer", "player-insights"],
    targetUser: "Analytical DFS player who wants to build and backtest their own models",
    corePain: "Pre-built DFS tools use someone else's model; serious players need their own model with historical validation",
    corePromise: "Build your own player/game models, backtest them against historical results, and apply them to current slates",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: true,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Subscription tiers by feature access — source gap, verify",
    strongestFeature: "Custom model builder with backtesting against historical DFS results; ProModels for users who don't build their own",
    weakestOrMissing: "Complex for casual users; no fantasy season-long integration; no narrative intelligence",
    mechanicGseLearn: "Backtesting creates calibration: a model that's been tested against historical results has a track record. This is the foundation of GSE's Autopsy/Calibration loop and Trust Ledger",
    gseExceedMethods: ["calibration-loop", "trust-ledger", "narrative-inflation-detection"],
    gseExceedNarrative: "GSE applies calibration discipline to both DFS and season-long fantasy, with the Trust Ledger proving GSE didn't rewrite history after outcomes",
    confidence: "HIGH",
    sourceNote: "Well-documented DFS analytics platform",
  },
  {
    id: "stokastic",
    name: "Stokastic",
    url: "https://stokastic.com",
    categories: ["dfs-optimizer", "dfs-portfolio"],
    targetUser: "DFS tournament player seeking simulated optimal portfolios",
    corePain: "DFS tournaments are won by portfolio construction, not single optimal lineup",
    corePromise: "Simulation-based DFS portfolio optimizer: game theory, expected value, ownership leverage",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: false,
      customProjections: true,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Subscription access — source gap, verify",
    strongestFeature: "Expected value framing for DFS portfolios; simulation-based portfolio construction with game theory optimal concepts",
    weakestOrMissing: "No narrative intelligence; no source reliability; no fantasy season integration",
    mechanicGseLearn: "EV-based portfolio framing: the user's DFS decisions are a portfolio with expected value, variance, and correlation — not individual bets",
    gseExceedMethods: ["narrative-inflation-detection", "deeper-evidence-layer"],
    gseExceedNarrative: "GSE adds the source/narrative intelligence layer on top of simulation to identify when projection inputs are inflated by hype",
    confidence: "MEDIUM",
    sourceNote: "Public product page",
  },
  {
    id: "action-network",
    name: "Action Network",
    url: "https://www.actionnetwork.com",
    categories: ["betting-analytics", "odds-intelligence", "content-media"],
    targetUser: "Sports bettor seeking sharpness signals; recreational to serious bettors",
    corePain: "Sportsbook lines aren't fair; need market intelligence to find value before the public reacts",
    corePromise: "Sports betting intelligence: odds, line movement, public/sharp tracking, CLV, picks, and community",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: true,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "sportsbook-affiliate"],
    pricingNote: "Action+ subscription; significant sportsbook affiliate revenue — source gap on exact pricing",
    strongestFeature: "Public/sharp bet tracking and CLV measurement; the best betting market data visualization in consumer sports media",
    weakestOrMissing: "Recommendations don't include counter-evidence; heavy sportsbook affiliate integration creates conflicts; no process grading",
    mechanicGseLearn: "CLV as a calibration metric: a recommendation that beats the closing line over time is demonstrably sharp. This is how GSE should measure prediction quality, not outcome",
    gseExceedMethods: ["deeper-evidence-layer", "process-grading", "trust-ledger", "calibration-loop"],
    gseExceedNarrative: "GSE takes Action Network's CLV concept and applies it to ALL recommendation types (fantasy, DFS, prediction) with mandatory counter-evidence and Trust Ledger proof",
    confidence: "HIGH",
    sourceNote: "Well-documented major sports media/analytics brand",
  },
  {
    id: "oddsjam",
    name: "OddsJam",
    url: "https://oddsjam.com",
    categories: ["odds-intelligence", "betting-analytics"],
    targetUser: "Serious sports bettor seeking positive expected value",
    corePain: "Finding +EV bets requires comparing lines across 50+ sportsbooks in real time — impossible manually",
    corePromise: "Real-time positive EV finder, arbitrage alerts, and CLV tracker across all major sportsbooks",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: true,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "sportsbook-affiliate"],
    pricingNote: "Monthly subscription; sportsbook affiliate for sign-up bonuses — public page estimate",
    strongestFeature: "Real-time odds comparison across 50+ books; arbitrage and +EV alerts are genuinely useful for sharp bettors",
    weakestOrMissing: "No fantasy/DFS integration; pure odds arbitrage; no explanation layer for why a line is off",
    mechanicGseLearn: "Odds dispersion as a signal: when one book is significantly off the rest, there's information in that gap. GSE's Prop-to-Projection Delta engine uses this concept",
    gseExceedMethods: ["deeper-evidence-layer", "narrative-inflation-detection"],
    gseExceedNarrative: "GSE applies market-dispersion reasoning to DFS ownership and fantasy valuation — where is the 'crowd' wrong relative to real signal?",
    confidence: "HIGH",
    sourceNote: "Well-documented product with clear positioning",
  },
  {
    id: "unabated",
    name: "Unabated",
    url: "https://unabated.com",
    categories: ["betting-analytics", "odds-intelligence"],
    targetUser: "Sharp sports bettor; CLV-focused analytics user",
    corePain: "Most sports betting content teaches you to pick winners, not to evaluate your own sharpness",
    corePromise: "Sharp betting tools: CLV tracking, expected value, market comparison, and education for long-term bettors",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: true,
      calibrationTracking: true,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Subscription — source gap, verify",
    strongestFeature: "Education-first approach to sharp betting: CLV tracking makes users smarter, not just winning in the short term",
    weakestOrMissing: "Narrow audience (sharp bettors); no fantasy/DFS integration; no draft tools",
    mechanicGseLearn: "Process grading via CLV: 'Did this decision beat the market?' is a better question than 'Did I win?' This is the philosophy behind GSE's process grading and GM Ledger",
    gseExceedMethods: ["process-grading", "calibration-loop", "trust-ledger"],
    gseExceedNarrative: "Unabated teaches this philosophy for betting; GSE applies it across fantasy, DFS, and sports prediction with the GM Ledger as the implementation",
    confidence: "MEDIUM",
    sourceNote: "Public product page and community reputation",
  },
  {
    id: "pff",
    name: "Pro Football Focus (PFF)",
    url: "https://www.pff.com",
    categories: ["player-insights", "dfs-optimizer", "betting-analytics", "content-media"],
    targetUser: "Advanced NFL analyst; serious DFS player; sophisticated fantasy manager",
    corePain: "NFL statistics don't capture actual performance quality — a receiver can catch 4/4 targets for 35 yards and outperform expectations",
    corePromise: "Play-by-play grades for every player on every play: quantify performance independent of outcomes",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "b2b-data-licensing"],
    pricingNote: "Fan/Analyst/Elite tiers; significant B2B data licensing to NFL teams/media — public page",
    strongestFeature: "Play-by-play grading creates vocabulary users adopt (PFF grade, route participation, pass blocking efficiency) — proprietary metrics that become reference standards",
    weakestOrMissing: "Data is expensive; no draft intelligence layer; grades don't translate directly to fantasy projections",
    mechanicGseLearn: "Proprietary metric vocabulary: when your grading system becomes the reference standard, users adopt your language. GSE's GM Rating and process grades should aspire to this",
    gseExceedMethods: ["first-of-kind-system", "process-grading"],
    gseExceedNarrative: "GSE applies the 'grade process not outcome' philosophy to fantasy decisions, making GM Rating the reference standard for decision quality",
    confidence: "HIGH",
    sourceNote: "Major industry data provider — well documented",
  },
  {
    id: "covers",
    name: "Covers",
    url: "https://www.covers.com",
    categories: ["betting-analytics", "odds-intelligence", "content-media"],
    targetUser: "Sports bettor; casual to serious",
    corePain: "Want betting information and consensus without paying for premium tools",
    corePromise: "Free sports betting information: picks, odds, consensus, trends, and news",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["free-with-ads", "sportsbook-affiliate"],
    pricingNote: "Free; primary revenue from sportsbook affiliate commissions",
    strongestFeature: "Consensus percentage data and historical ATS records; trusted long-term brand in sports betting",
    weakestOrMissing: "No prediction intelligence; content is affiliate-revenue-driven; no evidence layer for picks",
    mechanicGseLearn: "ATS record tracking: a team's record against the spread is publicly available and meaningful. GSE should track model accuracy against the relevant market benchmark",
    gseExceedMethods: ["deeper-evidence-layer", "trust-ledger", "calibration-loop"],
    gseExceedNarrative: "Covers is affiliate content; GSE is evidence-based intelligence. Completely different trust posture",
    confidence: "HIGH",
    sourceNote: "Well-known long-running sports betting site",
  },
  {
    id: "teamrankings",
    name: "TeamRankings",
    url: "https://www.teamrankings.com",
    categories: ["betting-analytics", "sports-prediction"],
    targetUser: "Analytical sports bettor and fantasy player",
    corePain: "Who is actually better? Need mathematical rankings beyond wins/losses",
    corePromise: "Data-driven team and game predictions: ATS records, betting trends, historical performance metrics",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: true,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription"],
    pricingNote: "Free basic + paid premium — source gap, verify",
    strongestFeature: "Historical trend databases: ATS records, home/away splits, totals performance, rest-of-season data going back many years",
    weakestOrMissing: "No player-level intelligence; no DFS or fantasy integration; historical data without real-time narrative",
    mechanicGseLearn: "Historical trend databases have legitimate predictive value when properly calibrated. GSE's calibration engine should track model performance against these benchmarks",
    gseExceedMethods: ["deeper-evidence-layer", "calibration-loop"],
    gseExceedNarrative: "TeamRankings is data without intelligence layer; GSE adds Signal Courtroom evidence debate and Trust Ledger",
    confidence: "HIGH",
    sourceNote: "Long-running analytics site with well-documented methodology",
  },
  {
    id: "underdog",
    name: "Underdog Fantasy",
    url: "https://underdogfantasy.com",
    categories: ["best-ball-platform", "draft-assistant"],
    targetUser: "Best ball and pick'em daily fantasy player",
    corePain: "Traditional DFS requires too much lineup management; want draft-and-done fantasy",
    corePromise: "Best ball draft games: draft a team, best lineup is automatically set each week",
    features: {
      draftAssistant: false,
      mockDraft: true,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: true,
      projections: true,
      adp: true,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["platform-host-fees", "freemium-subscription"],
    pricingNote: "Entry fees for contests; free to use platform — real money contest fees",
    strongestFeature: "Best ball draft games with real-money contests; fastest-growing draft format; massive prize pools attract quality competition",
    weakestOrMissing: "Not an intelligence tool; no pick recommendations; no season management; real-money product with significant regulatory exposure",
    mechanicGseLearn: "Best ball forces pure draft quality — no waiver management or lineups. Portfolio exposure across many drafts becomes the game. GSE can build best ball specific draft intelligence",
    gseExceedMethods: ["draft-futures-engine", "process-grading"],
    gseExceedNarrative: "GSE provides best-ball specific draft intelligence: stack exposure, positional breadth, upside portfolio — all optimized for best-ball scoring",
    confidence: "HIGH",
    sourceNote: "Well-known best ball platform",
  },
  {
    id: "rotoviz",
    name: "RotoViz",
    url: "https://rotoviz.com",
    categories: ["player-insights", "dfs-optimizer", "content-media"],
    targetUser: "Analytical DFS and fantasy player; data-driven",
    corePain: "Fantasy/DFS analytics tools present outputs without letting users explore the underlying data",
    corePromise: "Advanced analytics for DFS and fantasy: game script modeling, historical stat exploration, projections, and the RotoViz App optimizer",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "content-tools-bundle"],
    pricingNote: "Subscription for full tool access — source gap, verify",
    strongestFeature: "Game script modeling: projects how game script (score, pace, run/pass ratio) affects individual player outcomes — one of the most advanced player contextualization methods",
    weakestOrMissing: "Requires analytical sophistication; no fantasy season-long integration; no narrative intelligence",
    mechanicGseLearn: "Game script as projection input: a team's projected game script (expected points, pace, game total) should flow directly into individual player projections. GSE's Projection Factory should include game script",
    gseExceedMethods: ["deeper-evidence-layer", "narrative-inflation-detection"],
    gseExceedNarrative: "GSE incorporates game script context into projection inputs while adding narrative reliability scoring on top",
    confidence: "MEDIUM",
    sourceNote: "Well-known analytical DFS site",
  },
  {
    id: "establish-the-run",
    name: "Establish The Run",
    url: "https://establishtherun.com",
    categories: ["content-media", "player-insights", "dfs-optimizer"],
    targetUser: "Serious DFS player seeking running back expertise and game theory",
    corePain: "RB is the most complex position in DFS; depth charts, usage rates, game script, and ownership all interact",
    corePromise: "Deep RB analysis, air yards tracking, game theory DFS strategy, and projection tools for serious DFS grinders",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: true,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "content-tools-bundle"],
    pricingNote: "Subscription for premium tools + articles — source gap, verify",
    strongestFeature: "Air yards and target share analytics; game theory discussions that challenge conventional DFS thinking; deep RB workload tracking",
    weakestOrMissing: "Narrow position focus; no draft tools; no season-long fantasy integration",
    mechanicGseLearn: "Usage rate as projection input: target share, air yards, snap rate, route participation, and rush share are the actual drivers of fantasy value — not projected points. GSE should show these inputs",
    gseExceedMethods: ["deeper-evidence-layer", "narrative-inflation-detection"],
    gseExceedNarrative: "GSE incorporates usage-rate signals as verifiable evidence in pick recommendations, not just projection outputs",
    confidence: "MEDIUM",
    sourceNote: "Well-known DFS/analytics content brand",
  },
  {
    id: "sportsline",
    name: "SportsLine",
    url: "https://www.sportsline.com",
    categories: ["sports-prediction", "betting-analytics", "player-insights"],
    targetUser: "Sports bettor and fantasy player seeking expert model-backed picks",
    corePain: "Don't know whose predictions to trust; want model-backed expert picks across sports",
    corePromise: "Model-based and expert sports picks; player projections; picks from verified experts with track records",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: true,
      dfsOptimizer: false,
      playerNewsInjury: true,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "sportsbook-affiliate"],
    pricingNote: "Monthly/annual subscription + sportsbook affiliate — public page estimate",
    strongestFeature: "Model ratings with claimed performance records; multi-sport coverage; expert picks with stated track records",
    weakestOrMissing: "No mandatory counter-evidence; no process grading; track records may not be independently audited",
    mechanicGseLearn: "Model ratings need independent verification: claimed track records must be auditable. GSE's Trust Ledger prevents retroactive editing of pick history",
    gseExceedMethods: ["trust-ledger", "calibration-loop", "deeper-evidence-layer"],
    gseExceedNarrative: "GSE's GM Ledger uses tamper-evident record keeping (Merkle chain concept) to prove picks were made before outcomes were known",
    confidence: "MEDIUM",
    sourceNote: "Public product page — CBS Sports subsidiary",
  },
  {
    id: "dimers",
    name: "Dimers",
    url: "https://www.dimers.com",
    categories: ["sports-prediction", "betting-analytics"],
    targetUser: "Casual to moderate sports bettor seeking model-backed picks",
    corePain: "Don't know how to evaluate betting picks or who to trust",
    corePromise: "Model-based sports predictions with probability-based language; transparent about uncertainty",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: true,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["sportsbook-affiliate", "free-with-ads"],
    pricingNote: "Primarily free, monetizes through sportsbook affiliate links",
    strongestFeature: "Probability language: '63% chance team wins' rather than 'strong play' — educates rather than manipulates",
    weakestOrMissing: "No evidence layer; no counter-thesis; primarily affiliate revenue creates conflict",
    mechanicGseLearn: "Probability language builds trust and accuracy: saying '63% win probability' is more honest than 'strong play.' GSE should use probability ranges consistently",
    gseExceedMethods: ["deeper-evidence-layer", "trust-ledger", "process-grading"],
    gseExceedNarrative: "GSE uses probability language AND backs it with evidence and uncertainty — not just a number without reasoning",
    confidence: "MEDIUM",
    sourceNote: "Public product page",
  },
  {
    id: "bettingpros",
    name: "BettingPros",
    url: "https://www.bettingpros.com",
    categories: ["odds-intelligence", "betting-analytics"],
    targetUser: "Sports bettor seeking odds comparison and expert consensus",
    corePain: "Odds vary across books; hard to find the best line and know which experts to follow",
    corePromise: "Odds aggregator with best-line finder, expert consensus picks, and alerts",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: true,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["free-with-ads", "sportsbook-affiliate"],
    pricingNote: "Primarily free with affiliate revenue",
    strongestFeature: "Best-line finder across books; expert consensus as social proof mechanism",
    weakestOrMissing: "No intelligence layer; picks are aggregated consensus without evidence or counter-thesis",
    mechanicGseLearn: "Consensus as signal, not verdict: expert consensus is one data point, not the answer. GSE should aggregate it with other signals and show divergence",
    gseExceedMethods: ["deeper-evidence-layer", "trust-ledger"],
    gseExceedNarrative: "GSE treats consensus as one input among many, with source reliability weighting — not the final word",
    confidence: "MEDIUM",
    sourceNote: "Public product page — well-known in sports betting community",
  },
  {
    id: "vsin",
    name: "VSiN (Vegas Stats & Information Network)",
    url: "https://www.vsin.com",
    categories: ["betting-analytics", "content-media"],
    targetUser: "Serious sports bettor seeking insider Vegas-perspective content",
    corePain: "Public sports media doesn't explain how Vegas sets lines or why line movement happens",
    corePromise: "The sports betting network for serious bettors: line movement analysis, sharp action education, and industry insider content",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: false,
      customScoring: false,
      auctionSupport: false,
      keeperDynasty: false,
      superflex: false,
      idp: false,
      bestBall: false,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: false,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: false,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["freemium-subscription", "content-tools-bundle"],
    pricingNote: "Subscription for premium content — source gap, verify",
    strongestFeature: "Insider market mechanics education: teaching how books think, not just picks",
    weakestOrMissing: "Content-only; no tools; no data; no prediction system",
    mechanicGseLearn: "Market mechanics education builds a sophisticated user who trusts the product more. GSE's GSN Transmission should teach users how to think about lines and signals",
    gseExceedMethods: ["first-of-kind-system", "deeper-evidence-layer"],
    gseExceedNarrative: "VSiN teaches Vegas mechanics through media; GSE embeds that education into the decision engine itself",
    confidence: "MEDIUM",
    sourceNote: "Sports media brand — public information",
  },
  {
    id: "myfl",
    name: "MyFantasyLeague (MFL)",
    url: "https://www.myfantasyleague.com",
    categories: ["league-host", "auction-tools", "dynasty-tools"],
    targetUser: "Advanced dynasty and highly customized league managers",
    corePain: "Yahoo/ESPN can't support extreme customization: huge rosters, custom scoring, auction, dynasty",
    corePromise: "The most customizable fantasy platform: any format, any roster size, any scoring, any league",
    features: {
      draftAssistant: false,
      mockDraft: true,
      liveDraftSync: "oauth-api",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: true,
      idp: true,
      bestBall: true,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: false,
      customProjections: false,
      historicalDraftStorage: true,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["platform-host-fees"],
    pricingNote: "Annual commissioner fees — public page",
    strongestFeature: "Deepest customization of any fantasy platform; API access for data export; multi-year league history stored",
    weakestOrMissing: "No intelligence layer; no draft recommendations; very dated UI; tools must come from third parties",
    mechanicGseLearn: "MFL's API exports enable GSE to import multi-year league history for Manager Genome. This is one of the richest data sources available",
    gseExceedMethods: ["league-memory", "draft-futures-engine", "voice-jarvis"],
    gseExceedNarrative: "MFL provides the infrastructure and history; GSE provides the intelligence layer on top",
    confidence: "HIGH",
    sourceNote: "Long-running platform with known API",
  },
  {
    id: "fantrax",
    name: "Fantrax",
    url: "https://www.fantrax.com",
    categories: ["league-host", "dynasty-tools", "auction-tools"],
    targetUser: "Advanced, custom, dynasty, and college fantasy managers",
    corePain: "No platform supports extreme IDP, college, and custom dynasty formats properly",
    corePromise: "Advanced league hosting with IDP, custom scoring, dynasty, best ball, and college football",
    features: {
      draftAssistant: false,
      mockDraft: false,
      liveDraftSync: "none",
      leagueSync: true,
      customScoring: true,
      auctionSupport: true,
      keeperDynasty: true,
      superflex: true,
      idp: true,
      bestBall: true,
      projections: false,
      adp: false,
      tiers: false,
      positionRunAlerts: false,
      projectedAvailability: false,
      rosterNeeds: false,
      pickRecommendations: false,
      draftGradeAnalyzer: false,
      tradeCalculator: false,
      waiverTool: true,
      startSit: false,
      dfsOptimizer: false,
      playerNewsInjury: false,
      browserExtension: false,
      mobileApp: true,
      customProjections: false,
      historicalDraftStorage: true,
      managerGenome: false,
      voiceAssistant: false,
      pickThesisCounterThesis: false,
      draftFuturesEngine: false,
      opponentModeling: false,
      rosterDestinySimulator: false,
      biasDetection: false,
      processGrading: false,
      calibrationTracking: false,
      narrativeInflationDetection: false,
    },
    monetization: ["platform-host-fees"],
    pricingNote: "Commissioner annual fees; advanced features cost more — public page",
    strongestFeature: "IDP and college fantasy support; extreme customization; included in FantasyPros' supported host list",
    weakestOrMissing: "No intelligence layer; no draft tools; requires third-party intelligence apps",
    mechanicGseLearn: "Fantrax IDP support: GSE's draft intelligence should properly weight defensive players in IDP leagues — positions, scoring, and positional scarcity all change significantly",
    gseExceedMethods: ["league-memory", "draft-futures-engine"],
    gseExceedNarrative: "Fantrax hosts; GSE provides IDP-aware draft intelligence with proper positional scarcity modeling",
    confidence: "HIGH",
    sourceNote: "Well-known advanced platform",
  },
] as const;

export const COMPETITOR_COUNT = COMPETITOR_INTELLIGENCE.length;
