/**
 * Agent provisioning registry — the machine-readable list of every leveraged
 * account GSE wants created and wired, consolidated from docs/ops/CREDITS.md and
 * docs/ops/GSE_CREDITS_PROGRAMS_ACTION_PACK_V3.md (claim-order traps included).
 *
 * An executing agent (see docs/ops/agent-provisioning/RUNBOOK_FOR_AGENT.md)
 * walks this list in priority order and drives each account to `doneWhen`.
 *
 * automation levels (escalation ladder — always attempt the least-human first):
 *   api_only            — provisionable via API/token, no browser at all
 *   headless_first      — try Playwright in the session container; escalate on wall
 *   supervised_browser  — founder's Claude-in-Chrome; human passes CAPTCHA/OAuth
 *   founder_assisted    — agent drives + prefills, founder present (KYC/tax/OAuth)
 *   founder_only        — applications/once-ever traps; agent PREPARES, never submits
 *
 * LAWS: no CAPTCHA/anti-bot evasion (CLAUDE.md). Credit-program APPLICATIONS are
 * founder-only (CREDITS.md). Secrets land in Vercel env, never in this repo.
 */

export const AGENT_EMAIL = "gse-ops@agentmail.to"; // AgentMail inbox, created 2026-08-07

export const CATEGORIES = ["free_lane_llm", "cloud_credits", "dev_systems", "affiliate_partner"];
export const AUTOMATION_LEVELS = [
  "api_only",
  "headless_first",
  "supervised_browser",
  "founder_assisted",
  "founder_only",
];
export const VERIFICATION = ["email", "oauth_google", "captcha_likely", "kyc_tax", "none"];
export const STATUSES = ["todo", "existing", "blocked"];

export const REGISTRY = [
  // ---------------- P0 — free-lane LLM (kills cash Jynx) ----------------
  {
    id: "cerebras",
    name: "Cerebras Cloud (free tier)",
    category: "free_lane_llm",
    priority: "P0",
    status: "todo",
    signupUrl: "https://cloud.cerebras.ai",
    email: AGENT_EMAIL,
    automation: "supervised_browser",
    verification: "captcha_likely",
    envTargets: ["CEREBRAS_API_KEY", "CONTENT_FREE_LANE_ENABLED"],
    doneWhen: "verify-credit-stack.mjs exit 0 with contentPlanPrimary=cerebras_free",
    traps: [],
    notes: "Primary free lane (gpt-oss-120b). Headless attempt allowed first; expect Turnstile wall.",
  },
  {
    id: "groq",
    name: "Groq (free tier)",
    category: "free_lane_llm",
    priority: "P0",
    status: "todo",
    signupUrl: "https://console.groq.com",
    email: AGENT_EMAIL,
    automation: "supervised_browser",
    verification: "oauth_google",
    envTargets: ["FREE_LANE_SECONDARY_BASE_URL", "FREE_LANE_SECONDARY_MODEL", "FREE_LANE_SECONDARY_API_KEY", "INTERNAL_LLM_API_KEY"],
    doneWhen: "secondary free lane configured OR internal LLM key set; posture reflects it",
    traps: [],
    notes: "Doubles as internal LLM tier per CREDITS.md. OpenAI-compat base URL is the Groq console's /openai/v1 path — set it in FREE_LANE_SECONDARY_BASE_URL, not here.",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "free_lane_llm",
    priority: "P0",
    status: "todo",
    signupUrl: "https://openrouter.ai",
    email: AGENT_EMAIL,
    automation: "headless_first",
    verification: "email",
    envTargets: ["FREE_LANE_SECONDARY_BASE_URL", "FREE_LANE_SECONDARY_MODEL", "FREE_LANE_SECONDARY_API_KEY"],
    doneWhen: "key minted (provisioning API after first key) + free model smoke passes",
    traps: [],
    notes: "Has key-provisioning API once account exists — most automatable secondary. Free models available.",
  },
  {
    id: "google-ai-studio",
    name: "Google AI Studio (free Gemini key)",
    category: "free_lane_llm",
    priority: "P1",
    status: "todo",
    signupUrl: "https://aistudio.google.com",
    email: "founder-google-account",
    automation: "founder_assisted",
    verification: "oauth_google",
    envTargets: ["FREE_LANE_SECONDARY_BASE_URL", "FREE_LANE_SECONDARY_MODEL", "FREE_LANE_SECONDARY_API_KEY"],
    doneWhen: "key minted under founder Google account",
    traps: ["Google anti-stacking — see Action Pack §5 before pairing with GCP credits"],
    notes: "OpenAI-compat endpoint exists for Gemini; usable as secondary free lane.",
  },
  {
    id: "nvidia-build",
    name: "NVIDIA build.nvidia.com (free NIM credits)",
    category: "free_lane_llm",
    priority: "P1",
    status: "todo",
    signupUrl: "https://build.nvidia.com",
    email: AGENT_EMAIL,
    automation: "supervised_browser",
    verification: "email",
    envTargets: ["FREE_LANE_SECONDARY_BASE_URL", "FREE_LANE_SECONDARY_MODEL", "FREE_LANE_SECONDARY_API_KEY"],
    doneWhen: "NIM key minted; nemotron free model smoke passes",
    traps: [],
    notes: "Pairs with open-weight catalog entries (nemotron-3-*). Also gateway to Inception.",
  },

  // ---------------- P1 — cloud credits (Claude off cash) ----------------
  {
    id: "aws-activate",
    name: "AWS Activate (Bedrock credits)",
    category: "cloud_credits",
    priority: "P1",
    status: "todo",
    signupUrl: "https://aws.amazon.com/activate/",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: ["CLAUDE_PROVIDER", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_BEDROCK_REGION", "BEDROCK_MODEL_MAP"],
    doneWhen: "jynx.attemptOrder includes bedrock; ledger shows bedrock model ids",
    traps: ["Founders → Portfolio/GenAI sequential, never parallel", "Credits expire 12–24mo", "InvokeModel only for eligibility — never Marketplace Claude-Platform"],
    notes: "Agent PREPARES application text + IAM policy + model map; founder submits.",
  },
  {
    id: "azure-founders-hub",
    name: "Microsoft for Startups Founders Hub (Azure Foundry)",
    category: "cloud_credits",
    priority: "P1",
    status: "todo",
    signupUrl: "https://foundershub.startups.microsoft.com",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: ["CLAUDE_PROVIDER", "AZURE_FOUNDRY_RESOURCE", "AZURE_FOUNDRY_API_KEY", "AZURE_FOUNDRY_MODEL_MAP"],
    doneWhen: "Foundry Claude deployment live AND credit SKU confirmed to cover it",
    traps: ["Verify SKU covers Claude Foundry inference before assuming $0 (Launch Map §Phase 3)"],
    notes: "If SKU excludes Claude → burn Azure on GPU/infra, Claude via Bedrock/Vertex.",
  },
  {
    id: "google-startups",
    name: "Google for Startups Cloud (Vertex credits)",
    category: "cloud_credits",
    priority: "P1",
    status: "todo",
    signupUrl: "https://cloud.google.com/startup",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: ["CLAUDE_PROVIDER", "GOOGLE_VERTEX_PROJECT", "GOOGLE_VERTEX_REGION", "GOOGLE_APPLICATION_CREDENTIALS_JSON", "VERTEX_MODEL_MAP"],
    doneWhen: "jynx.attemptOrder includes vertex; ledger shows @-style vertex ids",
    traps: ["31-day Workspace rule", "yr-2 ~20%", "anti-stacking", "Ads 2× match timed to launch"],
    notes: "",
  },
  {
    id: "anthropic-startups",
    name: "Anthropic Claude for Startups",
    category: "cloud_credits",
    priority: "P1",
    status: "todo",
    signupUrl: "https://claude.com/programs/startups",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: ["ANTHROPIC_API_KEY"],
    doneWhen: "credits visible on Console org",
    traps: ["Partner VC for higher tiers"],
    notes: "Softens the cash fallback lane even after clouds are live.",
  },
  {
    id: "neon-startup",
    name: "Neon Startup program",
    category: "cloud_credits",
    priority: "P2",
    status: "todo",
    signupUrl: "https://neon.com/startups",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: ["DATABASE_URL", "DIRECT_URL"],
    doneWhen: "credits on existing Neon org (DB already live)",
    traps: ["Self-funded ≤$1k or VC ≤$100k eligibility"],
    notes: "",
  },
  {
    id: "vercel-startups",
    name: "Vercel for Startups",
    category: "cloud_credits",
    priority: "P2",
    status: "todo",
    signupUrl: "https://vercel.com/startups",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: [],
    doneWhen: "Pro credits applied to sports-web project",
    traps: ["~$1.2k Activate path may consume the larger slot — confirm terms first (Action Pack §5)"],
    notes: "",
  },

  // ---------------- P2 — dev systems ----------------
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "dev_systems",
    priority: "P2",
    status: "existing",
    signupUrl: "https://huggingface.co",
    email: AGENT_EMAIL,
    automation: "api_only",
    verification: "none",
    envTargets: [],
    doneWhen: "already authenticated as 'Beexly' via MCP",
    traps: [],
    notes: "Community GPU / model-zoo export path per Action Pack §2.",
  },
  {
    id: "posthog-startups",
    name: "PostHog for Startups (~$50k)",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://posthog.com/startups",
    email: "founder@galaxysportsedge.com",
    automation: "headless_first",
    verification: "email",
    envTargets: [],
    doneWhen: "startup credits on existing live org (org 'Galaxy Sports Network' already runs)",
    traps: ["<$5M raised + <2yr eligibility"],
    notes: "Org exists — this is a form on an existing logged-in account; most automatable credit claim.",
  },
  {
    id: "nvidia-inception",
    name: "NVIDIA Inception",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://www.nvidia.com/en-us/startups/",
    email: "founder@galaxysportsedge.com",
    automation: "supervised_browser",
    verification: "email",
    envTargets: [],
    doneWhen: "membership approved (GPU/DGX credit path)",
    traps: [],
    notes: "Self-serve per Action Pack; highest value-per-minute in its table.",
  },
  {
    id: "modal",
    name: "Modal (startup credits)",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://modal.com",
    email: AGENT_EMAIL,
    automation: "supervised_browser",
    verification: "oauth_google",
    envTargets: [],
    doneWhen: "account + credits if KIE GPU path activates",
    traps: ["Claim only if you'll spend (Action Pack rule)"],
    notes: "KIE GPU alternative to Azure.",
  },
  {
    id: "runpod",
    name: "RunPod (startup credits)",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://runpod.io",
    email: AGENT_EMAIL,
    automation: "supervised_browser",
    verification: "email",
    envTargets: [],
    doneWhen: "account + credits if KIE GPU path activates",
    traps: ["Claim only if you'll spend"],
    notes: "",
  },
  {
    id: "github-startups",
    name: "GitHub for Startups",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://github.com/enterprise/startups",
    email: "founder@galaxysportsedge.com",
    automation: "founder_assisted",
    verification: "kyc_tax",
    envTargets: [],
    doneWhen: "Enterprise seats / Actions minutes granted",
    traps: ["Partner-referral usually required"],
    notes: "Private-repo Actions minutes cap is a real current constraint.",
  },
  {
    id: "cloudflare-startups",
    name: "Cloudflare for Startups",
    category: "dev_systems",
    priority: "P2",
    status: "todo",
    signupUrl: "https://www.cloudflare.com/forstartups/",
    email: "founder@galaxysportsedge.com",
    automation: "founder_only",
    verification: "kyc_tax",
    envTargets: [],
    doneWhen: "Workers/KV/R2/D1 credits granted",
    traps: ["Partner-gated; Web Analytics already free — credits are for Workers-class infra"],
    notes: "",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "dev_systems",
    priority: "P2",
    status: "existing",
    signupUrl: "https://sentry.io",
    email: "founder@galaxysportsedge.com",
    automation: "api_only",
    verification: "none",
    envTargets: ["SENTRY_DSN"],
    doneWhen: "DSN pasted (done per live-state notes 2026-08-06); optionally claim startup tier",
    traps: [],
    notes: "",
  },

  // ---------------- P1 revenue — affiliate / partner ----------------
  {
    id: "stripe-live",
    name: "Stripe (live payments)",
    category: "affiliate_partner",
    priority: "P0",
    status: "existing",
    signupUrl: "https://dashboard.stripe.com",
    email: "founder@galaxysportsedge.com",
    automation: "api_only",
    verification: "none",
    envTargets: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    doneWhen: "live + webhook clean (one disabled foreign endpoint left to delete: we_1TgpwCQ2wPZMxx60pnxqD4JC)",
    traps: ["ONE lifetime offer — save Atlas/Activate fee credit for payments go-live (Action Pack §5)"],
    notes: "",
  },
  {
    id: "affiliate-networks",
    name: "Affiliate networks (per docs/revenue partner OS)",
    category: "affiliate_partner",
    priority: "P1",
    status: "todo",
    signupUrl: "https://docs/revenue/OUTREACH_TARGET_LIST",
    email: "founder@galaxysportsedge.com",
    automation: "founder_assisted",
    verification: "kyc_tax",
    envTargets: [],
    doneWhen: "network accounts live per docs/revenue target list; ledger.ts wired to real program ids",
    traps: ["FTC + RG partner policy compliance is pre-written in docs/revenue — follow it, never freelance offer copy", "affiliate-structural-separation guardrail must stay green"],
    notes: "Tax/KYC forms → founder present; agent drives the browser and prefills everything else.",
  },
  {
    id: "the-odds-api",
    name: "The Odds API (paid tier when volume demands)",
    category: "affiliate_partner",
    priority: "P2",
    status: "existing",
    signupUrl: "https://the-odds-api.com",
    email: "founder@galaxysportsedge.com",
    automation: "api_only",
    verification: "none",
    envTargets: ["THE_ODDS_API_KEY"],
    doneWhen: "key live (is); upgrade only when free settle spine insufficient",
    traps: ["Anti-pattern: paying while free settle is healthy (Launch Map)"],
    notes: "",
  },
];

/** Entries an agent can start on right now, least-human-first. */
export function actionable(registry = REGISTRY) {
  const order = { api_only: 0, headless_first: 1, supervised_browser: 2, founder_assisted: 3, founder_only: 4 };
  const prio = { P0: 0, P1: 1, P2: 2 };
  return registry
    .filter((e) => e.status === "todo")
    .sort((a, b) => prio[a.priority] - prio[b.priority] || order[a.automation] - order[b.automation]);
}

/** All env var names the registry expects to eventually exist in Vercel prod. */
export function allEnvTargets(registry = REGISTRY) {
  return [...new Set(registry.flatMap((e) => e.envTargets))].sort();
}
