"use client";

/**
 * StudioBrief — renders the generated weekly brief as a reviewable draft.
 *
 * Production status is explicit: this is a DRAFT for a human to review and
 * publish. Copy it out; nothing is auto-published anywhere.
 */

import { useState } from "react";
import type { WeeklyBrief } from "@/lib/fantasy/studio";
import { BRAND_COLORS } from "@/lib/brand";

export function StudioBrief({ brief }: { brief: WeeklyBrief }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(brief.plaintext);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      /* clipboard unavailable — no-op */
    }
  };

  return (
    <div className="space-y-5">
      {/* draft banner */}
      <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3" style={{ borderColor: `${BRAND_COLORS.softUltraviolet}55`, background: `${BRAND_COLORS.softUltraviolet}0d` }}>
        <span className="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider" style={{ background: `${BRAND_COLORS.softUltraviolet}22`, color: BRAND_COLORS.softUltraviolet }}>Draft · not published</span>
        <span className="text-xs text-ink-400">Generated for human review. Nothing is auto-published. You decide what ships.</span>
        <button type="button" onClick={copy} className="btn btn-ghost btn-sm ml-auto">{copied ? "Copied ✓" : "Copy draft"}</button>
      </div>

      {/* the brief */}
      <article className="surface-card p-6 sm:p-8">
        <p className="text-[10px] uppercase tracking-[0.2em] text-ink-600">Galaxy Studios · The Galaxy Brief</p>
        <h2 className="mt-2 font-display text-3xl text-white">{brief.title}</h2>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink-300">{brief.intro}</p>

        <div className="mt-7 space-y-6">
          {brief.sections.map((s) => (
            <section key={s.heading}>
              <h3 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wider" style={{ color: BRAND_COLORS.orbitalCyan }}>
                <span aria-hidden className="inline-block h-1.5 w-1.5 rounded-full" style={{ background: BRAND_COLORS.orbitalCyan }} />
                {s.heading}
              </h3>
              <ul className="mt-2 space-y-1.5">
                {s.items.map((it, i) => (
                  <li key={i} className="flex gap-2 text-sm leading-relaxed text-ink-200">
                    <span aria-hidden style={{ color: BRAND_COLORS.softUltraviolet }}>▸</span>
                    {it}
                  </li>
                ))}
              </ul>
            </section>
          ))}
        </div>

        <p className="mt-8 border-t pt-4 text-[11px] text-ink-600" style={{ borderColor: BRAND_COLORS.steelGray }}>
          Generated by Galaxy Studios from the live OS. A draft for production, podcast, and waiver-show scripts; never auto-published externally.
        </p>
      </article>
    </div>
  );
}
