/**
 * Matchup Engine — the weekly read that turns the static GSE Rating into a
 * game-specific edge.
 *
 * The GSE Rating (processGrade) grades a player against his position over the
 * season. It is the right BASE number — but it says nothing about who the player
 * lines up against THIS week. A WR1 with an elite rating drawing a shutdown
 * secondary is a different bet than the same WR drawing the league's softest
 * coverage. Sharps adjust for exactly this; the engine does it explicitly.
 *
 * For the current (or most-recent scheduled) week we:
 *   1. Join every team to its opponent from the schedule (schedule-context.ts).
 *   2. Read that OPPONENT's defensive context from the deep data we already
 *      ingest:
 *        • team-environment.ts — opponent defensive EPA percentile (defEpaPct,
 *          where HIGH = stronger defense) and defensive success rate.
 *        • pressure-coverage.ts — pressure the opponent's defense generates
 *          (team-summed def pressures + blitzes) and coverage it allows
 *          (target-weighted passer rating allowed across its charted defenders).
 *        • team-environment.ts pace proxy (noHuddleRate) — tempo/extra-snaps the
 *          opponent's own offense tends to force, a (light) volume tailwind.
 *   3. Fold those opponent reads into a single MATCHUP DELTA in GSE-Rating
 *      points (a bounded adjustment, NOT a re-grade of the model), classify it
 *      favorable / neutral / tough, and write a one-line, plain-English note
 *      naming the REAL driver.
 *   4. Pair each player (from player-model.ts) with his team's opponent read to
 *      produce a matchup-adjusted row: base rating, delta, adjusted read,
 *      opponent, and the note.
 *
 * INTEGRITY (non-negotiable):
 *   • We do NOT change the model. processGrade and MODEL_VERSION are untouched.
 *     The matchup delta is a presentation-layer adjustment shown ALONGSIDE the
 *     base rating; the base rating is always carried through unmodified.
 *   • No fabricated data. Every driver is a real column. When a team's opponent
 *     has no environment/charting context (e.g. early in the season, or a team
 *     below a sample floor), the delta is null, the grade is "—" / unknown, and
 *     the note says so honestly. We never invent an opponent strength.
 *   • This is matchup CONTEXT, not a published forward projection or a pick.
 *     canPublishProjections stays false.
 *
 * SERVER engine: loads player-model, schedule-context, team-environment and
 * pressure-coverage on the server and returns a flat, serializable result. No
 * functions cross the RSC boundary — the page/client owns all render fns.
 * Pattern mirrors play-design.ts / team-environment.ts.
 */

import { latestNflverseInspectionSeason } from "@/lib/trends/nflverse-readiness";
import {
  loadPlayerModel,
  type ModelPosition,
  type PlayerModel,
  type PlayerProfile,
} from "./player-model";
import {
  loadScheduleContext,
  type ScheduleContext,
} from "@/lib/nflverse/schedule-context";
import {
  loadTeamEnvironment,
  type TeamEnvironment,
  type TeamEnvironmentRow,
} from "./team-environment";
import {
  loadNflversePressureCoverage,
  type NflversePressureCoverage,
} from "@/lib/nflverse/pressure-coverage";

type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

/** Direction of the matchup adjustment, derived from the signed delta. */
export type MatchupGrade = "favorable" | "neutral" | "tough" | "unknown";

/**
 * The defensive context for ONE opponent, distilled from the deep data. Every
 * field is real and nullable — a null means that source had no row for this team
 * (honest dash, never a fabricated strength).
 */
export interface OpponentDefense {
  readonly team: string;
  /** Opponent defensive EPA percentile, 0..100, HIGH = stronger defense. */
  readonly defEpaPct: number | null;
  /** Opponent defensive success rate allowed, 0..1, LOWER = better defense. */
  readonly defSuccessRate: number | null;
  /** Opponent pace proxy (own-offense no-huddle rate), 0..1; a light volume read. */
  readonly paceProxy: number | null;
  /** Team-summed pass-rush pressures generated by the opponent's charted defenders. */
  readonly pressures: number | null;
  /** Team-summed blitzes by the opponent's charted defenders. */
  readonly blitzes: number | null;
  /**
   * Target-weighted passer rating the opponent's charted defenders ALLOW in
   * coverage (0..158.3). LOWER = stickier coverage. null when uncharted.
   */
  readonly coveragePasserRatingAllowed: number | null;
  /** Count of the opponent's charted coverage defenders backing the coverage read. */
  readonly coverageDefenders: number;
}

/** A single matchup-adjusted player row — base rating + the weekly adjustment. */
export interface MatchupRow {
  readonly playerId: string;
  readonly name: string;
  readonly team: string;
  readonly position: ModelPosition;
  /** The published GSE Rating, carried through UNCHANGED from player-model. */
  readonly baseRating: number;
  /** Opponent this week ("@ DAL" for away, "vs WAS" for home), or null if no game. */
  readonly opponent: string | null;
  /** True when the player's team is at home this week (null if no game found). */
  readonly isHome: boolean | null;
  /**
   * Matchup-adjusted read = baseRating + matchupDelta, clamped to 0..100. Equal
   * to baseRating when the delta is null (no opponent context). Presentation
   * only — NOT a re-grade of the model.
   */
  readonly adjustedRating: number;
  /** Signed adjustment in GSE-Rating points (bounded). null when no context. */
  readonly matchupDelta: number | null;
  readonly grade: MatchupGrade;
  /** One-line, plain-English read of the matchup, real drivers only. */
  readonly note: string;
  /** The distilled opponent defensive context (for the detail/expanded view). */
  readonly opponentDefense: OpponentDefense | null;
}

export interface MatchupEngine {
  readonly generatedAt: string;
  readonly status: "live" | "source-error";
  readonly season: number;
  readonly week: number | null;
  readonly rows: readonly MatchupRow[];
  /** Distinct games covered this week (for the header KPI). */
  readonly gamesCovered: number;
  /** Players that found a real opponent read (delta !== null). */
  readonly matchupsRead: number;
  readonly canPublishProjections: false;
  readonly note: string;
  readonly sourceUrls: Record<"schedule" | "environment" | "pressureCoverage" | "playerModel", string>;
  readonly error: string | null;
}

// ── Delta tuning ──────────────────────────────────────────────────────────────
// The matchup delta is intentionally MODEST: it nudges the base rating to reflect
// the week's opponent, it does not overwhelm a season-long grade. Each driver
// contributes a bounded number of rating points; the total is clamped to
// ±MAX_DELTA. All thresholds read REAL distributions (percentiles, rates).
const MAX_DELTA = 12; // hard cap on the absolute weekly adjustment, in rating points
const FAVORABLE_CUTOFF = 3; // |delta| >= this => favorable/tough; below => neutral

// Driver weights (max points each can swing). Defensive EPA percentile is the
// anchor; success-rate, pressure and coverage are secondary corroborators; pace
// is a light volume tailwind.
const W_DEF_EPA = 7; // opponent overall defensive strength (the anchor)
const W_DEF_SUCCESS = 3; // opponent success rate allowed
const W_PRESSURE = 3; // opponent pass-rush pressure (hurts QBs most)
const W_COVERAGE = 4; // opponent coverage stickiness (hurts pass-catchers most)
const W_PACE = 2; // opponent pace (extra snaps => light volume tailwind)

// Reference bands for normalizing real values into a [-1, 1] driver score.
const PRESSURE_REF = 120; // ~team-season charted pressures where rush reads as elite
const BLITZ_REF = 150; // ~team-season charted blitzes where the look reads as aggressive
const PACE_BASELINE = 0.04; // ~league no-huddle baseline; above => up-tempo
const PACE_SPAN = 0.06; // span that maps a pace gap to the full pace weight
// Coverage passer-rating-allowed band: ~70 is lockdown, ~110 is leaky. Centered
// at 92 (roughly average) and spanning ±22 to the edges.
const COVERAGE_CENTER = 92;
const COVERAGE_SPAN = 22;
// Success-rate-allowed band: ~0.40 stingy, ~0.50 leaky, centered at 0.45.
const SUCCESS_CENTER = 0.45;
const SUCCESS_SPAN = 0.06;

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}
function round(v: number, d = 1): number {
  const f = 10 ** d;
  return Math.round(v * f) / f;
}
/** nflverse team codes are clean abbreviations; normalize defensively for joins. */
function teamKey(team: string): string {
  return team.trim().toUpperCase();
}

/**
 * Aggregate pressure-coverage's PER-PLAYER charting into PER-TEAM opponent reads.
 * The charting files carry individual defenders; a team's pass-rush is the sum of
 * its defenders' pressures/blitzes, and its coverage is the target-weighted mean
 * of its defenders' passer-rating-allowed. Pure — fed real rows by the loader,
 * a fixture by tests. Returns a map keyed by normalized team code.
 */
export function buildTeamDefenseFromCoverage(
  pc: NflversePressureCoverage,
): Map<string, { pressures: number; blitzes: number; covPrWeighted: number; covTargets: number; defenders: number }> {
  const byTeam = new Map<
    string,
    { pressures: number; blitzes: number; covPrWeighted: number; covTargets: number; defenders: number }
  >();
  const get = (team: string) => {
    const key = teamKey(team);
    let t = byTeam.get(key);
    if (!t) {
      t = { pressures: 0, blitzes: 0, covPrWeighted: 0, covTargets: 0, defenders: 0 };
      byTeam.set(key, t);
    }
    return t;
  };
  for (const c of pc.coverage) {
    if (!c.team) continue;
    const t = get(c.team);
    t.defenders += 1;
    t.pressures += c.pressures;
    t.blitzes += c.blitzes;
    // Target-weight the passer rating allowed so a defender targeted often counts
    // more than one rarely thrown at — same weighting coverage uses internally.
    if (c.targets > 0) {
      t.covPrWeighted += c.passerRatingAllowed * c.targets;
      t.covTargets += c.targets;
    }
  }
  return byTeam;
}

/** Index team-environment rows by normalized team code for O(1) opponent lookup. */
function indexEnvironment(env: TeamEnvironment): Map<string, TeamEnvironmentRow> {
  const map = new Map<string, TeamEnvironmentRow>();
  for (const r of env.rows) map.set(teamKey(r.team), r);
  return map;
}

/**
 * Build a team's opponent-for-the-week map from the schedule: each team -> its
 * opponent code + whether the team is at home. Pure. Both sides of every game
 * are recorded so a lookup works from either team's perspective.
 */
export function buildOpponentMap(schedule: ScheduleContext): Map<string, { opponent: string; isHome: boolean }> {
  const map = new Map<string, { opponent: string; isHome: boolean }>();
  for (const g of schedule.rows) {
    const home = teamKey(g.homeTeam);
    const away = teamKey(g.awayTeam);
    if (!home || !away) continue;
    map.set(home, { opponent: away, isHome: true });
    map.set(away, { opponent: home, isHome: false });
  }
  return map;
}

/**
 * Distill an opponent's defensive context from the indexed deep data. Returns
 * null only when the opponent appears in NONE of the sources; otherwise each
 * field is filled where its source has a row and left null where it does not
 * (honest dash). Pure.
 */
export function buildOpponentDefense(
  opponent: string,
  envIndex: ReadonlyMap<string, TeamEnvironmentRow>,
  defIndex: ReadonlyMap<
    string,
    { pressures: number; blitzes: number; covPrWeighted: number; covTargets: number; defenders: number }
  >,
): OpponentDefense | null {
  const key = teamKey(opponent);
  const env = envIndex.get(key);
  const def = defIndex.get(key);
  if (!env && !def) return null;

  const coverageRating = def && def.covTargets > 0 ? round(def.covPrWeighted / def.covTargets, 1) : null;
  return {
    team: key,
    defEpaPct: env ? env.defEpaPct : null,
    defSuccessRate: env ? env.defSuccessRate : null,
    paceProxy: env ? env.noHuddleRate : null,
    pressures: def ? def.pressures : null,
    blitzes: def ? def.blitzes : null,
    coveragePasserRatingAllowed: coverageRating,
    coverageDefenders: def ? def.defenders : 0,
  };
}

/**
 * Position sensitivity to each driver. Pass-catchers (WR/TE) live and die by
 * coverage; QBs are most exposed to pressure; everyone feels overall defensive
 * strength. RBs feel front-seven success-rate more than coverage. These are
 * presentation weights on REAL opponent reads — they do not touch the model.
 */
const POS_SENSITIVITY: Record<ModelPosition, { coverage: number; pressure: number }> = {
  QB: { coverage: 0.6, pressure: 1.0 },
  WR: { coverage: 1.0, pressure: 0.2 },
  TE: { coverage: 0.9, pressure: 0.2 },
  RB: { coverage: 0.3, pressure: 0.4 },
};

interface DeltaResult {
  readonly delta: number | null;
  readonly grade: MatchupGrade;
  /** Internal driver label that dominated the delta, for the note. */
  readonly topDriver: "epa" | "coverage" | "pressure" | "success" | "pace" | null;
  readonly topMagnitude: number;
}

/**
 * Compute the signed matchup delta (in rating points) for a player against an
 * opponent defense. Returns null delta + "unknown" grade when there is no usable
 * opponent context at all. Pure and deterministic.
 *
 * Convention: a STRONG opponent defense pushes the delta NEGATIVE (tougher
 * matchup, lower adjusted read); a WEAK opponent defense pushes it POSITIVE.
 * Each driver is normalized to [-1, 1] where +1 = most favorable for the player.
 */
export function computeMatchupDelta(
  position: ModelPosition,
  opp: OpponentDefense | null,
): DeltaResult {
  if (!opp) return { delta: null, grade: "unknown", topDriver: null, topMagnitude: 0 };

  const sens = POS_SENSITIVITY[position];
  const contributions: { driver: DeltaResult["topDriver"]; points: number }[] = [];

  // Anchor: opponent defensive EPA percentile (HIGH = stronger D => unfavorable).
  // Map 0..100 percentile to +1..-1 (50th pct => 0). High pct => negative.
  if (opp.defEpaPct !== null) {
    const fav = (50 - opp.defEpaPct) / 50; // +1 (weak D) .. -1 (elite D)
    contributions.push({ driver: "epa", points: clamp(fav, -1, 1) * W_DEF_EPA });
  }

  // Opponent success rate allowed (HIGH = leaky => favorable for the player).
  if (opp.defSuccessRate !== null) {
    const fav = (opp.defSuccessRate - SUCCESS_CENTER) / SUCCESS_SPAN; // leaky => +, stingy => -
    contributions.push({ driver: "success", points: clamp(fav, -1, 1) * W_DEF_SUCCESS });
  }

  // Opponent pass rush (MORE pressure/blitz => unfavorable, weighted by position
  // exposure — QBs feel it most). Combine pressures + blitzes into one rush read.
  if (opp.pressures !== null || opp.blitzes !== null) {
    const pressNorm = opp.pressures !== null ? clamp(opp.pressures / PRESSURE_REF, 0, 1) : 0;
    const blitzNorm = opp.blitzes !== null ? clamp(opp.blitzes / BLITZ_REF, 0, 1) : 0;
    const rush = Math.max(pressNorm, blitzNorm); // 0 (none) .. 1 (elite rush)
    const fav = -rush; // more rush => less favorable
    contributions.push({ driver: "pressure", points: fav * W_PRESSURE * sens.pressure });
  }

  // Opponent coverage (LOWER passer rating allowed => stickier => unfavorable,
  // weighted by position exposure — pass-catchers feel it most).
  if (opp.coveragePasserRatingAllowed !== null) {
    const fav = (opp.coveragePasserRatingAllowed - COVERAGE_CENTER) / COVERAGE_SPAN; // leaky => +, sticky => -
    contributions.push({ driver: "coverage", points: clamp(fav, -1, 1) * W_COVERAGE * sens.coverage });
  }

  // Opponent pace (faster opponent => more total snaps => light volume tailwind).
  if (opp.paceProxy !== null) {
    const fav = (opp.paceProxy - PACE_BASELINE) / PACE_SPAN;
    contributions.push({ driver: "pace", points: clamp(fav, -1, 1) * W_PACE });
  }

  if (contributions.length === 0) {
    return { delta: null, grade: "unknown", topDriver: null, topMagnitude: 0 };
  }

  const raw = contributions.reduce((s, c) => s + c.points, 0);
  const delta = round(clamp(raw, -MAX_DELTA, MAX_DELTA), 1);

  // The dominant driver (largest absolute contribution) names the note.
  let top = contributions[0]!;
  for (const c of contributions) if (Math.abs(c.points) > Math.abs(top.points)) top = c;

  const grade: MatchupGrade =
    delta >= FAVORABLE_CUTOFF ? "favorable" : delta <= -FAVORABLE_CUTOFF ? "tough" : "neutral";

  return { delta, grade, topDriver: top.driver, topMagnitude: Math.abs(top.points) };
}

/** Format a percentile (0..100) as a rounded "Nth" read, or a dash. */
function pctText(v: number | null): string {
  return v === null ? "—" : `${Math.round(v)}th-pct`;
}

/**
 * Write the one-line matchup note from the dominant REAL driver. Names the actual
 * opponent strength/weakness; never invents one. Honest fallback when there is no
 * opponent context. Pure.
 */
export function matchupNote(
  grade: MatchupGrade,
  result: DeltaResult,
  opp: OpponentDefense | null,
  oppCode: string | null,
): string {
  if (grade === "unknown" || !opp || result.delta === null) {
    return oppCode
      ? `No opponent defensive context for ${oppCode} yet — base rating shown, unadjusted.`
      : "No game scheduled this week — base rating shown, unadjusted.";
  }
  const o = opp.team;
  const favorable = result.delta > 0;
  switch (result.topDriver) {
    case "epa":
      return favorable
        ? `${o}'s defense grades soft (${pctText(opp.defEpaPct)} by EPA) — a get-right spot.`
        : `${o}'s defense is stout (${pctText(opp.defEpaPct)} by EPA) — a tough draw.`;
    case "coverage":
      return favorable
        ? `${o} has been throwable in coverage (${opp.coveragePasserRatingAllowed} rating allowed) — room to work.`
        : `${o}'s coverage has been sticky (${opp.coveragePasserRatingAllowed} rating allowed) — a hard cover.`;
    case "pressure":
      return favorable
        ? `${o} generates little heat up front — a clean pocket on tap.`
        : `${o} brings real pressure (${opp.pressures ?? "—"} charted) — expect a muddied pocket.`;
    case "success":
      return favorable
        ? `${o} gives up a high success rate (${Math.round((opp.defSuccessRate ?? 0) * 100)}%) — movable.`
        : `${o} keeps plays off-schedule (${Math.round((opp.defSuccessRate ?? 0) * 100)}% allowed) — stingy.`;
    case "pace":
      return favorable
        ? `${o} plays up-tempo — extra snaps could mean extra volume.`
        : `${o} grinds the tempo down — fewer snaps to work with.`;
    default:
      return favorable ? `A net-favorable draw against ${o}.` : `A net-tough draw against ${o}.`;
  }
}

/**
 * Pair every player profile with his team's opponent read and produce the
 * matchup-adjusted rows. Pure — the loader supplies real, loaded results; tests
 * supply fixtures. The base rating is always carried through unchanged.
 */
export function buildMatchupRows(
  model: PlayerModel,
  schedule: ScheduleContext,
  env: TeamEnvironment,
  pc: NflversePressureCoverage,
): MatchupRow[] {
  const opponentMap = buildOpponentMap(schedule);
  const envIndex = indexEnvironment(env);
  const defIndex = buildTeamDefenseFromCoverage(pc);

  const rows: MatchupRow[] = model.profiles.map((p: PlayerProfile) => {
    const game = opponentMap.get(teamKey(p.team)) ?? null;
    const oppCode = game ? game.opponent : null;
    const opp = oppCode ? buildOpponentDefense(oppCode, envIndex, defIndex) : null;
    const result = computeMatchupDelta(p.position, opp);
    const grade = result.grade;
    const delta = result.delta;
    const adjustedRating =
      delta === null ? p.processGrade : Math.round(clamp(p.processGrade + delta, 0, 100));
    const opponentLabel = oppCode ? `${game!.isHome ? "vs" : "@"} ${oppCode}` : null;

    return {
      playerId: p.playerId,
      name: p.name,
      team: p.team,
      position: p.position,
      baseRating: p.processGrade,
      opponent: opponentLabel,
      isHome: game ? game.isHome : null,
      adjustedRating,
      matchupDelta: delta,
      grade,
      note: matchupNote(grade, result, opp, oppCode),
      opponentDefense: opp,
    };
  });

  // Most-favorable matchups first (largest positive delta), then by base rating
  // so a strong player in a neutral spot still ranks above a weak one. Rows with
  // no opponent context (null delta) sink to the bottom but remain visible.
  rows.sort((a, b) => {
    const da = a.matchupDelta ?? Number.NEGATIVE_INFINITY;
    const db = b.matchupDelta ?? Number.NEGATIVE_INFINITY;
    if (db !== da) return db - da;
    return b.baseRating - a.baseRating;
  });
  return rows;
}

function sourceError(
  season: number,
  week: number | null,
  urls: MatchupEngine["sourceUrls"],
  error: string | null,
): MatchupEngine {
  return {
    generatedAt: new Date().toISOString(),
    status: "source-error",
    season,
    week,
    rows: [],
    gamesCovered: 0,
    matchupsRead: 0,
    canPublishProjections: false,
    note: "The matchup read is unavailable right now. We show an empty state instead of a matchup adjustment we can't stand behind.",
    sourceUrls: urls,
    error,
  };
}

/**
 * Load the Matchup Engine: player model + schedule + team environment + pressure
 * coverage, all on the server, folded into matchup-adjusted rows for the week.
 *
 * Failure policy: the player model and the schedule are GATING — without players
 * to rate or a schedule to pair them against there is no board, so a failure in
 * either yields an honest source-error. Team environment and pressure-coverage
 * are ENRICHMENT — if either is thin/unavailable the board still renders, and the
 * affected players simply show a null delta with an honest "no context" note.
 */
export async function loadMatchupEngine({
  season = latestNflverseInspectionSeason(),
  timeoutMs = 20000,
  fetcher = fetch,
}: { season?: number; timeoutMs?: number; fetcher?: FetchLike } = {}): Promise<MatchupEngine> {
  const [modelR, scheduleR, envR, pcR] = await Promise.allSettled([
    loadPlayerModel({ season, timeoutMs, fetcher }),
    loadScheduleContext({ timeoutMs, fetcher }),
    loadTeamEnvironment({ season, timeoutMs, fetcher }),
    loadNflversePressureCoverage({ season, timeoutMs, fetcher }),
  ]);

  const model = modelR.status === "fulfilled" ? modelR.value : null;
  const schedule = scheduleR.status === "fulfilled" ? scheduleR.value : null;
  // Enrichment sources degrade to empty live results rather than taking the page
  // down: a thin/failed env or charting load means null deltas, not a 500.
  const env: TeamEnvironment =
    envR.status === "fulfilled"
      ? envR.value
      : {
          generatedAt: new Date().toISOString(),
          status: "source-error",
          season: 0,
          sourceRows: 0,
          rows: [],
          canPublishProjections: false,
          note: "",
          sourceUrl: "",
          error: envR.reason instanceof Error ? envR.reason.message : "UNKNOWN",
        };
  const pc: NflversePressureCoverage =
    pcR.status === "fulfilled"
      ? pcR.value
      : {
          generatedAt: new Date().toISOString(),
          status: "source-error",
          season,
          seasonType: "REG",
          sourceRows: 0,
          qbPressure: [],
          coverage: [],
          receivingAdvanced: [],
          canPublishProjections: false,
          blockReason: "",
          sourceUrls: { pass: "", def: "", rec: "" },
          error: pcR.reason instanceof Error ? pcR.reason.message : "UNKNOWN",
        };

  const urls: MatchupEngine["sourceUrls"] = {
    playerModel: model?.sourceUrl ?? "",
    schedule: schedule?.sourceUrl ?? "",
    environment: env.sourceUrl,
    pressureCoverage: pc.sourceUrls.def,
  };

  // Gating sources.
  if (!model || model.status === "source-error" || model.profiles.length === 0) {
    return sourceError(
      model?.season ?? 0,
      null,
      urls,
      model?.error ?? (modelR.status === "rejected" ? String(modelR.reason) : "no player profiles"),
    );
  }
  if (!schedule || schedule.status === "source-error" || schedule.rows.length === 0) {
    return sourceError(
      model.season,
      null,
      urls,
      schedule?.error ?? (scheduleR.status === "rejected" ? String(scheduleR.reason) : "no scheduled games"),
    );
  }

  const rows = buildMatchupRows(model, schedule, env, pc);
  const matchupsRead = rows.filter((r) => r.matchupDelta !== null).length;

  return {
    generatedAt: new Date().toISOString(),
    status: "live",
    season: model.season,
    week: schedule.week,
    rows,
    gamesCovered: schedule.rows.length,
    matchupsRead,
    canPublishProjections: false,
    note: "Each player's GSE Rating, adjusted for who he actually lines up against this week — built from the opponent's defensive EPA, coverage, pass rush and pace. The base rating is the season-long grade; the matchup delta is a weekly read, not a re-grade. Context, not a projection or a pick.",
    sourceUrls: urls,
    error: null,
  };
}
