export const AGENT_ACTIONS = [
  "OBSERVE", "ANALYZE", "DRAFT", "VALIDATE", "ROUTE", "ESCALATE", "SUMMARIZE", "REMEMBER", "FORECAST", "TEST", "QUEUE", "REVIEW", "MEASURE", "REPORT",
  "PUBLISH", "SEND_EXTERNAL", "SPEND_MONEY", "DEPLOY", "CHANGE_PUBLIC_CLAIM", "CHANGE_MODEL_WEIGHT", "SCRAPE_PROTECTED_SOURCE", "ENABLE_PUBLIC_PICKS", "ENABLE_BROWSER_CONTROL", "ENABLE_VOICE_CONTROL", "ENABLE_EXTERNAL_TOOL",
] as const;
export type AgentAction = (typeof AGENT_ACTIONS)[number];

export const SAFE_AGENT_ACTIONS = AGENT_ACTIONS.slice(0, 14) as readonly AgentAction[];
export const FORBIDDEN_EXTERNAL_ACTIONS = AGENT_ACTIONS.slice(14) as readonly AgentAction[];
