/**
 * Free multi-provider image pool — pure URL builders.
 *
 * Every provider in this pool is KEYLESS. No API keys are required.
 * These providers serve images directly at a URL — no server fetch required.
 *
 * Order matters: first URL is tried first in the client component.
 * The last entry is always a branded sentinel (never a real image URL;
 * the client component special-cases it to render the CSS fallback).
 *
 * Integrity:
 *   - All images generated by this pool are ABSTRACT / GENERATIVE / BRAND ART.
 *   - They are never presented as real photos of players, games, or events.
 *   - They never fabricate stats or outcomes.
 *   - Keyless by default — no credentials needed.
 *   - Honest branded fallback on failure — never a broken image.
 */

/** Options for image generation. All optional. */
export interface ImagePoolOpts {
  /** Pixel width. Default: 1200. */
  readonly width?: number;
  /** Pixel height. Default: 630. */
  readonly height?: number;
  /**
   * Seed for deterministic rendering. Same seed + same prompt = same image.
   * Defaults to a stable hash of the prompt so renders are consistent across
   * page loads without the caller needing to store a seed.
   */
  readonly seed?: number;
}

/** A single provider entry in the pool. */
export interface ImageProvider {
  /** Stable machine identifier for this provider. */
  readonly id: string;
  /** Human-readable label for status display. */
  readonly label: string;
  /**
   * Full URL that resolves directly to an image (no server fetch required).
   * The sentinel provider uses id "branded-fallback" and its url is the
   * empty string — the client component renders a CSS gradient block instead.
   */
  readonly url: string;
}

/** Branded fallback sentinel ID. Client component checks this. */
export const BRANDED_FALLBACK_ID = "branded-fallback";

/**
 * Maximum prompt length sent to providers.
 * Longer prompts are truncated to this boundary at a word break.
 */
const MAX_PROMPT_LENGTH = 200;

/**
 * Sanitize a prompt for use in a URL:
 *   - Strip newlines and excessive whitespace
 *   - Cap at MAX_PROMPT_LENGTH chars (truncate at word boundary)
 */
function sanitizePrompt(raw: string): string {
  const cleaned = raw.replace(/[\r\n\t]+/g, " ").replace(/\s{2,}/g, " ").trim();
  if (cleaned.length <= MAX_PROMPT_LENGTH) return cleaned;
  // Truncate at word boundary
  const truncated = cleaned.slice(0, MAX_PROMPT_LENGTH);
  const lastSpace = truncated.lastIndexOf(" ");
  return lastSpace > MAX_PROMPT_LENGTH * 0.7 ? truncated.slice(0, lastSpace) : truncated;
}

/**
 * Deterministic seed from a string.
 * Uses a simple djb2-style hash that is fast and stable.
 */
function hashSeed(str: string): number {
  let h = 5381;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) + h) ^ str.charCodeAt(i);
    h = h >>> 0; // keep 32-bit unsigned
  }
  return h % 2_147_483_647; // keep within i32 positive range
}

/**
 * Build the ordered pool of image provider URLs for a given prompt.
 *
 * The list is ordered: try providers in order, fall back down the list.
 * The last entry is always the branded sentinel (CSS gradient fallback).
 *
 * Usage:
 *   const pool = imageSourcePool("NBA matchup abstract");
 *   // pool[0].url → first provider (Pollinations)
 *   // pool[pool.length-1].id === "branded-fallback"
 */
export function imageSourcePool(
  prompt: string,
  opts: ImagePoolOpts = {}
): ImageProvider[] {
  const w = opts.width ?? 1200;
  const h = opts.height ?? 630;
  const safe = sanitizePrompt(prompt);
  const seed = opts.seed ?? hashSeed(safe);
  const enc = encodeURIComponent(safe);

  return [
    // ── Provider 1: Pollinations AI ────────────────────────────────────────
    // Free, keyless, stable. Serves images directly at a predictable URL.
    // Produces abstract/generative art from text prompts.
    // https://pollinations.ai — open-access, no rate-limit key required.
    {
      id: "pollinations",
      label: "Pollinations AI",
      url: `https://image.pollinations.ai/prompt/${enc}?width=${w}&height=${h}&seed=${seed}&nologo=true`,
    },

    // ── Provider 2: Picsum (deterministic, keyless) ────────────────────────
    // https://picsum.photos — free, keyless, deterministic via seed.
    // Abstract/nature photos (not sports-specific). Good as a secondary
    // because it never fails and never breaks; just not generative.
    // Labeled as "abstract stock" — never presented as a real sports photo.
    {
      id: "picsum",
      label: "Picsum abstract stock",
      url: `https://picsum.photos/seed/${seed}/${w}/${h}`,
    },

    // ── Branded fallback sentinel ──────────────────────────────────────────
    // Not a real URL. The client component (PooledImage) detects this id
    // and renders an obsidian→ultraviolet/cyan CSS gradient block instead.
    // This ALWAYS succeeds — the last resort is never a broken image.
    {
      id: BRANDED_FALLBACK_ID,
      label: "Galaxy Sports Edge brand gradient",
      url: "",
    },
  ];
}

/**
 * Returns the URL of the first (highest-priority) provider for a prompt.
 * This is a convenience wrapper; the PooledImage component uses the full list
 * for progressive failover.
 */
export function primaryImageUrl(prompt: string, opts?: ImagePoolOpts): string {
  return imageSourcePool(prompt, opts)[0]!.url;
}

/**
 * Returns the id/label pairs for all providers (excluding sentinel).
 * Useful for status pages or provider health displays.
 */
export function listImageProviders(): Array<{ id: string; label: string }> {
  // Build with a neutral prompt to enumerate the stable provider list.
  return imageSourcePool("status")
    .filter((p) => p.id !== BRANDED_FALLBACK_ID)
    .map(({ id, label }) => ({ id, label }));
}
